"""CLI for ginext-stubgen.

Subcommands
-----------
generate NAMESPACE:VERSION ...
    Regenerate .pyi stubs for the given (Namespace, version) pairs and write
    them into the output directory (default: packages/ginext-stubs/ginext-stubs
    for native mode).

generate-all
    Regenerate stubs for every namespace ginext ships by default, plus the
    __init__.pyi hub, and write them into the output directory.

install
    Run generate-all then reinstall the ginext-stubs package into the active
    venv so the new stubs are immediately available to mypy.

Examples:
    uv run python -m ginext_stubgen generate GLib:2.0
    uv run python -m ginext_stubgen generate-all
    uv run python -m ginext_stubgen install
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from . import find_gir, generate
from . import Mode


def parse_spec(spec: str) -> tuple[str, str]:
    if ":" not in spec:
        raise SystemExit(f"bad spec {spec!r}: want NAMESPACE:VERSION")
    name, version = spec.split(":", 1)
    return name, version


# Default output directory per mode, relative to the repo root.
_DEFAULT_OUT = {
    "native": Path("packages/ginext-stubs/ginext-stubs"),
    "gi": Path("stubs/gi/repository"),
}

# Namespaces (and their canonical version) that ginext-stubs ships. Kept here
# as the single declaration: generate-all iterates this list and _init_pyi
# generates the __init__.pyi hub from it.
_DEFAULT_NAMESPACES: list[tuple[str, str]] = [
    ("GLib", "2.0"),
    ("GObject", "2.0"),
    ("Gio", "2.0"),
    ("GioUnix", "2.0"),
    ("Adw", "1"),
    ("Gst", "1.0"),
    ("GstApp", "1.0"),
    ("GstAudio", "1.0"),
    ("GstBase", "1.0"),
    ("GstVideo", "1.0"),
    ("Gtk", "4.0"),
    ("Gdk", "4.0"),
    ("Gsk", "4.0"),
    ("Pango", "1.0"),
    ("PangoCairo", "1.0"),
    ("Graphene", "1.0"),
    ("GdkPixbuf", "2.0"),
    ("GModule", "2.0"),
    ("HarfBuzz", "0.0"),
    ("freetype2", "2.0"),
    # Test-only namespaces built from packages/typelib. Generated only when the
    # build directory exists; silently skipped otherwise.
    ("GIMarshallingTests", "1.0"),
    ("GoiBench", "1.0"),
    ("Regress", "1.0"),
    ("RegressUnix", "1.0"),
]


def _generate_one(name: str, version: str, out_dir: Path, mode: Mode) -> str | None:
    """Generate a single namespace stub. Returns the namespace name or None on failure."""
    gir = find_gir(name, version)
    if gir is None:
        print(f"warn: {name}-{version}.gir not found — skipping", file=sys.stderr)
        return None
    ns_name, text = generate(gir, mode=mode)
    out_path = out_dir / f"{ns_name}.pyi"
    out_path.write_text(text, encoding="utf-8")
    print(f"wrote {out_path} ({text.count(chr(10))} lines)")
    return ns_name


def _write_init_pyi(namespaces: list[str], out_dir: Path) -> None:
    """Generate the __init__.pyi re-export hub for the ginext-stubs package."""
    lines = [
        "# Auto-generated by ginext-stubgen. Do not edit by hand.",
        "# Re-exports all namespace stubs so `from ginext import Gtk` resolves to",
        "# the generated Gtk.pyi module.",
        "from typing import Any",
        "",
    ]
    for ns in sorted(namespaces):
        lines.append(f"from . import {ns} as {ns}")
    lines += [
        "",
        "class PyGIWarning(Warning): ...",
        "class PyGIDeprecationWarning(DeprecationWarning): ...",
        "",
        "def __getattr__(name: str) -> Any: ...",
        "",
    ]
    out_path = out_dir / "__init__.pyi"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_path} ({len(lines)} lines)")


def cmd_generate(args: argparse.Namespace) -> int:
    out_dir: Path = args.out if args.out is not None else _DEFAULT_OUT[args.mode]
    out_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}

    for spec in args.specs:
        name, version = parse_spec(spec)
        gir = find_gir(name, version)
        if gir is None:
            print(f"error: {name}-{version}.gir not found", file=sys.stderr)
            return 1
        ns_name, text = generate(gir, mode=args.mode)
        if args.mode == "native":
            out_path = out_dir / f"{ns_name}.pyi"
            out_path.write_text(text, encoding="utf-8")
            print(f"wrote {out_path} ({text.count(chr(10))} lines)")
            continue
        suffix_name = f"{ns_name}{version.split('.', 1)[0]}"
        out_path = out_dir / f"{suffix_name}.pyi"
        out_path.write_text(text, encoding="utf-8")
        written[ns_name] = suffix_name
        print(f"wrote {out_path} ({text.count(chr(10))} lines)")

    if not args.no_symlink:
        for ns_name, suffix_name in written.items():
            link = out_dir / f"{ns_name}.pyi"
            try:
                if link.exists() or link.is_symlink():
                    link.unlink()
                link.symlink_to(f"{suffix_name}.pyi")
                print(f"linked {link} -> {suffix_name}.pyi")
            except OSError as e:
                print(f"warn: could not symlink {link}: {e}", file=sys.stderr)
    return 0


def cmd_generate_all(args: argparse.Namespace) -> int:
    out_dir: Path = args.out if args.out is not None else _DEFAULT_OUT["native"]
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    for name, version in _DEFAULT_NAMESPACES:
        ns = _generate_one(name, version, out_dir, "native")
        if ns:
            written.append(ns)
    _write_init_pyi(written, out_dir)
    return 0


def cmd_install(args: argparse.Namespace) -> int:
    rc = cmd_generate_all(args)
    if rc != 0:
        return rc
    out_dir: Path = args.out if args.out is not None else _DEFAULT_OUT["native"]
    # The package root is the parent of the stub directory (contains pyproject.toml).
    pkg_root = out_dir.parent
    print(f"reinstalling {pkg_root} ...")
    result = subprocess.run(
        ["uv", "pip", "install", "--reinstall", str(pkg_root)],
        check=False,
    )
    return result.returncode


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(prog="ginext_stubgen", description=__doc__)
    sub = p.add_subparsers(dest="cmd")

    # --- generate ---
    gen = sub.add_parser("generate", help="generate stubs for specific namespaces")
    gen.add_argument("specs", nargs="+", help="NAMESPACE:VERSION (e.g. Gtk:4.0)")
    gen.add_argument("--mode", choices=("native", "gi"), default="native")
    gen.add_argument("--out", type=Path, default=None)
    gen.add_argument("--no-symlink", action="store_true")

    # --- generate-all ---
    gall = sub.add_parser("generate-all", help="regenerate all default namespaces")
    gall.add_argument("--out", type=Path, default=None)

    # --- install ---
    inst = sub.add_parser(
        "install",
        help="regenerate all stubs and reinstall the ginext-stubs package",
    )
    inst.add_argument("--out", type=Path, default=None)

    args = p.parse_args(argv)

    if args.cmd == "generate":
        return cmd_generate(args)
    if args.cmd == "generate-all":
        return cmd_generate_all(args)
    if args.cmd == "install":
        return cmd_install(args)
    p.print_help()
    return 1


def main_cli() -> int:
    """Console-script entry point (``ginext-stubgen``)."""
    return main(sys.argv[1:])


if __name__ == "__main__":
    raise SystemExit(main_cli())
