"""CLI for ginext-stubgen.

Subcommands
-----------
generate NAMESPACE:VERSION ...
    Regenerate .pyi stubs for the given (Namespace, version) pairs and write
    them into the output directory (default: build/stubs/ginext
    for native mode).

generate-all
    Regenerate stubs for every namespace ginext ships by default, plus the
    __init__.pyi hub, and write them into the output directory.

install
    Run generate-all then reinstall the ginext-stubs package into the active
    venv so the new stubs are immediately available to mypy.

Examples:
    uv run python -m ginext_stubgen generate GLib:2.0
    uv run python -m ginext_stubgen generate-all
    uv run python -m ginext_stubgen install
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

from . import build_namespace, find_gir, generate
from . import Mode


def parse_spec(spec: str) -> tuple[str, str]:
    if ":" not in spec:
        raise SystemExit(f"bad spec {spec!r}: want NAMESPACE:VERSION")
    name, version = spec.split(":", 1)
    return name, version


# Default output directory per mode, relative to the repo root.
_DEFAULT_OUT = {
    "native": Path("build/stubs/ginext"),
    "gi": Path("stubs/gi/repository"),
}

# Namespaces (and their canonical version) that ginext-stubs ships. Kept here
# as the single declaration: generate-all iterates this list and _init_pyi
# generates the __init__.pyi hub from it.
_DEFAULT_NAMESPACES: list[tuple[str, str]] = [
    ("GLib", "2.0"),
    ("GObject", "2.0"),
    ("Gio", "2.0"),
    ("GioUnix", "2.0"),
    ("Adw", "1"),
    ("Gst", "1.0"),
    ("GstApp", "1.0"),
    ("GstAudio", "1.0"),
    ("GstBase", "1.0"),
    ("GstVideo", "1.0"),
    ("Gtk", "4.0"),
    ("Gdk", "4.0"),
    ("Gsk", "4.0"),
    ("Pango", "1.0"),
    ("PangoCairo", "1.0"),
    ("Graphene", "1.0"),
    ("GdkPixbuf", "2.0"),
    ("GModule", "2.0"),
    ("HarfBuzz", "0.0"),
    ("freetype2", "2.0"),
    # GTK-ecosystem namespaces used by the example apps (terminal, pyedit,
    # web_browser). Generated only when their .gir is installed; skipped
    # otherwise (so a minimal checkout still works).
    ("Vte", "3.91"),
    ("GtkSource", "5"),
    ("WebKit", "6.0"),
    # Test-only namespaces built from packages/typelib. Generated only when the
    # build directory exists; silently skipped otherwise.
    ("GIMarshallingTests", "1.0"),
    ("GoiBench", "1.0"),
    ("Regress", "1.0"),
    ("RegressUnix", "1.0"),
]


def _generate_one(
    name: str,
    version: str,
    out_dir: Path,
    mode: Mode,
    cache_dir: Path | None = None,
) -> str | None:
    """Generate a single namespace stub. Returns the namespace name or None on failure."""
    gir = find_gir(name, version)
    if gir is None:
        print(f"warn: {name}-{version}.gir not found — skipping", file=sys.stderr)
        return None
    ns_name, text = generate(gir, mode=mode, cache_dir=cache_dir)
    out_path = out_dir / f"{ns_name}.pyi"
    out_path.write_text(text, encoding="utf-8")
    print(f"wrote {out_path} ({text.count(chr(10))} lines)")
    return ns_name


def _write_init_pyi(namespaces: list[str], out_dir: Path) -> None:
    """Generate the __init__.pyi re-export hub for the ginext stub package."""
    lines = [
        "# Auto-generated by ginext-stubgen. Do not edit by hand.",
        "# Re-exports all namespace stubs so `from ginext import Gtk` resolves to",
        "# the generated Gtk.pyi module.",
        "from typing import Any",
        "",
    ]
    for ns in sorted(namespaces):
        lines.append(f"from . import {ns} as {ns}")
    lines += [
        "",
        "class PyGIWarning(Warning): ...",
        "class PyGIDeprecationWarning(DeprecationWarning): ...",
        "",
        "def __getattr__(name: str) -> Any: ...",
        "",
    ]
    out_path = out_dir / "__init__.pyi"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_path} ({len(lines)} lines)")


def _write_py_typed(out_dir: Path) -> None:
    out_path = out_dir / "py.typed"
    out_path.write_text("", encoding="utf-8")
    print(f"wrote {out_path} (0 lines)")


# Handwritten stubs for ginext-internal namespaces that do NOT map 1:1 to their
# upstream GIR. These are written after the generated stubs so they override any
# GIR-derived output for the same namespace.
_HANDWRITTEN_STUBS: dict[str, str] = {
    # ginext.GIRepository is NOT the upstream GIRepository-3.0 typelib surface —
    # it's ginext's own C introspection wrapper types registered via the
    # GIRepository overlay. Re-export them from ginext.private._gobject so that
    # ``from ginext.GIRepository import EnumInfo`` type-checks against the real
    # runtime types.
    "GIRepository": """\
# Handwritten stub — ginext.GIRepository re-exports ginext's own C introspection
# wrappers, not the upstream GIRepository-3.0 typelib surface.
# Do not replace with a generated stub.
from ginext.overlay.registrar import OverlayRegistrar
from ginext.private._gobject import (
    ArgInfo as ArgInfo,
    BaseInfo as BaseInfo,
    CallableInfo as CallableInfo,
    CallbackInfo as CallbackInfo,
    ConstantInfo as ConstantInfo,
    EnumInfo as EnumInfo,
    FieldInfo as FieldInfo,
    FlagsInfo as FlagsInfo,
    FunctionInfo as FunctionInfo,
    InterfaceInfo as InterfaceInfo,
    ObjectInfo as ObjectInfo,
    PropertyInfo as PropertyInfo,
    RegisteredTypeInfo as RegisteredTypeInfo,
    SignalInfo as SignalInfo,
    StructInfo as StructInfo,
    TypeInfo as TypeInfo,
    UnionInfo as UnionInfo,
    UnresolvedInfo as UnresolvedInfo,
    VFuncInfo as VFuncInfo,
    ValueInfo as ValueInfo,
)

overlay: OverlayRegistrar
""",
}


def _write_handwritten_stubs(out_dir: Path) -> list[str]:
    """Write handwritten stubs for ginext-internal namespaces. Returns ns names written."""
    written = []
    for ns_name, content in _HANDWRITTEN_STUBS.items():
        out_path = out_dir / f"{ns_name}.pyi"
        out_path.write_text(content, encoding="utf-8")
        print(f"wrote {out_path} (handwritten, {content.count(chr(10))} lines)")
        written.append(ns_name)
    return written


def cmd_generate(args: argparse.Namespace) -> int:
    out_dir: Path = args.out if args.out is not None else _DEFAULT_OUT[args.mode]
    out_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}

    for spec in args.specs:
        name, version = parse_spec(spec)
        gir = find_gir(name, version)
        if gir is None:
            print(f"error: {name}-{version}.gir not found", file=sys.stderr)
            return 1
        ns_name, text = generate(gir, mode=args.mode)
        if args.mode == "native":
            out_path = out_dir / f"{ns_name}.pyi"
            out_path.write_text(text, encoding="utf-8")
            print(f"wrote {out_path} ({text.count(chr(10))} lines)")
            continue
        suffix_name = f"{ns_name}{version.split('.', 1)[0]}"
        out_path = out_dir / f"{suffix_name}.pyi"
        out_path.write_text(text, encoding="utf-8")
        written[ns_name] = suffix_name
        print(f"wrote {out_path} ({text.count(chr(10))} lines)")

    if not args.no_symlink:
        for ns_name, suffix_name in written.items():
            link = out_dir / f"{ns_name}.pyi"
            try:
                if link.exists() or link.is_symlink():
                    link.unlink()
                link.symlink_to(f"{suffix_name}.pyi")
                print(f"linked {link} -> {suffix_name}.pyi")
            except OSError as e:
                print(f"warn: could not symlink {link}: {e}", file=sys.stderr)
    return 0


def cmd_generate_all(args: argparse.Namespace) -> int:
    out_dir: Path = args.out if args.out is not None else _DEFAULT_OUT["native"]
    out_dir.mkdir(parents=True, exist_ok=True)
    for path in out_dir.glob("*.pyi"):
        path.unlink()
    py_typed = out_dir / "py.typed"
    if py_typed.exists():
        py_typed.unlink()
    no_cache: bool = getattr(args, "no_cache", False) or os.environ.get("GINEXT_STUBGEN_NO_CACHE") == "1"
    cache_dir: Path | None = None if no_cache else (out_dir.parent / ".cache")
    written: list[str] = []
    for name, version in _DEFAULT_NAMESPACES:
        ns = _generate_one(name, version, out_dir, "native", cache_dir=cache_dir)
        if ns:
            written.append(ns)
    written.extend(_write_handwritten_stubs(out_dir))
    _write_init_pyi(written, out_dir)
    _write_py_typed(out_dir)
    return 0


def cmd_generate_docs(args: argparse.Namespace) -> int:
    from .docgen import DocEmitter

    out_dir: Path = args.out
    if args.all:
        specs = list(_DEFAULT_NAMESPACES)
    else:
        specs = [parse_spec(s) for s in args.specs]
    if not specs:
        print("error: pass NAMESPACE:VERSION specs or --all", file=sys.stderr)
        return 1

    entries = []
    for name, version in specs:
        gir = find_gir(name, version)
        if gir is None:
            print(f"warn: {name}-{version}.gir not found — skipping", file=sys.stderr)
            continue
        entries.append(build_namespace(gir, doc_format="raw"))

    if not entries:
        print("error: no namespaces resolved", file=sys.stderr)
        return 1

    written = DocEmitter(entries, ext=args.ext).write(out_dir)
    namespaces = ", ".join(sorted(ns.name for ns, _ in entries))
    print(f"wrote {len(written)} files for {namespaces} into {out_dir}")
    return 0


def cmd_install(args: argparse.Namespace) -> int:
    rc = cmd_generate_all(args)
    if rc != 0:
        return rc
    out_dir: Path = args.out if args.out is not None else _DEFAULT_OUT["native"]
    # The package root is the parent of the stub directory (contains pyproject.toml).
    pkg_root = out_dir.parent
    print(f"reinstalling {pkg_root} ...")
    result = subprocess.run(
        ["uv", "pip", "install", "--reinstall", str(pkg_root)],
        check=False,
    )
    return result.returncode


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(prog="ginext_stubgen", description=__doc__)
    sub = p.add_subparsers(dest="cmd")

    # --- generate ---
    gen = sub.add_parser("generate", help="generate stubs for specific namespaces")
    gen.add_argument("specs", nargs="+", help="NAMESPACE:VERSION (e.g. Gtk:4.0)")
    gen.add_argument("--mode", choices=("native", "gi"), default="native")
    gen.add_argument("--out", type=Path, default=None)
    gen.add_argument("--no-symlink", action="store_true")

    # --- generate-all ---
    gall = sub.add_parser("generate-all", help="regenerate all default namespaces")
    gall.add_argument("--out", type=Path, default=None)
    gall.add_argument(
        "--no-cache",
        action="store_true",
        dest="no_cache",
        help="disable the pickle cache (also: GINEXT_STUBGEN_NO_CACHE=1)",
    )

    # --- generate-docs ---
    gdocs = sub.add_parser(
        "generate-docs",
        help="generate Docusaurus MDX API reference pages",
    )
    gdocs.add_argument(
        "specs", nargs="*", help="NAMESPACE:VERSION (e.g. Gtk:4.0); omit with --all"
    )
    gdocs.add_argument(
        "--all", action="store_true", help="generate all default namespaces"
    )
    gdocs.add_argument(
        "--out",
        type=Path,
        required=True,
        help="output directory (the Docusaurus content/api dir)",
    )
    gdocs.add_argument(
        "--ext",
        choices=("mdx", "md"),
        default="mdx",
        help="page file extension: mdx for Docusaurus (default), md for mkdocs",
    )

    # --- install ---
    inst = sub.add_parser(
        "install",
        help="regenerate all stubs and reinstall the ginext-stubs package",
    )
    inst.add_argument("--out", type=Path, default=None)
    inst.add_argument(
        "--no-cache",
        action="store_true",
        dest="no_cache",
        help="disable the pickle cache (also: GINEXT_STUBGEN_NO_CACHE=1)",
    )

    args = p.parse_args(argv)

    if args.cmd == "generate":
        return cmd_generate(args)
    if args.cmd == "generate-all":
        return cmd_generate_all(args)
    if args.cmd == "generate-docs":
        return cmd_generate_docs(args)
    if args.cmd == "install":
        return cmd_install(args)
    p.print_help()
    return 1


def main_cli() -> int:
    """Console-script entry point (``ginext-stubgen``)."""
    return main(sys.argv[1:])


if __name__ == "__main__":
    raise SystemExit(main_cli())
