# Configure and build ginext on Windows (clang-cl + MSVC ABI), x64 or arm64.
#
#   powershell -File tools\win\build.ps1            # configure (if needed) + compile
#   powershell -File tools\win\build.ps1 -Reconfigure
#   $env:GINEXT_TRIPLET='x64-windows'; powershell -File tools\win\build.ps1
# (pwsh / PowerShell 7 works too if installed.)
#
# Prerequisites (one-time, see tools\win\setup.ps1 / tools\win\BOOTSTRAP.md):
#   * Visual Studio 2022 Build Tools with the target arch toolchain + Windows SDK.
#   * LLVM (clang-cl + lld-link) at C:\LLVM (or $env:GINEXT_LLVM).
#   * vcpkg at $env:VCPKG_ROOT (default C:\dev\vcpkg) with the manifest deps
#     installed for the target triplet: `vcpkg install --triplet <triplet>`.
#   * A build venv (run tools\win\setup.ps1).
# clang-cl is REQUIRED (not MSVC cl.exe): ginext is GNU-C (__attribute__((cleanup)),
# g_autoptr). clang-cl gives GNU extensions with the MSVC ABI.
[CmdletBinding()]
param(
    [switch]$Reconfigure,
    [string]$BuildDir,
    [switch]$WithGiTests = $true
)

$ErrorActionPreference = "Stop"
$repo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
Set-Location $repo

# 1. Toolchain environment (vcvars + clang-cl + vcpkg pkgconfig + typelibs).
#    Sets/normalizes $env:GINEXT_TRIPLET and resolves VCPKG_ROOT.
. "$repo\tools\win\build-env.ps1"
$triplet = $env:GINEXT_TRIPLET
# build-env.ps1 resolved the install tree (manifest vcpkg_installed vs classic)
# and exported it; reuse that exact path so the native file's pkg-config is right.
$installed = $env:GINEXT_VCPKG_INSTALLED
if (-not $installed) { throw "GINEXT_VCPKG_INSTALLED not set by build-env.ps1" }
if (-not $BuildDir) { $BuildDir = "build\win-" + ($triplet -replace '-windows$','') }

# 2. Build venv tooling (meson). Prefer the per-arch venv, fall back to .venv.
$venv = if (Test-Path "$repo\.venv-win-$($triplet -replace '-windows$','')\Scripts\python.exe") {
    "$repo\.venv-win-$($triplet -replace '-windows$','')"
} else { "$repo\.venv-win-arm64" }
$venvPy = "$venv\Scripts\python.exe"
$meson = "$venv\Scripts\meson.exe"
if (-not (Test-Path $venvPy)) { throw "build venv missing: $venvPy (run tools\win\setup.ps1)" }

# 3. Generate the meson native file from the resolved env (no hardcoded paths).
$pkgconf = Join-Path $installed 'tools\pkgconf\pkgconf.exe'
$pcLibdir = (Join-Path $installed 'lib\pkgconfig') -replace '\\','\\'
$nativeFile = Join-Path "$repo\$BuildDir" 'native.ini'
New-Item -ItemType Directory -Force -Path "$repo\$BuildDir" | Out-Null
$nativeContent = @"
; Generated by tools\win\build.ps1 for triplet $triplet -- do not edit.
[binaries]
c = 'clang-cl'
cpp = 'clang-cl'
c_ld = 'lld-link'
pkg-config = '$($pkgconf -replace '\\','\\')'
"@

# When building the gi test typelibs, gnome.generate_gir runs g-ir-scanner.
# vcpkg's _giscanner is cp312, so it must run under a 3.12 interpreter with
# setuptools (the build venv is 3.14 -> ABI mismatch). Create such a venv from
# vcpkg's python3 and point meson's g-ir-scanner/g-ir-compiler at it.
if ($WithGiTests) {
    $py312 = Join-Path $installed 'tools\python3\python.exe'
    if (-not (Test-Path $py312)) { throw "vcpkg python3 not found: $py312" }
    $scanVenv = "$repo\.venv-gir-scanner"
    if (-not (Test-Path "$scanVenv\Scripts\python.exe")) {
        & $py312 -I -m venv --copies $scanVenv
        if ($LASTEXITCODE -ne 0) { throw "scanner venv creation failed" }
        uv pip install --python "$scanVenv\Scripts\python.exe" setuptools
        if ($LASTEXITCODE -ne 0) { throw "scanner venv setuptools install failed" }
    }
    $scanPy = (Join-Path $scanVenv 'Scripts\python.exe') -replace '\\','\\'
    $girScanner = (Join-Path $installed 'tools\gobject-introspection\g-ir-scanner') -replace '\\','\\'
    $girCompiler = (Join-Path $installed 'tools\gobject-introspection\g-ir-compiler.exe') -replace '\\','\\'
    $nativeContent += @"

g-ir-scanner = ['$scanPy', '$girScanner']
g-ir-compiler = '$girCompiler'
"@
}

$nativeContent += @"

[properties]
pkg_config_libdir = '$pcLibdir'
"@
$nativeContent | Set-Content -Encoding ascii $nativeFile

# The scanner reads these to locate dep libs and gdump.c during introspection.
if ($WithGiTests) {
    $env:VCPKG_GI_DATADIR = "$installed\share"
    $env:VCPKG_GI_LIBDIR = "$installed\lib"
    $env:VCPKG_GI_LIBDIR_VAR = "LIB"
}

# 4. Configure (first time) or reconfigure on request.
# -Db_pch=false: on some environments meson auto-uses Python.h as a precompiled
# header and emits the GCC-style `-include Python.h`, which clang-cl rejects.
# ginext declares no PCH, so disabling it is safe and forces the include via the
# normal `#include <Python.h>` in the sources.
$giTests = if ($WithGiTests) { "true" } else { "false" }
if (-not (Test-Path "$repo\$BuildDir\build.ninja")) {
    & $meson setup $BuildDir --native-file $nativeFile `
        "-Dbuild_gi_tests=$giTests" -Dwerror=false -Db_pch=false
    if ($LASTEXITCODE -ne 0) { throw "meson setup failed ($LASTEXITCODE)" }
} elseif ($Reconfigure) {
    & $meson setup --reconfigure $BuildDir --native-file $nativeFile `
        "-Dbuild_gi_tests=$giTests" -Dwerror=false -Db_pch=false
    if ($LASTEXITCODE -ne 0) { throw "meson reconfigure failed ($LASTEXITCODE)" }
}

# 5. Compile. The gi test-typelib generation (build_gi_tests) has a parallel
# race on Windows where a g-ir-scanner target can run before its test DLL is
# ready; the build is incremental, so a retry reliably continues to completion.
$attempts = if ($WithGiTests) { 3 } else { 1 }
for ($i = 1; $i -le $attempts; $i++) {
    & $meson compile -C $BuildDir
    if ($LASTEXITCODE -eq 0) { break }
    if ($i -eq $attempts) { throw "meson compile failed ($LASTEXITCODE) after $attempts attempt(s)" }
    Write-Host "meson compile attempt $i failed; retrying (incremental)..."
}

Write-Host "ginext built for $triplet in $repo\$BuildDir\src"
