# Auto-generated by ginext-stubgen. Do not edit by hand.
# Re-exports all namespace stubs so `from ginext import Gtk` resolves to
# the generated Gtk.pyi module.
from typing import Any

from . import Adw as Adw
from . import GIMarshallingTests as GIMarshallingTests
from . import GLib as GLib
from . import GModule as GModule
from . import GObject as GObject
from . import Gdk as Gdk
from . import GdkPixbuf as GdkPixbuf
from . import Gio as Gio
from . import GioUnix as GioUnix
from . import GoiBench as GoiBench
from . import Graphene as Graphene
from . import Gsk as Gsk
from . import Gst as Gst
from . import GstApp as GstApp
from . import GstAudio as GstAudio
from . import GstBase as GstBase
from . import GstVideo as GstVideo
from . import Gtk as Gtk
from . import GtkSource as GtkSource
from . import HarfBuzz as HarfBuzz
from . import Pango as Pango
from . import PangoCairo as PangoCairo
from . import Regress as Regress
from . import RegressUnix as RegressUnix
from . import Vte as Vte
from . import WebKit as WebKit
from . import freetype2 as freetype2

class PyGIWarning(Warning): ...
class PyGIDeprecationWarning(DeprecationWarning): ...

def __getattr__(name: str) -> Any: ...
