# Auto-generated by ginext-stubgen from freetype2-2.0.gir.
# Do not edit by hand.
# mypy: disable-error-code="override,type-arg,misc,valid-type"
from __future__ import annotations

from collections.abc import Iterator
from typing import Any, Awaitable, Callable, ClassVar, Final, Generic, Literal, NamedTuple, Self, TypeVar, override, overload
from ginext.overlay.registrar import OverlayRegistrar as _OverlayRegistrar
from ginext.private import GIMeta as _GIMeta

overlay: _OverlayRegistrar
__version__: tuple[int, ...]
def __getattr__(name: str) -> Any: ...

Int32 = Any
class Bitmap:
    gimeta: ClassVar[_GIMeta]

class Face:
    gimeta: ClassVar[_GIMeta]

class Library:
    gimeta: ClassVar[_GIMeta]
