# Auto-generated by ginext-stubgen from GioUnix-2.0.gir.
# Do not edit by hand.
# mypy: disable-error-code="override,type-arg,misc,valid-type"
from __future__ import annotations

import os
from collections.abc import Iterator
from typing_extensions import deprecated
from contextlib import AbstractContextManager
from typing import Any, Awaitable, Callable, ClassVar, Concatenate, Generic, Final, Literal, NamedTuple, ParamSpec as _ParamSpec, Self, TypeVar, override, overload
from ginext import GLib
from ginext import GObject
from ginext import Gio
from ginext.overlay.registrar import OverlayRegistrar as _OverlayRegistrar
from ginext.private import GIMeta as _GIMeta

overlay: _OverlayRegistrar
__version__: tuple[int, ...]
def __getattr__(name: str) -> Any: ...

_SigO = TypeVar('_SigO')
_SigP = _ParamSpec('_SigP')
_SigR = TypeVar('_SigR')

class SignalConnection:
    handler_id: int
    signal_name: str
    source: Any
    callback: Callable[..., Any]
    after: bool
    once: bool
    owner: Any
    is_connected: bool
    def disconnect(self) -> None: ...
    def blocked(self) -> AbstractContextManager[SignalConnection]: ...

class Signal(Generic[_SigO, _SigP, _SigR]):
    def __call__(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...
    def connect(self, handler: Callable[Concatenate[_SigO, _SigP], _SigR], *, after: bool = ..., once: bool = ..., owner: Any = ...) -> SignalConnection: ...
    def connect_after(self, handler: Callable[Concatenate[_SigO, _SigP], _SigR]) -> SignalConnection: ...
    def emit(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...
    def disconnect(self, connection: SignalConnection) -> None: ...
class SignalMethod(Signal[_SigO, _SigP, _SigR]):
    def __call__(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...

class DetailedSignal(Signal[_SigO, _SigP, _SigR]):
    def __call__(self, detail: str | GObject.Property) -> 'Signal[_SigO, _SigP, _SigR]': ...

DesktopAppLaunchCallback = Callable[[DesktopAppInfo, GLib.Pid], None]
class DesktopAppInfo(GObject.Object, Gio.AppInfo):
    """
    :class:`GioUnix.DesktopAppInfo` is an implementation of :class:`Gio.AppInfo` based on
    desktop files.

    Note that ``<gio/gdesktopappinfo.h>`` belongs to the UNIX-specific
    GIO interfaces, thus you have to use the ``gio-unix-2.0.pc`` pkg-config
    file or the ``GioUnix-2.0`` GIR namespace when using it.
    """
    gimeta: ClassVar[_GIMeta]
    filename: str
    def __init__(self, *, filename: str = ..., **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...
    @classmethod
    def new_from_filename(cls, filename: str | bytes | os.PathLike[str] | os.PathLike[bytes]) -> Self:
        """
        Creates a new :class:`GioUnix.DesktopAppInfo`.
        """
    @classmethod
    def new_from_keyfile(cls, key_file: GLib.KeyFile) -> Self:
        """
        Creates a new :class:`GioUnix.DesktopAppInfo`.
        """
    def get_action_name(self, action_name: str) -> str:
        """
        Gets the user-visible display name of the
        `‘additional application actions’ <https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s11.html>`_
        specified by ``action_name``.

        This corresponds to the ``Name`` key within the keyfile group for the
        action.
        """
    def get_boolean(self, key: str) -> bool:
        """
        Looks up a boolean value in the keyfile backing ``info``.

        The ``key`` is looked up in the ``Desktop Entry`` group.
        """
    def get_categories(self) -> str | None:
        """
        Gets the categories from the desktop file.
        """
    def get_filename(self) -> str | None:
        """
        When ``info`` was created from a known filename, return it.

        In some situations such as a :class:`GioUnix.DesktopAppInfo` returned
        from :meth:`GioUnix.DesktopAppInfo.new_from_keyfile`, this function
        will return ``None``.
        """
    def get_generic_name(self) -> str | None:
        """
        Gets the generic name from the desktop file.
        """
    def get_is_hidden(self) -> bool:
        """
        A desktop file is hidden if the
        `Hidden key <https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-hidden>`_
        in it is set to ``True``.
        """
    def get_keywords(self) -> list[str] | None:
        """
        Gets the keywords from the desktop file.
        """
    def get_locale_string(self, key: str) -> str | None:
        """
        Looks up a localized string value in the keyfile backing ``info``
        translated to the current locale.

        The ``key`` is looked up in the ``Desktop Entry`` group.
        """
    def get_nodisplay(self) -> bool:
        """
        Gets the value of the
        `NoDisplay key <https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-nodisplay>`_
         which helps determine if the application info should be shown in menus. See
        ``G_KEY_FILE_DESKTOP_KEY_NO_DISPLAY`` and :meth:`Gio.AppInfo.should_show`.
        """
    def get_show_in(self, desktop_env: str | None = ...) -> bool:
        """
        Checks if the application info should be shown in menus that list available
        applications for a specific name of the desktop, based on the
        `OnlyShowIn <https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-onlyshowin>`_
        and `NotShowIn <https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-notshowin>`_
        keys.

        ``desktop_env`` should typically be given as ``None``, in which case the
        ``XDG_CURRENT_DESKTOP`` environment variable is consulted.  If you want
        to override the default mechanism then you may specify ``desktop_env``,
        but this is not recommended.

        Note that :meth:`Gio.AppInfo.should_show` for ``info`` will include this check
        (with ``None`` for ``desktop_env``) as well as additional checks.
        """
    def get_startup_wm_class(self) -> str | None:
        """
        Retrieves the ``StartupWMClass`` field from ``info``. This represents the
        ``WM_CLASS`` property of the main window of the application, if launched
        through ``info``.
        """
    def get_string(self, key: str) -> str | None:
        """
        Looks up a string value in the keyfile backing ``info``.

        The ``key`` is looked up in the ``Desktop Entry`` group.
        """
    def get_string_list(self, key: str) -> list[str] | None:
        """
        Looks up a string list value in the keyfile backing ``info``.

        The ``key`` is looked up in the ``Desktop Entry`` group.
        """
    def has_key(self, key: str) -> bool:
        """
        Returns whether ``key`` exists in the ``Desktop Entry`` group
        of the keyfile backing ``info``.
        """
    def launch_action(self, action_name: str, launch_context: Gio.AppLaunchContext | None = ...) -> None:
        """
        Activates the named application action.

        You may only call this function on action names that were
        returned from :meth:`GioUnix.DesktopAppInfo.list_actions`.

        Note that if the main entry of the desktop file indicates that the
        application supports startup notification, and ``launch_context`` is
        non-``None``, then startup notification will be used when activating the
        action (and as such, invocation of the action on the receiving side
        must signal the end of startup notification when it is completed).
        This is the expected behaviour of applications declaring additional
        actions, as per the
        `desktop file specification <https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s11.html>`_.

        As with :meth:`Gio.AppInfo.launch` there is no way to detect failures that
        occur while using this function.
        """
    def launch_uris_as_manager(self, uris: list[str], launch_context: Gio.AppLaunchContext | None, spawn_flags: GLib.SpawnFlags | int, user_setup: GLib.SpawnChildSetupFunc | None = ..., pid_callback: DesktopAppLaunchCallback | None = ...) -> bool:
        """
        This function performs the equivalent of :meth:`Gio.AppInfo.launch_uris`,
        but is intended primarily for operating system components that
        launch applications.  Ordinary applications should use
        :meth:`Gio.AppInfo.launch_uris`.

        If the application is launched via GSpawn, then ``spawn_flags``, ``user_setup``
        and ``user_setup_data`` are used for the call to :func:`GLib.spawn_async`.
        Additionally, ``pid_callback`` (with ``pid_callback_data``) will be called to
        inform about the PID of the created process. See
        :func:`GLib.spawn_async_with_pipes` for information on certain parameter
        conditions that can enable an optimized [``posix_spawn()``](man:posix_spawn(3))
        code path to be used.

        If application launching occurs via some other mechanism (for example, D-Bus
        activation) then ``spawn_flags``, ``user_setup``, ``user_setup_data``,
        ``pid_callback`` and ``pid_callback_data`` are ignored.
        """
    def launch_uris_as_manager_with_fds(self, uris: list[str], launch_context: Gio.AppLaunchContext | None, spawn_flags: GLib.SpawnFlags | int, user_setup: GLib.SpawnChildSetupFunc | None, pid_callback: DesktopAppLaunchCallback | None, stdin_fd: int, stdout_fd: int, stderr_fd: int) -> bool:
        """
        Equivalent to :meth:`GioUnix.DesktopAppInfo.launch_uris_as_manager` but
        allows you to pass in file descriptors for the stdin, stdout and stderr
        streams of the launched process.

        If application launching occurs via some non-spawn mechanism (e.g. D-Bus
        activation) then ``stdin_fd``, ``stdout_fd`` and ``stderr_fd`` are ignored.
        """
    def list_actions(self) -> list[str]:
        """
        Returns the list of
        `‘additional application actions’ <https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s11.html>`_
        supported on the desktop file, as per the desktop file specification.

        As per the specification, this is the list of actions that are
        explicitly listed in the ``Actions`` key of the ``Desktop Entry`` group.
        """
    @staticmethod
    def get_implementations(interface: str) -> list[DesktopAppInfo]:
        """
        Gets all applications that implement ``interface``.

        An application implements an interface if that interface is listed in
        the ``Implements`` line of the desktop file of the application.
        """
    @staticmethod
    def search(search_string: str) -> list[list[str]]:
        """
        Searches desktop files for ones that match ``search_string``.

        The return value is an array of strvs.  Each strv contains a list of
        applications that matched ``search_string`` with an equal score.  The
        outer list is sorted by score so that the first strv contains the
        best-matching applications, and so on.
        The algorithm for determining matches is undefined and may change at
        any time.

        None of the search results are subjected to the normal validation
        checks performed by :meth:`GioUnix.DesktopAppInfo.new` (for example,
        checking that the executable referenced by a result exists), and so it is
        possible for :meth:`GioUnix.DesktopAppInfo.new` to return ``None`` when passed
        an app ID returned by this function. It is expected that calling code will
        do this when subsequently creating a :class:`GioUnix.DesktopAppInfo` for
        each result.
        """
    @deprecated("Deprecated since 2.42.")
    @staticmethod
    def set_desktop_env(desktop_env: str) -> None:
        """
        Sets the name of the desktop that the application is running in.

        This is used by :meth:`Gio.AppInfo.should_show` and
        :meth:`GioUnix.DesktopAppInfo.get_show_in` to evaluate the
        `OnlyShowIn <https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-onlyshowin>`_
        and `NotShowIn <https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-notshowin>`_
        keys.

        Should be called only once; subsequent calls are ignored.
        """

class DesktopAppInfoClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: GObject.ObjectClass

@deprecated("Deprecated since 2.28.")
class DesktopAppInfoLookup:
    """
    :class:`GioUnix.DesktopAppInfoLookup` is an opaque data structure and can only be accessed
    using the following functions.
    """
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    @deprecated("Deprecated since 2.28.")
    def get_default_for_uri_scheme(self, uri_scheme: str) -> Gio.AppInfo | None:
        """
        Gets the default application for launching applications
        using this URI scheme for a particular :class:`GioUnix.DesktopAppInfoLookup`
        implementation.

        The :class:`GioUnix.DesktopAppInfoLookup` interface and this function is used
        to implement :func:`Gio.AppInfo.get_default_for_uri_scheme` backends
        in a GIO module. There is no reason for applications to use it
        directly. Applications should use
        :func:`Gio.AppInfo.get_default_for_uri_scheme`.
        """
    @deprecated("Deprecated since 2.28.")
    def do_get_default_for_uri_scheme(self, uri_scheme: str) -> Gio.AppInfo | None:
        """
        Gets the default application for launching applications
        using this URI scheme for a particular :class:`GioUnix.DesktopAppInfoLookup`
        implementation.

        The :class:`GioUnix.DesktopAppInfoLookup` interface and this function is used
        to implement :func:`Gio.AppInfo.get_default_for_uri_scheme` backends
        in a GIO module. There is no reason for applications to use it
        directly. Applications should use
        :func:`Gio.AppInfo.get_default_for_uri_scheme`.
        """

class DesktopAppInfoLookupIface:
    """
    Interface that is used by backends to associate default
    handlers with URI schemes.
    """
    gimeta: ClassVar[_GIMeta]
    g_iface: GObject.TypeInterface
    get_default_for_uri_scheme: Any

class FDMessage(Gio.SocketControlMessage):
    """
    This :class:`Gio.SocketControlMessage` contains a :class:`Gio.UnixFDList`.
    It may be sent using :meth:`Gio.Socket.send_message` and received using
    :meth:`Gio.Socket.receive_message` over UNIX sockets (ie: sockets in the
    ``G_SOCKET_FAMILY_UNIX`` family). The file descriptors are copied
    between processes by the kernel.

    For an easier way to send and receive file descriptors over
    stream-oriented UNIX sockets, see :meth:`Gio.UnixConnection.send_fd` and
    :meth:`Gio.UnixConnection.receive_fd`.

    Note that ``<gio/gunixfdmessage.h>`` belongs to the UNIX-specific GIO
    interfaces, thus you have to use the ``gio-unix-2.0.pc`` pkg-config
    file or the ``GioUnix-2.0`` GIR namespace when using it.
    """
    gimeta: ClassVar[_GIMeta]
    fd_list: Gio.UnixFDList
    def __init__(self, *, fd_list: Gio.UnixFDList = ..., **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...
    @classmethod
    def new_with_fd_list(cls, fd_list: Gio.UnixFDList) -> Self:
        """
        Creates a new :class:`GioUnix.FDMessage` containing ``list``.
        """
    def append_fd(self, fd: int) -> bool:
        """
        Adds a file descriptor to ``message``.

        The file descriptor is duplicated using dup(). You keep your copy
        of the descriptor and the copy contained in ``message`` will be closed
        when ``message`` is finalized.

        A possible cause of failure is exceeding the per-process or
        system-wide file descriptor limit.
        """
    def get_fd_list(self) -> Gio.UnixFDList:
        """
        Gets the :class:`GUnixFDList` contained in ``message``.  This function does not
        return a reference to the caller, but the returned list is valid for
        the lifetime of ``message``.
        """
    def steal_fds(self) -> list[int]:
        """
        Returns the array of file descriptors that is contained in this
        object.

        After this call, the descriptors are no longer contained in
        ``message``. Further calls will return an empty list (unless more
        descriptors have been added).

        The return result of this function must be freed with g_free().
        The caller is also responsible for closing all of the file
        descriptors.

        If ``length`` is non-``None`` then it is set to the number of file
        descriptors in the returned array. The returned array is also
        terminated with -1.

        This function never returns ``None``. In case there are no file
        descriptors contained in ``message``, an empty array is returned.
        """

class FDMessageClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: Gio.SocketControlMessageClass

class FDMessagePrivate:
    gimeta: ClassVar[_GIMeta]

class FileDescriptorBased:
    """
    :class:`GioUnix.FileDescriptorBased` is an interface for file descriptor based IO.

    It is implemented by streams (implementations of :class:`Gio.InputStream` or
    :class:`Gio.OutputStream`) that are based on file descriptors.

    Note that ``<gio/gfiledescriptorbased.h>`` belongs to the UNIX-specific
    GIO interfaces, thus you have to use the ``gio-unix-2.0.pc`` pkg-config
    file or the ``GioUnix-2.0`` GIR namespace when using it.
    """
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    def get_fd(self) -> int:
        """
        Gets the underlying file descriptor.
        """
    def do_get_fd(self) -> int:
        """
        Gets the underlying file descriptor.
        """

class FileDescriptorBasedIface:
    """
    An interface for file descriptor based io objects.
    """
    gimeta: ClassVar[_GIMeta]
    g_iface: GObject.TypeInterface
    get_fd: Any

class InputStream(Gio.InputStream, Gio.PollableInputStream, FileDescriptorBased):
    """
    :class:`GioUnix.InputStream` implements :class:`Gio.InputStream` for reading from a UNIX
    file descriptor, including asynchronous operations. (If the file
    descriptor refers to a socket or pipe, this will use ``poll()`` to do
    asynchronous I/O. If it refers to a regular file, it will fall back
    to doing asynchronous I/O in another thread.)

    Note that ``<gio/gunixinputstream.h>`` belongs to the UNIX-specific GIO
    interfaces, thus you have to use the ``gio-unix-2.0.pc`` pkg-config
    file or the ``GioUnix-2.0`` GIR namespace when using it.
    """
    gimeta: ClassVar[_GIMeta]
    close_fd: bool
    fd: int
    def __init__(self, *, close_fd: bool = ..., fd: int = ..., **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...
    def get_close_fd(self) -> bool:
        """
        Returns whether the file descriptor of ``stream`` will be
        closed when the stream is closed.
        """
    def get_fd(self) -> int:
        """
        Return the UNIX file descriptor that the stream reads from.
        """
    def set_close_fd(self, close_fd: bool) -> None:
        """
        Sets whether the file descriptor of ``stream`` shall be closed
        when the stream is closed.
        """

class InputStreamClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: Gio.InputStreamClass

class InputStreamPrivate:
    gimeta: ClassVar[_GIMeta]

class MountEntry:
    """
    Defines a Unix mount entry (e.g. ``/media/cdrom``).
    This corresponds roughly to a mtab entry.
    """
    gimeta: ClassVar[_GIMeta]
    def compare(self, mount2: MountEntry) -> int:
        """
        Compares two Unix mounts.
        """
    def copy(self) -> MountEntry:
        """
        Makes a copy of ``mount_entry``.
        """
    def free(self) -> None:
        """
        Frees a Unix mount.
        """
    def get_device_path(self) -> str:
        """
        Gets the device path for a Unix mount.
        """
    def get_fs_type(self) -> str:
        """
        Gets the filesystem type for the Unix mount.
        """
    def get_mount_path(self) -> str:
        """
        Gets the mount path for a Unix mount.
        """
    def get_options(self) -> str | None:
        """
        Gets a comma separated list of mount options for the Unix mount.

        For example: ``rw,relatime,seclabel,data=ordered``.

        This is similar to :meth:`GioUnix.MountPoint.get_options`, but it takes
        a :class:`GioUnix.MountEntry` as an argument.
        """
    def get_root_path(self) -> str | None:
        """
        Gets the root of the mount within the filesystem. This is useful e.g. for
        mounts created by bind operation, or btrfs subvolumes.

        For example, the root path is equal to ``/`` for a mount created by
        ``mount /dev/sda1 /mnt/foo`` and ``/bar`` for
        ``mount --bind /mnt/foo/bar /mnt/bar``.
        """
    def guess_can_eject(self) -> bool:
        """
        Guesses whether a Unix mount entry can be ejected.
        """
    def guess_icon(self) -> Gio.Icon:
        """
        Guesses the icon of a Unix mount entry.
        """
    def guess_name(self) -> str:
        """
        Guesses the name of a Unix mount entry.

        The result is a translated string.
        """
    def guess_should_display(self) -> bool:
        """
        Guesses whether a Unix mount entry should be displayed in the UI.
        """
    def guess_symbolic_icon(self) -> Gio.Icon:
        """
        Guesses the symbolic icon of a Unix mount entry.
        """
    def is_readonly(self) -> bool:
        """
        Checks if a Unix mount is mounted read only.
        """
    def is_system_internal(self) -> bool:
        """
        Checks if a Unix mount is a system mount.

        This is the Boolean OR of
        :func:`GioUnix.is_system_fs_type`, :func:`GioUnix.is_system_device_path` and
        :func:`GioUnix.is_mount_path_system_internal` on ``mount_entry``’s properties.

        The definition of what a ‘system’ mount entry is may change over time as new
        file system types and device paths are ignored.
        """
    @staticmethod
    def at(mount_path: str | bytes | os.PathLike[str] | os.PathLike[bytes]) -> tuple[MountEntry | None, int]:
        """
        Gets a :class:`GioUnix.MountEntry` for a given mount path.

        If ``time_read`` is set, it will be filled with a Unix timestamp for checking
        if the mounts have changed since with
        :func:`GioUnix.mount_entries_changed_since`.

        If more mounts have the same mount path, the last matching mount
        is returned.

        This will return ``None`` if there is no mount point at ``mount_path``.
        """
    @staticmethod
    def for_(file_path: str | bytes | os.PathLike[str] | os.PathLike[bytes]) -> tuple[MountEntry | None, int]:
        """
        Gets a :class:`GioUnix.MountEntry` for a given file path.

        If ``time_read`` is set, it will be filled with a Unix timestamp for checking
        if the mounts have changed since with
        :func:`GioUnix.mount_entries_changed_since`.

        If more mounts have the same mount path, the last matching mount
        is returned.

        This will return ``None`` if looking up the mount entry fails, if
        ``file_path`` doesn’t exist or there is an I/O error.
        """

class MountMonitor(GObject.Object):
    """
    Watches for changes to the set of mount entries and mount points in the
    system.

    Connect to the ``GioUnix.MountMonitor::mounts-changed`` signal to be
    notified of changes to the :class:`GioUnix.MountEntry` list.

    Connect to the ``GioUnix.MountMonitor::mountpoints-changed`` signal to
    be notified of changes to the :class:`GioUnix.MountPoint` list.
    """
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    @deprecated("Deprecated since 2.44.")
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...
    @deprecated("Deprecated since 2.44.")
    def set_rate_limit(self, limit_msec: int) -> None:
        """
        This function does nothing.

        Before 2.44, this was a partially-effective way of controlling the
        rate at which events would be reported under some uncommon
        circumstances.  Since ``mount_monitor`` is a singleton, it also meant
        that calling this function would have side effects for other users of
        the monitor.
        """
    @staticmethod
    def get() -> MountMonitor:
        """
        Gets the :class:`GioUnix.MountMonitor` for the current thread-default main
        context.

        The mount monitor can be used to monitor for changes to the list of
        mounted filesystems as well as the list of mount points (ie: fstab
        entries).

        You must only call :meth:`GObject.Object.unref` on the return value from
        under the same main context as you called this function.
        """
    mountpoints_changed: Signal[Self, [], None]
    mounts_changed: Signal[Self, [], None]
    def do_mountpoints_changed(self) -> None: ...
    def do_mounts_changed(self) -> None: ...

class MountMonitorClass:
    gimeta: ClassVar[_GIMeta]

class MountPoint:
    """
    Defines a Unix mount point (e.g. ``/dev``).
    This corresponds roughly to a fstab entry.
    """
    gimeta: ClassVar[_GIMeta]
    def compare(self, mount2: MountPoint) -> int:
        """
        Compares two Unix mount points.
        """
    def copy(self) -> MountPoint:
        """
        Makes a copy of ``mount_point``.
        """
    def free(self) -> None:
        """
        Frees a Unix mount point.
        """
    def get_device_path(self) -> str:
        """
        Gets the device path for a Unix mount point.
        """
    def get_fs_type(self) -> str:
        """
        Gets the file system type for the mount point.
        """
    def get_mount_path(self) -> str:
        """
        Gets the mount path for a Unix mount point.
        """
    def get_options(self) -> str | None:
        """
        Gets the options for the mount point.
        """
    def guess_can_eject(self) -> bool:
        """
        Guesses whether a Unix mount point can be ejected.
        """
    def guess_icon(self) -> Gio.Icon:
        """
        Guesses the icon of a Unix mount point.
        """
    def guess_name(self) -> str:
        """
        Guesses the name of a Unix mount point.

        The result is a translated string.
        """
    def guess_symbolic_icon(self) -> Gio.Icon:
        """
        Guesses the symbolic icon of a Unix mount point.
        """
    def is_loopback(self) -> bool:
        """
        Checks if a Unix mount point is a loopback device.
        """
    def is_readonly(self) -> bool:
        """
        Checks if a Unix mount point is read only.
        """
    def is_user_mountable(self) -> bool:
        """
        Checks if a Unix mount point is mountable by the user.
        """
    @staticmethod
    def at(mount_path: str | bytes | os.PathLike[str] | os.PathLike[bytes]) -> tuple[MountPoint | None, int]:
        """
        Gets a :class:`GioUnix.MountPoint` for a given mount path.

        If ``time_read`` is set, it will be filled with a Unix timestamp for checking if
        the mount points have changed since with
        :func:`GioUnix.mount_points_changed_since`.

        If more mount points have the same mount path, the last matching mount point
        is returned.
        """

class OutputStream(Gio.OutputStream, Gio.PollableOutputStream, FileDescriptorBased):
    """
    :class:`GioUnix.OutputStream` implements :class:`Gio.OutputStream` for writing to a UNIX
    file descriptor, including asynchronous operations. (If the file
    descriptor refers to a socket or pipe, this will use ``poll()`` to do
    asynchronous I/O. If it refers to a regular file, it will fall back
    to doing asynchronous I/O in another thread.)

    Note that ``<gio/gunixoutputstream.h>`` belongs to the UNIX-specific GIO
    interfaces, thus you have to use the ``gio-unix-2.0.pc`` pkg-config file
    file or the ``GioUnix-2.0`` GIR namespace when using it.
    """
    gimeta: ClassVar[_GIMeta]
    close_fd: bool
    fd: int
    def __init__(self, *, close_fd: bool = ..., fd: int = ..., **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...
    def get_close_fd(self) -> bool:
        """
        Returns whether the file descriptor of ``stream`` will be
        closed when the stream is closed.
        """
    def get_fd(self) -> int:
        """
        Return the UNIX file descriptor that the stream writes to.
        """
    def set_close_fd(self, close_fd: bool) -> None:
        """
        Sets whether the file descriptor of ``stream`` shall be closed
        when the stream is closed.
        """

class OutputStreamClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: Gio.OutputStreamClass

class OutputStreamPrivate:
    gimeta: ClassVar[_GIMeta]

DESKTOP_APP_INFO_LOOKUP_EXTENSION_POINT_NAME: str
"""
Extension point for default handler to URI association. See
[Extending GIO](overview.html#extending-gio).
"""
def is_mount_path_system_internal(mount_path: str | bytes | os.PathLike[str] | os.PathLike[bytes]) -> bool:
    """
    Determines if ``mount_path`` is considered an implementation of the
    OS.

    This is primarily used for hiding mountable and mounted volumes
    that only are used in the OS and has little to no relevance to the
    casual user.
    """
def is_system_device_path(device_path: str) -> bool:
    """
    Determines if ``device_path`` is considered a block device path which is only
    used in implementation of the OS.

    This is primarily used for hiding mounted volumes that are intended as APIs
    for programs to read, and system administrators at a shell; rather than
    something that should, for example, appear in a GUI. For example, the Linux
    ``/proc`` filesystem.

    The list of device paths considered ‘system’ ones may change over time.
    """
def is_system_fs_type(fs_type: str) -> bool:
    """
    Determines if ``fs_type`` is considered a type of file system which is only
    used in implementation of the OS.

    This is primarily used for hiding mounted volumes that are intended as APIs
    for programs to read, and system administrators at a shell; rather than
    something that should, for example, appear in a GUI. For example, the Linux
    ``/proc`` filesystem.

    The list of file system types considered ‘system’ ones may change over time.
    """
@deprecated("Deprecated since 2.84.")
def mount_at(mount_path: str | bytes | os.PathLike[str] | os.PathLike[bytes]) -> tuple[MountEntry | None, int]:
    """
    Gets a :class:`GioUnix.MountEntry` for a given mount path.

    If ``time_read`` is set, it will be filled with a Unix timestamp for checking
    if the mounts have changed since with
    :func:`GioUnix.mount_entries_changed_since`.

    If more mounts have the same mount path, the last matching mount
    is returned.

    This will return ``None`` if there is no mount point at ``mount_path``.
    """
@deprecated("Deprecated since 2.84.")
def mount_compare(mount1: MountEntry, mount2: MountEntry) -> int:
    """
    Compares two Unix mounts.
    """
@deprecated("Deprecated since 2.84.")
def mount_copy(mount_entry: MountEntry) -> MountEntry:
    """
    Makes a copy of ``mount_entry``.
    """
def mount_entries_changed_since(time: int) -> bool:
    """
    Checks if the Unix mounts have changed since a given Unix time.

    This can only work reliably if a :class:`GioUnix.MountMonitor` is running in
    the process, otherwise changes in the mount entries file (such as
    ``/proc/self/mountinfo`` on Linux) cannot be detected and, as a result, this
    function has to conservatively always return ``True``.

    It is more efficient to use ``GioUnix.MountMonitor::mounts-changed`` to
    be signalled of changes to the mount entries, rather than polling using this
    function. This function is more appropriate for infrequently determining
    cache validity.
    """
def mount_entries_get() -> tuple[list[MountEntry], int]:
    """
    Gets a list of :class:`GioUnix.MountEntry` instances representing the Unix
    mounts.

    If ``time_read`` is set, it will be filled with the mount timestamp, allowing
    for checking if the mounts have changed with
    :func:`GioUnix.mount_entries_changed_since`.
    """
def mount_entries_get_from_file(table_path: str) -> tuple[list[MountEntry] | None, int]:
    """
    Gets an array of :class:`GioUnix.MountEntry`s containing the Unix mounts
    listed in ``table_path``.

    This is a generalized version of :func:`GioUnix.mount_entries_get`, mainly
    intended for internal testing use. Note that :func:`GioUnix.mount_entries_get`
    may parse multiple hierarchical table files, so this function is not a direct
    superset of its functionality.

    If there is an error reading or parsing the file, ``None`` will be returned
    and both out parameters will be set to ``0``.
    """
def mount_entry_at(mount_path: str | bytes | os.PathLike[str] | os.PathLike[bytes]) -> tuple[MountEntry | None, int]:
    """
    Gets a :class:`GioUnix.MountEntry` for a given mount path.

    If ``time_read`` is set, it will be filled with a Unix timestamp for checking
    if the mounts have changed since with
    :func:`GioUnix.mount_entries_changed_since`.

    If more mounts have the same mount path, the last matching mount
    is returned.

    This will return ``None`` if there is no mount point at ``mount_path``.
    """
def mount_entry_for(file_path: str | bytes | os.PathLike[str] | os.PathLike[bytes]) -> tuple[MountEntry | None, int]:
    """
    Gets a :class:`GioUnix.MountEntry` for a given file path.

    If ``time_read`` is set, it will be filled with a Unix timestamp for checking
    if the mounts have changed since with
    :func:`GioUnix.mount_entries_changed_since`.

    If more mounts have the same mount path, the last matching mount
    is returned.

    This will return ``None`` if looking up the mount entry fails, if
    ``file_path`` doesn’t exist or there is an I/O error.
    """
@deprecated("Deprecated since 2.84.")
def mount_for(file_path: str | bytes | os.PathLike[str] | os.PathLike[bytes]) -> tuple[MountEntry | None, int]:
    """
    Gets a :class:`GioUnix.MountEntry` for a given file path.

    If ``time_read`` is set, it will be filled with a Unix timestamp for checking
    if the mounts have changed since with
    :func:`GioUnix.mount_entries_changed_since`.

    If more mounts have the same mount path, the last matching mount
    is returned.

    This will return ``None`` if looking up the mount entry fails, if
    ``file_path`` doesn’t exist or there is an I/O error.
    """
@deprecated("Deprecated since 2.84.")
def mount_free(mount_entry: MountEntry) -> None:
    """
    Frees a Unix mount.
    """
@deprecated("Deprecated since 2.84.")
def mount_get_device_path(mount_entry: MountEntry) -> str:
    """
    Gets the device path for a Unix mount.
    """
@deprecated("Deprecated since 2.84.")
def mount_get_fs_type(mount_entry: MountEntry) -> str:
    """
    Gets the filesystem type for the Unix mount.
    """
@deprecated("Deprecated since 2.84.")
def mount_get_mount_path(mount_entry: MountEntry) -> str:
    """
    Gets the mount path for a Unix mount.
    """
@deprecated("Deprecated since 2.84.")
def mount_get_options(mount_entry: MountEntry) -> str | None:
    """
    Gets a comma separated list of mount options for the Unix mount.

    For example: ``rw,relatime,seclabel,data=ordered``.

    This is similar to :meth:`GioUnix.MountPoint.get_options`, but it takes
    a :class:`GioUnix.MountEntry` as an argument.
    """
@deprecated("Deprecated since 2.84.")
def mount_get_root_path(mount_entry: MountEntry) -> str | None:
    """
    Gets the root of the mount within the filesystem.

    This is useful e.g. for mounts created by bind operation, or btrfs subvolumes.

    For example, the root path is equal to ``/`` for a mount created by
    ``mount /dev/sda1 /mnt/foo`` and ``/bar`` for
    ``mount --bind /mnt/foo/bar /mnt/bar``.
    """
@deprecated("Deprecated since 2.84.")
def mount_guess_can_eject(mount_entry: MountEntry) -> bool:
    """
    Guesses whether a Unix mount entry can be ejected.
    """
@deprecated("Deprecated since 2.84.")
def mount_guess_icon(mount_entry: MountEntry) -> Gio.Icon:
    """
    Guesses the icon of a Unix mount entry.
    """
@deprecated("Deprecated since 2.84.")
def mount_guess_name(mount_entry: MountEntry) -> str:
    """
    Guesses the name of a Unix mount entry.

    The result is a translated string.
    """
@deprecated("Deprecated since 2.84.")
def mount_guess_should_display(mount_entry: MountEntry) -> bool:
    """
    Guesses whether a Unix mount entry should be displayed in the UI.
    """
@deprecated("Deprecated since 2.84.")
def mount_guess_symbolic_icon(mount_entry: MountEntry) -> Gio.Icon:
    """
    Guesses the symbolic icon of a Unix mount entry.
    """
@deprecated("Deprecated since 2.84.")
def mount_is_readonly(mount_entry: MountEntry) -> bool:
    """
    Checks if a Unix mount is mounted read only.
    """
@deprecated("Deprecated since 2.84.")
def mount_is_system_internal(mount_entry: MountEntry) -> bool:
    """
    Checks if a Unix mount is a system mount.

    This is the Boolean OR of
    :func:`GioUnix.is_system_fs_type`, :func:`GioUnix.is_system_device_path` and
    :func:`GioUnix.is_mount_path_system_internal` on ``mount_entry``’s properties.

    The definition of what a ‘system’ mount entry is may change over time as new
    file system types and device paths are ignored.
    """
def mount_point_at(mount_path: str | bytes | os.PathLike[str] | os.PathLike[bytes]) -> tuple[MountPoint | None, int]:
    """
    Gets a :class:`GioUnix.MountPoint` for a given mount path.

    If ``time_read`` is set, it will be filled with a Unix timestamp for checking if
    the mount points have changed since with
    :func:`GioUnix.mount_points_changed_since`.

    If more mount points have the same mount path, the last matching mount point
    is returned.
    """
def mount_points_changed_since(time: int) -> bool:
    """
    Checks if the Unix mount points have changed since a given Unix time.

    Unlike :func:`GioUnix.mount_entries_changed_since`, this function can work
    reliably without a :class:`GioUnix.MountMonitor` running, as it accesses the
    static mount point information (such as ``/etc/fstab`` on Linux), which has a
    valid modification time.

    It is more efficient to use ``GioUnix.MountMonitor::mountpoints-changed``
    to be signalled of changes to the mount points, rather than polling using
    this function. This function is more appropriate for infrequently determining
    cache validity.
    """
def mount_points_get() -> tuple[list[MountPoint], int]:
    """
    Gets a list of :class:`GioUnix.MountPoint` instances representing the Unix
    mount points.

    If ``time_read`` is set, it will be filled with the mount timestamp, allowing
    for checking if the mounts have changed with
    :func:`GioUnix.mount_points_changed_since`.
    """
def mount_points_get_from_file(table_path: str) -> tuple[list[MountPoint] | None, int]:
    """
    Gets an array of :class:`GioUnix.MountPoint`s containing the Unix mount
    points listed in ``table_path``.

    This is a generalized version of :func:`GioUnix.mount_points_get`, mainly
    intended for internal testing use. Note that :func:`GioUnix.mount_points_get`
    may parse multiple hierarchical table files, so this function is not a direct
    superset of its functionality.

    If there is an error reading or parsing the file, ``None`` will be returned
    and both out parameters will be set to ``0``.
    """
@deprecated("Deprecated since 2.84.")
def mounts_changed_since(time: int) -> bool:
    """
    Checks if the Unix mounts have changed since a given Unix time.
    """
@deprecated("Deprecated since 2.84.")
def mounts_get() -> tuple[list[MountEntry], int]:
    """
    Gets a list of :class:`GioUnix.MountEntry` instances representing the Unix
    mounts.

    If ``time_read`` is set, it will be filled with the mount timestamp, allowing
    for checking if the mounts have changed with
    :func:`GioUnix.mount_entries_changed_since`.
    """
@deprecated("Deprecated since 2.84.")
def mounts_get_from_file(table_path: str) -> tuple[list[MountEntry] | None, int]:
    """
    Gets an array of :class:`GioUnix.MountEntry`s containing the Unix mounts
    listed in ``table_path``.

    This is a generalized version of :func:`GioUnix.mount_entries_get`, mainly
    intended for internal testing use. Note that :func:`GioUnix.mount_entries_get`
    may parse multiple hierarchical table files, so this function is not a direct
    superset of its functionality.

    If there is an error reading or parsing the file, ``None`` will be returned
    and both out parameters will be set to ``0``.
    """
