# Auto-generated by ginext-stubgen from GModule-2.0.gir.
# Do not edit by hand.
# mypy: disable-error-code="override,type-arg,misc,valid-type"
from __future__ import annotations

from collections.abc import Iterator
from typing_extensions import deprecated
from typing import Any, Awaitable, Callable, ClassVar, Final, Generic, Literal, NamedTuple, Self, TypeVar, override, overload
from enum import IntEnum, IntFlag
from ginext import GLib
from ginext.overlay.registrar import OverlayRegistrar as _OverlayRegistrar
from ginext.private import GIMeta as _GIMeta

overlay: _OverlayRegistrar
__version__: tuple[int, ...]
def __getattr__(name: str) -> Any: ...

class ModuleError(IntEnum):
    FAILED = 0
    CHECK_FAILED = 1

class ModuleFlags(IntFlag):
    LAZY = 1
    LOCAL = 2
    MASK = 3

ModuleCheckInit = Callable[[Module], str]
ModuleUnload = Callable[[Module], None]
class Module:
    """
    The :class:`GModule.Module` struct is an opaque data structure to represent a
    [dynamically-loaded module](modules.html#dynamic-loading-of-modules).
    It should only be accessed via the following functions.

    To ensure correct lock ordering, these functions must not be called from
    global constructors (for example, those using GCC’s
    ``__attribute__((constructor))`` attribute).
    """
    gimeta: ClassVar[_GIMeta]
    def close(self) -> bool:
        """
        Closes a module.
        """
    def make_resident(self) -> None:
        """
        Ensures that a module will never be unloaded.
        Any future :meth::class:`GModule.Module`.Module.close` calls on the module will be ignored.
        """
    def name(self) -> str:
        """
        Returns the filename that the module was opened with.

        If ``module`` refers to the application itself, "main" is returned.
        """
    def symbol(self, symbol_name: str) -> tuple[bool, int]:
        """
        Gets a symbol pointer from a module, such as one exported
        by ``G_MODULE_EXPORT``. Note that a valid symbol can be ``None``.
        """
    @deprecated("Deprecated since 2.76.")
    @staticmethod
    def build_path(directory: str | None, module_name: str) -> str:
        """
        A portable way to build the filename of a module. The platform-specific
        prefix and suffix are added to the filename, if needed, and the result
        is added to the directory, using the correct separator character.

        The directory should specify the directory where the module can be found.
        It can be ``None`` or an empty string to indicate that the module is in a
        standard platform-specific directory, though this is not recommended
        since the wrong module may be found.

        For example, calling :func::class:`GModule.Module`.module_build_path` on a Linux system with a
        ``directory`` of ``/lib`` and a ``module_name`` of "mylibrary" will return
        ``/lib/libmylibrary.so``. On a Windows system, using ``\\Windows`` as the
        directory it will return ``\\Windows\\mylibrary.dll``.
        """
    @staticmethod
    def error() -> str:
        """
        Gets a string describing the last module error.
        """
    @staticmethod
    def error_quark() -> GLib.Quark: ...
    @staticmethod
    def supported() -> bool:
        """
        Checks if modules are supported on the current platform.
        """

MODULE_IMPL_AR: int
MODULE_IMPL_DL: int
MODULE_IMPL_NONE: int
MODULE_IMPL_WIN32: int
@deprecated("Deprecated since 2.76.")
def module_build_path(directory: str | None, module_name: str) -> str:
    """
    A portable way to build the filename of a module. The platform-specific
    prefix and suffix are added to the filename, if needed, and the result
    is added to the directory, using the correct separator character.

    The directory should specify the directory where the module can be found.
    It can be ``None`` or an empty string to indicate that the module is in a
    standard platform-specific directory, though this is not recommended
    since the wrong module may be found.

    For example, calling :func::class:`GModule.Module`.module_build_path` on a Linux system with a
    ``directory`` of ``/lib`` and a ``module_name`` of "mylibrary" will return
    ``/lib/libmylibrary.so``. On a Windows system, using ``\\Windows`` as the
    directory it will return ``\\Windows\\mylibrary.dll``.
    """
def module_error() -> str:
    """
    Gets a string describing the last module error.
    """
def module_error_quark() -> GLib.Quark: ...
def module_supported() -> bool:
    """
    Checks if modules are supported on the current platform.
    """
