# Auto-generated by ginext-stubgen from Graphene-1.0.gir.
# Do not edit by hand.
# mypy: disable-error-code="override,type-arg,misc,valid-type"
from __future__ import annotations

from collections.abc import Iterator
from typing_extensions import deprecated
from typing import Any, Awaitable, Callable, ClassVar, Final, Generic, Literal, NamedTuple, Self, TypeVar, override, overload
from enum import IntEnum, IntFlag
from ginext.overlay.registrar import OverlayRegistrar as _OverlayRegistrar
from ginext.private import GIMeta as _GIMeta

overlay: _OverlayRegistrar
__version__: tuple[int, ...]
def __getattr__(name: str) -> Any: ...

class EulerOrder(IntEnum):
    DEFAULT = -1
    XYZ = 0
    YZX = 1
    ZXY = 2
    XZY = 3
    YXZ = 4
    ZYX = 5
    SXYZ = 6
    SXYX = 7
    SXZY = 8
    SXZX = 9
    SYZX = 10
    SYZY = 11
    SYXZ = 12
    SYXY = 13
    SZXY = 14
    SZXZ = 15
    SZYX = 16
    SZYZ = 17
    RZYX = 18
    RXYX = 19
    RYZX = 20
    RXZX = 21
    RXZY = 22
    RYZY = 23
    RZXY = 24
    RYXY = 25
    RYXZ = 26
    RZXZ = 27
    RXYZ = 28
    RZYZ = 29

class RayIntersectionKind(IntEnum):
    NONE = 0
    ENTER = 1
    LEAVE = 2

class Box:
    """
    A 3D box, described as the volume between a minimum and
    a maximum vertices.
    """
    gimeta: ClassVar[_GIMeta]
    min: Vec3
    max: Vec3
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Box`.

        The contents of the returned structure are undefined.
        """
    def contains_box(self, b: Box) -> bool:
        """
        Checks whether the :class:`Graphene.Box` ``a`` contains the given
        :class:`Graphene.Box` ``b``.
        """
    def contains_point(self, point: Point3D) -> bool:
        """
        Checks whether ``box`` contains the given ``point``.
        """
    def equal(self, b: Box) -> bool:
        """
        Checks whether the two given boxes are equal.
        """
    def expand(self, point: Point3D) -> Box:
        """
        Expands the dimensions of ``box`` to include the coordinates at ``point``.
        """
    def expand_scalar(self, scalar: float) -> Box:
        """
        Expands the dimensions of ``box`` by the given ``scalar`` value.

        If ``scalar`` is positive, the :class:`Graphene.Box` will grow; if ``scalar`` is
        negative, the :class:`Graphene.Box` will shrink.
        """
    def expand_vec3(self, vec: Vec3) -> Box:
        """
        Expands the dimensions of ``box`` to include the coordinates of the
        given vector.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :meth:`Graphene.Box.alloc`.
        """
    def get_bounding_sphere(self) -> Sphere:
        """
        Computes the bounding :class:`Graphene.Sphere` capable of containing the given
        :class:`Graphene.Box`.
        """
    def get_center(self) -> Point3D:
        """
        Retrieves the coordinates of the center of a :class:`Graphene.Box`.
        """
    def get_depth(self) -> float:
        """
        Retrieves the size of the ``box`` on the Z axis.
        """
    def get_height(self) -> float:
        """
        Retrieves the size of the ``box`` on the Y axis.
        """
    def get_max(self) -> Point3D:
        """
        Retrieves the coordinates of the maximum point of the given
        :class:`Graphene.Box`.
        """
    def get_min(self) -> Point3D:
        """
        Retrieves the coordinates of the minimum point of the given
        :class:`Graphene.Box`.
        """
    def get_size(self) -> Vec3:
        """
        Retrieves the size of the box on all three axes, and stores
        it into the given ``size`` vector.
        """
    def get_vertices(self) -> list[Vec3]:
        """
        Computes the vertices of the given :class:`Graphene.Box`.
        """
    def get_width(self) -> float:
        """
        Retrieves the size of the ``box`` on the X axis.
        """
    def init(self, min: Point3D | None = ..., max: Point3D | None = ...) -> Box:
        """
        Initializes the given :class:`Graphene.Box` with two vertices.
        """
    def init_from_box(self, src: Box) -> Box:
        """
        Initializes the given :class:`Graphene.Box` with the vertices of
        another :class:`Graphene.Box`.
        """
    def init_from_points(self, points: list[Point3D]) -> Box:
        """
        Initializes the given :class:`Graphene.Box` with the given array
        of vertices.

        If ``n_points`` is 0, the returned box is initialized with
        :func:`Graphene.box_empty`.
        """
    def init_from_vec3(self, min: Vec3 | None = ..., max: Vec3 | None = ...) -> Box:
        """
        Initializes the given :class:`Graphene.Box` with two vertices
        stored inside :class:`Graphene.Vec3`.
        """
    def init_from_vectors(self, vectors: list[Vec3]) -> Box:
        """
        Initializes the given :class:`Graphene.Box` with the given array
        of vertices.

        If ``n_vectors`` is 0, the returned box is initialized with
        :func:`Graphene.box_empty`.
        """
    def intersection(self, b: Box) -> tuple[bool, Box]:
        """
        Intersects the two given :class:`Graphene.Box`.

        If the two boxes do not intersect, ``res`` will contain a degenerate box
        initialized with :func:`Graphene.box_empty`.
        """
    def union(self, b: Box) -> Box:
        """
        Unions the two given :class:`Graphene.Box`.
        """
    @staticmethod
    def empty() -> Box:
        """
        A degenerate :class:`Graphene.Box` that can only be expanded.

        The returned value is owned by Graphene and should not be modified or freed.
        """
    @staticmethod
    def infinite() -> Box:
        """
        A degenerate :class:`Graphene.Box` that cannot be expanded.

        The returned value is owned by Graphene and should not be modified or freed.
        """
    @staticmethod
    def minus_one() -> Box:
        """
        A :class:`Graphene.Box` with the minimum vertex set at (-1, -1, -1) and the
        maximum vertex set at (0, 0, 0).

        The returned value is owned by Graphene and should not be modified or freed.
        """
    @staticmethod
    def one() -> Box:
        """
        A :class:`Graphene.Box` with the minimum vertex set at (0, 0, 0) and the
        maximum vertex set at (1, 1, 1).

        The returned value is owned by Graphene and should not be modified or freed.
        """
    @staticmethod
    def one_minus_one() -> Box:
        """
        A :class:`Graphene.Box` with the minimum vertex set at (-1, -1, -1) and the
        maximum vertex set at (1, 1, 1).

        The returned value is owned by Graphene and should not be modified or freed.
        """
    @staticmethod
    def zero() -> Box:
        """
        A :class:`Graphene.Box` with both the minimum and maximum vertices set at (0, 0, 0).

        The returned value is owned by Graphene and should not be modified or freed.
        """

class Euler:
    """
    Describe a rotation using Euler angles.

    The contents of the :class:`Graphene.Euler` structure are private
    and should never be accessed directly.
    """
    gimeta: ClassVar[_GIMeta]
    angles: Vec3
    order: EulerOrder | int
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Euler`.

        The contents of the returned structure are undefined.
        """
    def equal(self, b: Euler) -> bool:
        """
        Checks if two :class:`Graphene.Euler` are equal.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :meth:`Graphene.Euler.alloc`.
        """
    def get_alpha(self) -> float:
        """
        Retrieves the first component of the Euler angle vector,
        depending on the order of rotation.

        See also: :meth:`Graphene.Euler.get_x`
        """
    def get_beta(self) -> float:
        """
        Retrieves the second component of the Euler angle vector,
        depending on the order of rotation.

        See also: :meth:`Graphene.Euler.get_y`
        """
    def get_gamma(self) -> float:
        """
        Retrieves the third component of the Euler angle vector,
        depending on the order of rotation.

        See also: :meth:`Graphene.Euler.get_z`
        """
    def get_order(self) -> EulerOrder:
        """
        Retrieves the order used to apply the rotations described in the
        :class:`Graphene.Euler` structure, when converting to and from other
        structures, like :class:`Graphene.Quaternion` and :class:`Graphene.Matrix`.

        This function does not return the :data:`Graphene.EulerOrder.DEFAULT`
        enumeration value; it will return the effective order of rotation
        instead.
        """
    def get_x(self) -> float:
        """
        Retrieves the rotation angle on the X axis, in degrees.
        """
    def get_y(self) -> float:
        """
        Retrieves the rotation angle on the Y axis, in degrees.
        """
    def get_z(self) -> float:
        """
        Retrieves the rotation angle on the Z axis, in degrees.
        """
    def init(self, x: float, y: float, z: float) -> Euler:
        """
        Initializes a :class:`Graphene.Euler` using the given angles.

        The order of the rotations is :data:`Graphene.EulerOrder.DEFAULT`.
        """
    def init_from_euler(self, src: Euler | None = ...) -> Euler:
        """
        Initializes a :class:`Graphene.Euler` using the angles and order of
        another :class:`Graphene.Euler`.

        If the :class:`Graphene.Euler` ``src`` is ``None``, this function is equivalent
        to calling :meth:`Graphene.Euler.init` with all angles set to 0.
        """
    def init_from_matrix(self, m: Matrix | None, order: EulerOrder | int) -> Euler:
        """
        Initializes a :class:`Graphene.Euler` using the given rotation matrix.

        If the :class:`Graphene.Matrix` ``m`` is ``None``, the :class:`Graphene.Euler` will
        be initialized with all angles set to 0.
        """
    def init_from_quaternion(self, q: Quaternion | None, order: EulerOrder | int) -> Euler:
        """
        Initializes a :class:`Graphene.Euler` using the given normalized quaternion.

        If the :class:`Graphene.Quaternion` ``q`` is ``None``, the :class:`Graphene.Euler` will
        be initialized with all angles set to 0.
        """
    def init_from_radians(self, x: float, y: float, z: float, order: EulerOrder | int) -> Euler:
        """
        Initializes a :class:`Graphene.Euler` using the given angles
        and order of rotation.
        """
    def init_from_vec3(self, v: Vec3 | None, order: EulerOrder | int) -> Euler:
        """
        Initializes a :class:`Graphene.Euler` using the angles contained in a
        :class:`Graphene.Vec3`.

        If the :class:`Graphene.Vec3` ``v`` is ``None``, the :class:`Graphene.Euler` will be
        initialized with all angles set to 0.
        """
    def init_with_order(self, x: float, y: float, z: float, order: EulerOrder | int) -> Euler:
        """
        Initializes a :class:`Graphene.Euler` with the given angles and ``order``.
        """
    def reorder(self, order: EulerOrder | int) -> Euler:
        """
        Reorders a :class:`Graphene.Euler` using ``order``.

        This function is equivalent to creating a :class:`Graphene.Quaternion` from the
        given :class:`Graphene.Euler`, and then converting the quaternion into another
        :class:`Graphene.Euler`.
        """
    def to_matrix(self) -> Matrix:
        """
        Converts a :class:`Graphene.Euler` into a transformation matrix expressing
        the extrinsic composition of rotations described by the Euler angles.

        The rotations are applied over the reference frame axes in the order
        associated with the :class:`Graphene.Euler`; for instance, if the order
        used to initialize ``e`` is :data:`Graphene.EulerOrder.XYZ`:

         * the first rotation moves the body around the X axis with
           an angle φ
         * the second rotation moves the body around the Y axis with
           an angle of ϑ
         * the third rotation moves the body around the Z axis with
           an angle of ψ

        The rotation sign convention is right-handed, to preserve compatibility
        between Euler-based, quaternion-based, and angle-axis-based rotations.
        """
    def to_quaternion(self) -> Quaternion:
        """
        Converts a :class:`Graphene.Euler` into a :class:`Graphene.Quaternion`.
        """
    def to_vec3(self) -> Vec3:
        """
        Retrieves the angles of a :class:`Graphene.Euler` and initializes a
        :class:`Graphene.Vec3` with them.
        """

class Frustum:
    """
    A 3D volume delimited by 2D clip planes.

    The contents of the :class:`Graphene.Frustum` are private, and should not be
    modified directly.
    """
    gimeta: ClassVar[_GIMeta]
    planes: list[Plane]
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Frustum` structure.

        The contents of the returned structure are undefined.
        """
    def contains_point(self, point: Point3D) -> bool:
        """
        Checks whether a point is inside the volume defined by the given
        :class:`Graphene.Frustum`.
        """
    def equal(self, b: Frustum) -> bool:
        """
        Checks whether the two given :class:`Graphene.Frustum` are equal.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :meth:`Graphene.Frustum.alloc`.
        """
    def get_planes(self) -> list[Plane]:
        """
        Retrieves the planes that define the given :class:`Graphene.Frustum`.
        """
    def init(self, p0: Plane, p1: Plane, p2: Plane, p3: Plane, p4: Plane, p5: Plane) -> Frustum:
        """
        Initializes the given :class:`Graphene.Frustum` using the provided
        clipping planes.
        """
    def init_from_frustum(self, src: Frustum) -> Frustum:
        """
        Initializes the given :class:`Graphene.Frustum` using the clipping
        planes of another :class:`Graphene.Frustum`.
        """
    def init_from_matrix(self, matrix: Matrix) -> Frustum:
        """
        Initializes a :class:`Graphene.Frustum` using the given ``matrix``.
        """
    def intersects_box(self, box: Box) -> bool:
        """
        Checks whether the given ``box`` intersects a plane of
        a :class:`Graphene.Frustum`.
        """
    def intersects_sphere(self, sphere: Sphere) -> bool:
        """
        Checks whether the given ``sphere`` intersects a plane of
        a :class:`Graphene.Frustum`.
        """

class Matrix:
    """
    A structure capable of holding a 4x4 matrix.

    The contents of the :class:`Graphene.Matrix` structure are private and
    should never be accessed directly.
    """
    gimeta: ClassVar[_GIMeta]
    value: Simd4X4F
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Matrix`.
        """
    def decompose(self) -> tuple[bool, Vec3, Vec3, Quaternion, Vec3, Vec4]:
        """
        Decomposes a transformation matrix into its component transformations.

        The algorithm for decomposing a matrix is taken from the
        `CSS3 Transforms specification <http://dev.w3.org/csswg/css-transforms/>`_;
        specifically, the decomposition code is based on the equivalent code
        published in "Graphics Gems II", edited by Jim Arvo, and
        `available online <http://web.archive.org/web/20150512160205/http://tog.acm.org/resources/GraphicsGems/gemsii/unmatrix.c>`_.
        """
    def determinant(self) -> float:
        """
        Computes the determinant of the given matrix.
        """
    def equal(self, b: Matrix) -> bool:
        """
        Checks whether the two given :class:`Graphene.Matrix` matrices are equal.
        """
    def equal_fast(self, b: Matrix) -> bool:
        """
        Checks whether the two given :class:`Graphene.Matrix` matrices are
        byte-by-byte equal.

        While this function is faster than :meth:`Graphene.Matrix.equal`, it
        can also return false negatives, so it should be used in
        conjuction with either :meth:`Graphene.Matrix.equal` or
        :meth:`Graphene.Matrix.near`. For instance:

        |[<!-- language="C" -->
          if (:meth:`Graphene.Matrix.equal_fast` (a, b))
            {
              // matrices are definitely the same
            }
          else
            {
              if (:meth:`Graphene.Matrix.equal` (a, b))
                // matrices contain the same values within an epsilon of FLT_EPSILON
              else if (:meth:`Graphene.Matrix.near` (a, b, 0.0001))
                // matrices contain the same values within an epsilon of 0.0001
              else
                // matrices are not equal
            }
        ]|
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :meth:`Graphene.Matrix.alloc`.
        """
    def get_row(self, index_: int) -> Vec4:
        """
        Retrieves the given row vector at ``index_`` inside a matrix.
        """
    def get_value(self, row: int, col: int) -> float:
        """
        Retrieves the value at the given ``row`` and ``col`` index.
        """
    def get_x_scale(self) -> float:
        """
        Retrieves the scaling factor on the X axis in ``m``.
        """
    def get_x_translation(self) -> float:
        """
        Retrieves the translation component on the X axis from ``m``.
        """
    def get_y_scale(self) -> float:
        """
        Retrieves the scaling factor on the Y axis in ``m``.
        """
    def get_y_translation(self) -> float:
        """
        Retrieves the translation component on the Y axis from ``m``.
        """
    def get_z_scale(self) -> float:
        """
        Retrieves the scaling factor on the Z axis in ``m``.
        """
    def get_z_translation(self) -> float:
        """
        Retrieves the translation component on the Z axis from ``m``.
        """
    def init_from_2d(self, xx: float, yx: float, xy: float, yy: float, x_0: float, y_0: float) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` from the values of an affine
        transformation matrix.

        The arguments map to the following matrix layout:

        |[<!-- language="plain" -->
          ⎛ xx  yx ⎞   ⎛  a   b  0 ⎞
          ⎜ xy  yy ⎟ = ⎜  c   d  0 ⎟
          ⎝ x0  y0 ⎠   ⎝ tx  ty  1 ⎠
        ]|

        This function can be used to convert between an affine matrix type
        from other libraries and a :class:`Graphene.Matrix`.
        """
    def init_from_float(self, v: list[float]) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` with the given array of floating
        point values.
        """
    def init_from_matrix(self, src: Matrix) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` using the values of the
        given matrix.
        """
    def init_from_vec4(self, v0: Vec4, v1: Vec4, v2: Vec4, v3: Vec4) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` with the given four row
        vectors.
        """
    def init_frustum(self, left: float, right: float, bottom: float, top: float, z_near: float, z_far: float) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` compatible with :class:`Graphene.Frustum`.

        See also: :meth:`Graphene.Frustum.init_from_matrix`
        """
    def init_identity(self) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` with the identity matrix.
        """
    def init_look_at(self, eye: Vec3, center: Vec3, up: Vec3) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` so that it positions the "camera"
        at the given ``eye`` coordinates towards an object at the ``center``
        coordinates. The top of the camera is aligned to the direction
        of the ``up`` vector.

        Before the transform, the camera is assumed to be placed at the
        origin, looking towards the negative Z axis, with the top side of
        the camera facing in the direction of the Y axis and the right
        side in the direction of the X axis.

        In theory, one could use ``m`` to transform a model of such a camera
        into world-space. However, it is more common to use the inverse of
        ``m`` to transform another object from world coordinates to the view
        coordinates of the camera. Typically you would then apply the
        camera projection transform to get from view to screen
        coordinates.
        """
    def init_ortho(self, left: float, right: float, top: float, bottom: float, z_near: float, z_far: float) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` with an orthographic projection.
        """
    def init_perspective(self, fovy: float, aspect: float, z_near: float, z_far: float) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` with a perspective projection.
        """
    def init_rotate(self, angle: float, axis: Vec3) -> Matrix:
        """
        Initializes ``m`` to represent a rotation of ``angle`` degrees on
        the axis represented by the ``axis`` vector.
        """
    def init_scale(self, x: float, y: float, z: float) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` with the given scaling factors.
        """
    def init_skew(self, x_skew: float, y_skew: float) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` with a skew transformation
        with the given factors.
        """
    def init_translate(self, p: Point3D) -> Matrix:
        """
        Initializes a :class:`Graphene.Matrix` with a translation to the
        given coordinates.
        """
    def interpolate(self, b: Matrix, factor: float) -> Matrix:
        """
        Linearly interpolates the two given :class:`Graphene.Matrix` by
        interpolating the decomposed transformations separately.

        If either matrix cannot be reduced to their transformations
        then the interpolation cannot be performed, and this function
        will return an identity matrix.
        """
    def inverse(self) -> tuple[bool, Matrix]:
        """
        Inverts the given matrix.
        """
    def is_2d(self) -> bool:
        """
        Checks whether the given :class:`Graphene.Matrix` is compatible with an
        a 2D affine transformation matrix.
        """
    def is_backface_visible(self) -> bool:
        """
        Checks whether a :class:`Graphene.Matrix` has a visible back face.
        """
    def is_identity(self) -> bool:
        """
        Checks whether the given :class:`Graphene.Matrix` is the identity matrix.
        """
    def is_singular(self) -> bool:
        """
        Checks whether a matrix is singular.
        """
    def multiply(self, b: Matrix) -> Matrix:
        """
        Multiplies two :class:`Graphene.Matrix`.

        Matrix multiplication is not commutative in general; the order of the factors matters.
        The product of this multiplication is (``a`` × ``b``)
        """
    def near(self, b: Matrix, epsilon: float) -> bool:
        """
        Compares the two given :class:`Graphene.Matrix` matrices and checks
        whether their values are within the given ``epsilon`` of each
        other.
        """
    def normalize(self) -> Matrix:
        """
        Normalizes the given :class:`Graphene.Matrix`.
        """
    def perspective(self, depth: float) -> Matrix:
        """
        Applies a perspective of ``depth`` to the matrix.
        """
    def print(self) -> None:
        """
        Prints the contents of a matrix to the standard error stream.

        This function is only useful for debugging; there are no guarantees
        made on the format of the output.
        """
    def project_point(self, p: Point) -> Point:
        """
        Projects a :class:`Graphene.Point` using the matrix ``m``.
        """
    def project_rect(self, r: Rect) -> Quad:
        """
        Projects all corners of a :class:`Graphene.Rect` using the given matrix.

        See also: :meth:`Graphene.Matrix.project_point`
        """
    def project_rect_bounds(self, r: Rect) -> Rect:
        """
        Projects a :class:`Graphene.Rect` using the given matrix.

        The resulting rectangle is the axis aligned bounding rectangle capable
        of fully containing the projected rectangle.
        """
    def rotate(self, angle: float, axis: Vec3) -> None:
        """
        Adds a rotation transformation to ``m``, using the given ``angle``
        and ``axis`` vector.

        This is the equivalent of calling :meth:`Graphene.Matrix.init_rotate` and
        then multiplying the matrix ``m`` with the rotation matrix.
        """
    def rotate_euler(self, e: Euler) -> None:
        """
        Adds a rotation transformation to ``m``, using the given
        :class:`Graphene.Euler`.
        """
    def rotate_quaternion(self, q: Quaternion) -> None:
        """
        Adds a rotation transformation to ``m``, using the given
        :class:`Graphene.Quaternion`.

        This is the equivalent of calling :meth:`Graphene.Quaternion.to_matrix` and
        then multiplying ``m`` with the rotation matrix.
        """
    def rotate_x(self, angle: float) -> None:
        """
        Adds a rotation transformation around the X axis to ``m``, using
        the given ``angle``.

        See also: :meth:`Graphene.Matrix.rotate`
        """
    def rotate_y(self, angle: float) -> None:
        """
        Adds a rotation transformation around the Y axis to ``m``, using
        the given ``angle``.

        See also: :meth:`Graphene.Matrix.rotate`
        """
    def rotate_z(self, angle: float) -> None:
        """
        Adds a rotation transformation around the Z axis to ``m``, using
        the given ``angle``.

        See also: :meth:`Graphene.Matrix.rotate`
        """
    def scale(self, factor_x: float, factor_y: float, factor_z: float) -> None:
        """
        Adds a scaling transformation to ``m``, using the three
        given factors.

        This is the equivalent of calling :meth:`Graphene.Matrix.init_scale` and then
        multiplying the matrix ``m`` with the scale matrix.
        """
    def skew_xy(self, factor: float) -> None:
        """
        Adds a skew of ``factor`` on the X and Y axis to the given matrix.
        """
    def skew_xz(self, factor: float) -> None:
        """
        Adds a skew of ``factor`` on the X and Z axis to the given matrix.
        """
    def skew_yz(self, factor: float) -> None:
        """
        Adds a skew of ``factor`` on the Y and Z axis to the given matrix.
        """
    def to_2d(self) -> tuple[bool, float, float, float, float, float, float]:
        """
        Converts a :class:`Graphene.Matrix` to an affine transformation
        matrix, if the given matrix is compatible.

        The returned values have the following layout:

        |[<!-- language="plain" -->
          ⎛ xx  yx ⎞   ⎛  a   b  0 ⎞
          ⎜ xy  yy ⎟ = ⎜  c   d  0 ⎟
          ⎝ x0  y0 ⎠   ⎝ tx  ty  1 ⎠
        ]|

        This function can be used to convert between a :class:`Graphene.Matrix`
        and an affine matrix type from other libraries.
        """
    def to_float(self) -> list[float]:
        """
        Converts a :class:`Graphene.Matrix` to an array of floating point
        values.
        """
    def transform_bounds(self, r: Rect) -> Rect:
        """
        Transforms each corner of a :class:`Graphene.Rect` using the given matrix ``m``.

        The result is the axis aligned bounding rectangle containing the coplanar
        quadrilateral.

        See also: :meth:`Graphene.Matrix.transform_point`
        """
    def transform_box(self, b: Box) -> Box:
        """
        Transforms the vertices of a :class:`Graphene.Box` using the given matrix ``m``.

        The result is the axis aligned bounding box containing the transformed
        vertices.
        """
    def transform_point(self, p: Point) -> Point:
        """
        Transforms the given :class:`Graphene.Point` using the matrix ``m``.

        Unlike :meth:`Graphene.Matrix.transform_vec3`, this function will take into
        account the fourth row vector of the :class:`Graphene.Matrix` when computing
        the dot product of each row vector of the matrix.

        See also: graphene_simd4x4f_point3_mul()
        """
    def transform_point3d(self, p: Point3D) -> Point3D:
        """
        Transforms the given :class:`Graphene.Point3D` using the matrix ``m``.

        Unlike :meth:`Graphene.Matrix.transform_vec3`, this function will take into
        account the fourth row vector of the :class:`Graphene.Matrix` when computing
        the dot product of each row vector of the matrix.

        See also: graphene_simd4x4f_point3_mul()
        """
    def transform_ray(self, r: Ray) -> Ray:
        """
        Transform a :class:`Graphene.Ray` using the given matrix ``m``.
        """
    def transform_rect(self, r: Rect) -> Quad:
        """
        Transforms each corner of a :class:`Graphene.Rect` using the given matrix ``m``.

        The result is a coplanar quadrilateral.

        See also: :meth:`Graphene.Matrix.transform_point`
        """
    def transform_sphere(self, s: Sphere) -> Sphere:
        """
        Transforms a :class:`Graphene.Sphere` using the given matrix ``m``. The
        result is the bounding sphere containing the transformed sphere.
        """
    def transform_vec3(self, v: Vec3) -> Vec3:
        """
        Transforms the given :class:`Graphene.Vec3` using the matrix ``m``.

        This function will multiply the X, Y, and Z row vectors of the matrix ``m``
        with the corresponding components of the vector ``v``. The W row vector will
        be ignored.

        See also: graphene_simd4x4f_vec3_mul()
        """
    def transform_vec4(self, v: Vec4) -> Vec4:
        """
        Transforms the given :class:`Graphene.Vec4` using the matrix ``m``.

        See also: graphene_simd4x4f_vec4_mul()
        """
    def translate(self, pos: Point3D) -> None:
        """
        Adds a translation transformation to ``m`` using the coordinates
        of the given :class:`Graphene.Point3D`.

        This is the equivalent of calling :meth:`Graphene.Matrix.init_translate` and
        then multiplying ``m`` with the translation matrix.
        """
    def transpose(self) -> Matrix:
        """
        Transposes the given matrix.
        """
    def unproject_point3d(self, modelview: Matrix, point: Point3D) -> Point3D:
        """
        Unprojects the given ``point`` using the ``projection`` matrix and
        a ``modelview`` matrix.
        """
    def untransform_bounds(self, r: Rect, bounds: Rect) -> Rect:
        """
        Undoes the transformation on the corners of a :class:`Graphene.Rect` using the
        given matrix, within the given axis aligned rectangular ``bounds``.
        """
    def untransform_point(self, p: Point, bounds: Rect) -> tuple[bool, Point]:
        """
        Undoes the transformation of a :class:`Graphene.Point` using the
        given matrix, within the given axis aligned rectangular ``bounds``.
        """

class Plane:
    """
    A 2D plane that extends infinitely in a 3D volume.

    The contents of the :class:`Graphene.Plane` are private, and should not be
    modified directly.
    """
    gimeta: ClassVar[_GIMeta]
    normal: Vec3
    constant: float
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Plane` structure.

        The contents of the returned structure are undefined.
        """
    def distance(self, point: Point3D) -> float:
        """
        Computes the distance of ``point`` from a :class:`Graphene.Plane`.
        """
    def equal(self, b: Plane) -> bool:
        """
        Checks whether the two given :class:`Graphene.Plane` are equal.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :meth:`Graphene.Plane.alloc`.
        """
    def get_constant(self) -> float:
        """
        Retrieves the distance along the normal vector of the
        given :class:`Graphene.Plane` from the origin.
        """
    def get_normal(self) -> Vec3:
        """
        Retrieves the normal vector pointing towards the origin of the
        given :class:`Graphene.Plane`.
        """
    def init(self, normal: Vec3 | None, constant: float) -> Plane:
        """
        Initializes the given :class:`Graphene.Plane` using the given ``normal`` vector
        and ``constant`` values.
        """
    def init_from_plane(self, src: Plane) -> Plane:
        """
        Initializes the given :class:`Graphene.Plane` using the normal
        vector and constant of another :class:`Graphene.Plane`.
        """
    def init_from_point(self, normal: Vec3, point: Point3D) -> Plane:
        """
        Initializes the given :class:`Graphene.Plane` using the given normal vector
        and an arbitrary co-planar point.
        """
    def init_from_points(self, a: Point3D, b: Point3D, c: Point3D) -> Plane:
        """
        Initializes the given :class:`Graphene.Plane` using the 3 provided co-planar
        points.

        The winding order is counter-clockwise, and determines which direction
        the normal vector will point.
        """
    def init_from_vec4(self, src: Vec4) -> Plane:
        """
        Initializes the given :class:`Graphene.Plane` using the components of
        the given :class:`Graphene.Vec4` vector.
        """
    def negate(self) -> Plane:
        """
        Negates the normal vector and constant of a :class:`Graphene.Plane`, effectively
        mirroring the plane across the origin.
        """
    def normalize(self) -> Plane:
        """
        Normalizes the vector of the given :class:`Graphene.Plane`,
        and adjusts the constant accordingly.
        """
    def transform(self, matrix: Matrix, normal_matrix: Matrix | None = ...) -> Plane:
        """
        Transforms a :class:`Graphene.Plane` ``p`` using the given ``matrix``
        and ``normal_matrix``.

        If ``normal_matrix`` is ``None``, a transformation matrix for the plane
        normal will be computed from ``matrix``. If you are transforming
        multiple planes using the same ``matrix`` it's recommended to compute
        the normal matrix beforehand to avoid incurring in the cost of
        recomputing it every time.
        """

class Point:
    """
    A point with two coordinates.
    """
    gimeta: ClassVar[_GIMeta]
    x: float
    y: float
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Point` structure.

        The coordinates of the returned point are (0, 0).

        It's possible to chain this function with :meth:`Graphene.Point.init`
        or :meth:`Graphene.Point.init_from_point`, e.g.:

        |[<!-- language="C" -->
          :class:`Graphene.Point` *
          point_new (float x, float y)
          {
            return :meth:`Graphene.Point.init` (:meth:`Graphene.Point.alloc`, x, y);
          }

          :class:`Graphene.Point` *
          point_copy (const :class:`Graphene.Point` *p)
          {
            return :meth:`Graphene.Point.init_from_point` (:meth:`Graphene.Point.alloc`, p);
          }
        ]|
        """
    def distance(self, b: Point) -> tuple[float, float, float]:
        """
        Computes the distance between ``a`` and ``b``.
        """
    def equal(self, b: Point) -> bool:
        """
        Checks if the two points ``a`` and ``b`` point to the same
        coordinates.

        This function accounts for floating point fluctuations; if
        you want to control the fuzziness of the match, you can use
        :meth:`Graphene.Point.near` instead.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :meth:`Graphene.Point.alloc`.
        """
    def init(self, x: float, y: float) -> Point:
        """
        Initializes ``p`` to the given ``x`` and ``y`` coordinates.

        It's safe to call this function multiple times.
        """
    def init_from_point(self, src: Point) -> Point:
        """
        Initializes ``p`` with the same coordinates of ``src``.
        """
    def init_from_vec2(self, src: Vec2) -> Point:
        """
        Initializes ``p`` with the coordinates inside the given :class:`Graphene.Vec2`.
        """
    def interpolate(self, b: Point, factor: float) -> Point:
        """
        Linearly interpolates the coordinates of ``a`` and ``b`` using the
        given ``factor``.
        """
    def near(self, b: Point, epsilon: float) -> bool:
        """
        Checks whether the two points ``a`` and ``b`` are within
        the threshold of ``epsilon``.
        """
    def to_vec2(self) -> Vec2:
        """
        Stores the coordinates of the given :class:`Graphene.Point` into a
        :class:`Graphene.Vec2`.
        """
    @staticmethod
    def zero() -> Point:
        """
        Returns a point fixed at (0, 0).
        """

class Point3D:
    """
    A point with three components: X, Y, and Z.
    """
    gimeta: ClassVar[_GIMeta]
    x: float
    y: float
    z: float
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a :class:`Graphene.Point3D` structure.
        """
    def cross(self, b: Point3D) -> Point3D:
        """
        Computes the cross product of the two given :class:`Graphene.Point3D`.
        """
    def distance(self, b: Point3D) -> tuple[float, Vec3]:
        """
        Computes the distance between the two given :class:`Graphene.Point3D`.
        """
    def dot(self, b: Point3D) -> float:
        """
        Computes the dot product of the two given :class:`Graphene.Point3D`.
        """
    def equal(self, b: Point3D) -> bool:
        """
        Checks whether two given points are equal.
        """
    def free(self) -> None:
        """
        Frees the resources allocated via :meth:`Graphene.Point3D.alloc`.
        """
    def init(self, x: float, y: float, z: float) -> Point3D:
        """
        Initializes a :class:`Graphene.Point3D` with the given coordinates.
        """
    def init_from_point(self, src: Point3D) -> Point3D:
        """
        Initializes a :class:`Graphene.Point3D` using the coordinates of
        another :class:`Graphene.Point3D`.
        """
    def init_from_vec3(self, v: Vec3) -> Point3D:
        """
        Initializes a :class:`Graphene.Point3D` using the components
        of a :class:`Graphene.Vec3`.
        """
    def interpolate(self, b: Point3D, factor: float) -> Point3D:
        """
        Linearly interpolates each component of ``a`` and ``b`` using the
        provided ``factor``, and places the result in ``res``.
        """
    def length(self) -> float:
        """
        Computes the length of the vector represented by the
        coordinates of the given :class:`Graphene.Point3D`.
        """
    def near(self, b: Point3D, epsilon: float) -> bool:
        """
        Checks whether the two points are near each other, within
        an ``epsilon`` factor.
        """
    def normalize(self) -> Point3D:
        """
        Computes the normalization of the vector represented by the
        coordinates of the given :class:`Graphene.Point3D`.
        """
    def normalize_viewport(self, viewport: Rect, z_near: float, z_far: float) -> Point3D:
        """
        Normalizes the coordinates of a :class:`Graphene.Point3D` using the
        given viewport and clipping planes.

        The coordinates of the resulting :class:`Graphene.Point3D` will be
        in the [ -1, 1 ] range.
        """
    def scale(self, factor: float) -> Point3D:
        """
        Scales the coordinates of the given :class:`Graphene.Point3D` by
        the given ``factor``.
        """
    def to_vec3(self) -> Vec3:
        """
        Stores the coordinates of a :class:`Graphene.Point3D` into a
        :class:`Graphene.Vec3`.
        """
    @staticmethod
    def zero() -> Point3D:
        """
        Retrieves a constant point with all three coordinates set to 0.
        """

class Quad:
    """
    A 4 vertex quadrilateral, as represented by four :class:`Graphene.Point`.

    The contents of a :class:`Graphene.Quad` are private and should never be
    accessed directly.
    """
    gimeta: ClassVar[_GIMeta]
    points: list[Point]
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Quad` instance.

        The contents of the returned instance are undefined.
        """
    def bounds(self) -> Rect:
        """
        Computes the bounding rectangle of ``q`` and places it into ``r``.
        """
    def contains(self, p: Point) -> bool:
        """
        Checks if the given :class:`Graphene.Quad` contains the given :class:`Graphene.Point`.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :meth:`Graphene.Quad.alloc`
        """
    def get_point(self, index_: int) -> Point:
        """
        Retrieves the point of a :class:`Graphene.Quad` at the given index.
        """
    def init(self, p1: Point, p2: Point, p3: Point, p4: Point) -> Quad:
        """
        Initializes a :class:`Graphene.Quad` with the given points.
        """
    def init_from_points(self, points: list[Point]) -> Quad:
        """
        Initializes a :class:`Graphene.Quad` using an array of points.
        """
    def init_from_rect(self, r: Rect) -> Quad:
        """
        Initializes a :class:`Graphene.Quad` using the four corners of the
        given :class:`Graphene.Rect`.
        """

class Quaternion:
    """
    A quaternion.

    The contents of the :class:`Graphene.Quaternion` structure are private
    and should never be accessed directly.
    """
    gimeta: ClassVar[_GIMeta]
    x: float
    y: float
    z: float
    w: float
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Quaternion`.

        The contents of the returned value are undefined.
        """
    def add(self, b: Quaternion) -> Quaternion:
        """
        Adds two :class:`Graphene.Quaternion` ``a`` and ``b``.
        """
    def dot(self, b: Quaternion) -> float:
        """
        Computes the dot product of two :class:`Graphene.Quaternion`.
        """
    def equal(self, b: Quaternion) -> bool:
        """
        Checks whether the given quaternions are equal.
        """
    def free(self) -> None:
        """
        Releases the resources allocated by :meth:`Graphene.Quaternion.alloc`.
        """
    def init(self, x: float, y: float, z: float, w: float) -> Quaternion:
        """
        Initializes a :class:`Graphene.Quaternion` using the given four values.
        """
    def init_from_angle_vec3(self, angle: float, axis: Vec3) -> Quaternion:
        """
        Initializes a :class:`Graphene.Quaternion` using an ``angle`` on a
        specific ``axis``.
        """
    def init_from_angles(self, deg_x: float, deg_y: float, deg_z: float) -> Quaternion:
        """
        Initializes a :class:`Graphene.Quaternion` using the values of
        the `Euler angles <http://en.wikipedia.org/wiki/Euler_angles>`_
        on each axis.

        See also: :meth:`Graphene.Quaternion.init_from_euler`
        """
    def init_from_euler(self, e: Euler) -> Quaternion:
        """
        Initializes a :class:`Graphene.Quaternion` using the given :class:`Graphene.Euler`.
        """
    def init_from_matrix(self, m: Matrix) -> Quaternion:
        """
        Initializes a :class:`Graphene.Quaternion` using the rotation components
        of a transformation matrix.
        """
    def init_from_quaternion(self, src: Quaternion) -> Quaternion:
        """
        Initializes a :class:`Graphene.Quaternion` with the values from ``src``.
        """
    def init_from_radians(self, rad_x: float, rad_y: float, rad_z: float) -> Quaternion:
        """
        Initializes a :class:`Graphene.Quaternion` using the values of
        the `Euler angles <http://en.wikipedia.org/wiki/Euler_angles>`_
        on each axis.

        See also: :meth:`Graphene.Quaternion.init_from_euler`
        """
    def init_from_vec4(self, src: Vec4) -> Quaternion:
        """
        Initializes a :class:`Graphene.Quaternion` with the values from ``src``.
        """
    def init_identity(self) -> Quaternion:
        """
        Initializes a :class:`Graphene.Quaternion` using the identity
        transformation.
        """
    def invert(self) -> Quaternion:
        """
        Inverts a :class:`Graphene.Quaternion`, and returns the conjugate
        quaternion of ``q``.
        """
    def multiply(self, b: Quaternion) -> Quaternion:
        """
        Multiplies two :class:`Graphene.Quaternion` ``a`` and ``b``.
        """
    def normalize(self) -> Quaternion:
        """
        Normalizes a :class:`Graphene.Quaternion`.
        """
    def scale(self, factor: float) -> Quaternion:
        """
        Scales all the elements of a :class:`Graphene.Quaternion` ``q`` using
        the given scalar factor.
        """
    def slerp(self, b: Quaternion, factor: float) -> Quaternion:
        """
        Interpolates between the two given quaternions using a spherical
        linear interpolation, or `SLERP <http://en.wikipedia.org/wiki/Slerp>`_,
        using the given interpolation ``factor``.
        """
    def to_angle_vec3(self) -> tuple[float, Vec3]:
        """
        Converts a quaternion into an ``angle``, ``axis`` pair.
        """
    def to_angles(self) -> tuple[float, float, float]:
        """
        Converts a :class:`Graphene.Quaternion` to its corresponding rotations
        on the `Euler angles <http://en.wikipedia.org/wiki/Euler_angles>`_
        on each axis.
        """
    def to_matrix(self) -> Matrix:
        """
        Converts a quaternion into a transformation matrix expressing
        the rotation defined by the :class:`Graphene.Quaternion`.
        """
    def to_radians(self) -> tuple[float, float, float]:
        """
        Converts a :class:`Graphene.Quaternion` to its corresponding rotations
        on the `Euler angles <http://en.wikipedia.org/wiki/Euler_angles>`_
        on each axis.
        """
    def to_vec4(self) -> Vec4:
        """
        Copies the components of a :class:`Graphene.Quaternion` into a
        :class:`Graphene.Vec4`.
        """

class Ray:
    """
    A ray emitted from an origin in a given direction.

    The contents of the :class:`Graphene.Ray` structure are private, and should not
    be modified directly.
    """
    gimeta: ClassVar[_GIMeta]
    origin: Vec3
    direction: Vec3
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Ray` structure.

        The contents of the returned structure are undefined.
        """
    def equal(self, b: Ray) -> bool:
        """
        Checks whether the two given :class:`Graphene.Ray` are equal.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :meth:`Graphene.Ray.alloc`.
        """
    def get_closest_point_to_point(self, p: Point3D) -> Point3D:
        """
        Computes the point on the given :class:`Graphene.Ray` that is closest to the
        given point ``p``.
        """
    def get_direction(self) -> Vec3:
        """
        Retrieves the direction of the given :class:`Graphene.Ray`.
        """
    def get_distance_to_plane(self, p: Plane) -> float:
        """
        Computes the distance of the origin of the given :class:`Graphene.Ray` from the
        given plane.

        If the ray does not intersect the plane, this function returns ``INFINITY``.
        """
    def get_distance_to_point(self, p: Point3D) -> float:
        """
        Computes the distance of the closest approach between the
        given :class:`Graphene.Ray` ``r`` and the point ``p``.

        The closest approach to a ray from a point is the distance
        between the point and the projection of the point on the
        ray itself.
        """
    def get_origin(self) -> Point3D:
        """
        Retrieves the origin of the given :class:`Graphene.Ray`.
        """
    def get_position_at(self, t: float) -> Point3D:
        """
        Retrieves the coordinates of a point at the distance ``t`` along the
        given :class:`Graphene.Ray`.
        """
    def init(self, origin: Point3D | None = ..., direction: Vec3 | None = ...) -> Ray:
        """
        Initializes the given :class:`Graphene.Ray` using the given ``origin``
        and ``direction`` values.
        """
    def init_from_ray(self, src: Ray) -> Ray:
        """
        Initializes the given :class:`Graphene.Ray` using the origin and direction
        values of another :class:`Graphene.Ray`.
        """
    def init_from_vec3(self, origin: Vec3 | None = ..., direction: Vec3 | None = ...) -> Ray:
        """
        Initializes the given :class:`Graphene.Ray` using the given vectors.
        """
    def intersect_box(self, b: Box) -> tuple[RayIntersectionKind, float]:
        """
        Intersects the given :class:`Graphene.Ray` ``r`` with the given
        :class:`Graphene.Box` ``b``.
        """
    def intersect_sphere(self, s: Sphere) -> tuple[RayIntersectionKind, float]:
        """
        Intersects the given :class:`Graphene.Ray` ``r`` with the given
        :class:`Graphene.Sphere` ``s``.
        """
    def intersect_triangle(self, t: Triangle) -> tuple[RayIntersectionKind, float]:
        """
        Intersects the given :class:`Graphene.Ray` ``r`` with the given
        :class:`Graphene.Triangle` ``t``.
        """
    def intersects_box(self, b: Box) -> bool:
        """
        Checks whether the given :class:`Graphene.Ray` ``r`` intersects the
        given :class:`Graphene.Box` ``b``.

        See also: :meth:`Graphene.Ray.intersect_box`
        """
    def intersects_sphere(self, s: Sphere) -> bool:
        """
        Checks if the given :class:`Graphene.Ray` ``r`` intersects the
        given :class:`Graphene.Sphere` ``s``.

        See also: :meth:`Graphene.Ray.intersect_sphere`
        """
    def intersects_triangle(self, t: Triangle) -> bool:
        """
        Checks whether the given :class:`Graphene.Ray` ``r`` intersects the
        given :class:`Graphene.Triangle` ``b``.

        See also: :meth:`Graphene.Ray.intersect_triangle`
        """

class Rect:
    """
    The location and size of a rectangle region.

    The width and height of a :class:`Graphene.Rect` can be negative; for instance,
    a :class:`Graphene.Rect` with an origin of [ 0, 0 ] and a size of [ 10, 10 ] is
    equivalent to a :class:`Graphene.Rect` with an origin of [ 10, 10 ] and a size
    of [ -10, -10 ].

    Application code can normalize rectangles using :meth:`Graphene.Rect.normalize`;
    this function will ensure that the width and height of a rectangle are
    positive values. All functions taking a :class:`Graphene.Rect` as an argument
    will internally operate on a normalized copy; all functions returning a
    :class:`Graphene.Rect` will always return a normalized rectangle.
    """
    gimeta: ClassVar[_GIMeta]
    origin: Point
    size: Size
    def contains_point(self, p: Point) -> bool:
        """
        Checks whether a :class:`Graphene.Rect` contains the given coordinates.
        """
    def contains_rect(self, b: Rect) -> bool:
        """
        Checks whether a :class:`Graphene.Rect` fully contains the given
        rectangle.
        """
    def equal(self, b: Rect) -> bool:
        """
        Checks whether the two given rectangle are equal.
        """
    def expand(self, p: Point) -> Rect:
        """
        Expands a :class:`Graphene.Rect` to contain the given :class:`Graphene.Point`.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :func:`Graphene.rect_alloc`.
        """
    def get_area(self) -> float:
        """
        Compute the area of given normalized rectangle.
        """
    def get_bottom_left(self) -> Point:
        """
        Retrieves the coordinates of the bottom-left corner of the given rectangle.
        """
    def get_bottom_right(self) -> Point:
        """
        Retrieves the coordinates of the bottom-right corner of the given rectangle.
        """
    def get_center(self) -> Point:
        """
        Retrieves the coordinates of the center of the given rectangle.
        """
    def get_height(self) -> float:
        """
        Retrieves the normalized height of the given rectangle.
        """
    def get_top_left(self) -> Point:
        """
        Retrieves the coordinates of the top-left corner of the given rectangle.
        """
    def get_top_right(self) -> Point:
        """
        Retrieves the coordinates of the top-right corner of the given rectangle.
        """
    def get_vertices(self) -> list[Vec2]:
        """
        Computes the four vertices of a :class:`Graphene.Rect`.
        """
    def get_width(self) -> float:
        """
        Retrieves the normalized width of the given rectangle.
        """
    def get_x(self) -> float:
        """
        Retrieves the normalized X coordinate of the origin of the given
        rectangle.
        """
    def get_y(self) -> float:
        """
        Retrieves the normalized Y coordinate of the origin of the given
        rectangle.
        """
    def init(self, x: float, y: float, width: float, height: float) -> Rect:
        """
        Initializes the given :class:`Graphene.Rect` with the given values.

        This function will implicitly normalize the :class:`Graphene.Rect`
        before returning.
        """
    def init_from_rect(self, src: Rect) -> Rect:
        """
        Initializes ``r`` using the given ``src`` rectangle.

        This function will implicitly normalize the :class:`Graphene.Rect`
        before returning.
        """
    def inset(self, d_x: float, d_y: float) -> Rect:
        """
        Changes the given rectangle to be smaller, or larger depending on the
        given inset parameters.

        To create an inset rectangle, use positive ``d_x`` or ``d_y`` values; to
        create a larger, encompassing rectangle, use negative ``d_x`` or ``d_y``
        values.

        The origin of the rectangle is offset by ``d_x`` and ``d_y``, while the size
        is adjusted by ``(2 * ``d_x``, 2 * ``d_y``)``. If ``d_x`` and ``d_y`` are positive
        values, the size of the rectangle is decreased; if ``d_x`` and ``d_y`` are
        negative values, the size of the rectangle is increased.

        If the size of the resulting inset rectangle has a negative width or
        height then the size will be set to zero.
        """
    def inset_r(self, d_x: float, d_y: float) -> Rect:
        """
        Changes the given rectangle to be smaller, or larger depending on the
        given inset parameters.

        To create an inset rectangle, use positive ``d_x`` or ``d_y`` values; to
        create a larger, encompassing rectangle, use negative ``d_x`` or ``d_y``
        values.

        The origin of the rectangle is offset by ``d_x`` and ``d_y``, while the size
        is adjusted by ``(2 * ``d_x``, 2 * ``d_y``)``. If ``d_x`` and ``d_y`` are positive
        values, the size of the rectangle is decreased; if ``d_x`` and ``d_y`` are
        negative values, the size of the rectangle is increased.

        If the size of the resulting inset rectangle has a negative width or
        height then the size will be set to zero.
        """
    def interpolate(self, b: Rect, factor: float) -> Rect:
        """
        Linearly interpolates the origin and size of the two given
        rectangles.
        """
    def intersection(self, b: Rect) -> tuple[bool, Rect]:
        """
        Computes the intersection of the two given rectangles.

        ![](rectangle-intersection.png)

        The intersection in the image above is the blue outline.

        If the two rectangles do not intersect, ``res`` will contain
        a degenerate rectangle with origin in (0, 0) and a size of 0.
        """
    def normalize(self) -> Rect:
        """
        Normalizes the passed rectangle.

        This function ensures that the size of the rectangle is made of
        positive values, and that the origin is the top-left corner of
        the rectangle.
        """
    def normalize_r(self) -> Rect:
        """
        Normalizes the passed rectangle.

        This function ensures that the size of the rectangle is made of
        positive values, and that the origin is in the top-left corner
        of the rectangle.
        """
    def offset(self, d_x: float, d_y: float) -> Rect:
        """
        Offsets the origin by ``d_x`` and ``d_y``.

        The size of the rectangle is unchanged.
        """
    def offset_r(self, d_x: float, d_y: float) -> Rect:
        """
        Offsets the origin of the given rectangle by ``d_x`` and ``d_y``.

        The size of the rectangle is left unchanged.
        """
    @deprecated("Deprecated since 1.10.")
    def round(self) -> Rect:
        """
        Rounds the origin and size of the given rectangle to
        their nearest integer values; the rounding is guaranteed
        to be large enough to have an area bigger or equal to the
        original rectangle, but might not fully contain its extents.
        Use :meth:`Graphene.Rect.round_extents` in case you need to round
        to a rectangle that covers fully the original one.

        This function is the equivalent of calling ``floor`` on
        the coordinates of the origin, and ``ceil`` on the size.
        """
    def round_extents(self) -> Rect:
        """
        Rounds the origin of the given rectangle to its nearest
        integer value and and recompute the size so that the
        rectangle is large enough to contain all the conrners
        of the original rectangle.

        This function is the equivalent of calling ``floor`` on
        the coordinates of the origin, and recomputing the size
        calling ``ceil`` on the bottom-right coordinates.

        If you want to be sure that the rounded rectangle
        completely covers the area that was covered by the
        original rectangle — i.e. you want to cover the area
        including all its corners — this function will make sure
        that the size is recomputed taking into account the ceiling
        of the coordinates of the bottom-right corner.
        If the difference between the original coordinates and the
        coordinates of the rounded rectangle is greater than the
        difference between the original size and and the rounded
        size, then the move of the origin would not be compensated
        by a move in the anti-origin, leaving the corners of the
        original rectangle outside the rounded one.
        """
    @deprecated("Deprecated since 1.4.")
    def round_to_pixel(self) -> Rect:
        """
        Rounds the origin and the size of the given rectangle to
        their nearest integer values; the rounding is guaranteed
        to be large enough to contain the original rectangle.
        """
    def scale(self, s_h: float, s_v: float) -> Rect:
        """
        Scales the size and origin of a rectangle horizontaly by ``s_h``,
        and vertically by ``s_v``. The result ``res`` is normalized.
        """
    def union(self, b: Rect) -> Rect:
        """
        Computes the union of the two given rectangles.

        ![](rectangle-union.png)

        The union in the image above is the blue outline.
        """
    @staticmethod
    def alloc() -> Rect:
        """
        Allocates a new :class:`Graphene.Rect`.

        The contents of the returned rectangle are undefined.
        """
    @staticmethod
    def zero() -> Rect:
        """
        Returns a degenerate rectangle with origin fixed at (0, 0) and
        a size of 0, 0.
        """

class Simd4F:
    gimeta: ClassVar[_GIMeta]
    x: float
    y: float
    z: float
    w: float

class Simd4X4F:
    gimeta: ClassVar[_GIMeta]
    x: Simd4F
    y: Simd4F
    z: Simd4F
    w: Simd4F

class Size:
    """
    A size.
    """
    gimeta: ClassVar[_GIMeta]
    width: float
    height: float
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Size`.

        The contents of the returned value are undefined.
        """
    def equal(self, b: Size) -> bool:
        """
        Checks whether the two give :class:`Graphene.Size` are equal.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :meth:`Graphene.Size.alloc`.
        """
    def init(self, width: float, height: float) -> Size:
        """
        Initializes a :class:`Graphene.Size` using the given ``width`` and ``height``.
        """
    def init_from_size(self, src: Size) -> Size:
        """
        Initializes a :class:`Graphene.Size` using the width and height of
        the given ``src``.
        """
    def interpolate(self, b: Size, factor: float) -> Size:
        """
        Linearly interpolates the two given :class:`Graphene.Size` using the given
        interpolation ``factor``.
        """
    def scale(self, factor: float) -> Size:
        """
        Scales the components of a :class:`Graphene.Size` using the given ``factor``.
        """
    @staticmethod
    def zero() -> Size:
        """
        A constant pointer to a zero :class:`Graphene.Size`, useful for
        equality checks and interpolations.
        """

class Sphere:
    """
    A sphere, represented by its center and radius.
    """
    gimeta: ClassVar[_GIMeta]
    center: Vec3
    radius: float
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Sphere`.

        The contents of the newly allocated structure are undefined.
        """
    def contains_point(self, point: Point3D) -> bool:
        """
        Checks whether the given ``point`` is contained in the volume
        of a :class:`Graphene.Sphere`.
        """
    def distance(self, point: Point3D) -> float:
        """
        Computes the distance of the given ``point`` from the surface of
        a :class:`Graphene.Sphere`.
        """
    def equal(self, b: Sphere) -> bool:
        """
        Checks whether two :class:`Graphene.Sphere` are equal.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :meth:`Graphene.Sphere.alloc`.
        """
    def get_bounding_box(self) -> Box:
        """
        Computes the bounding box capable of containing the
        given :class:`Graphene.Sphere`.
        """
    def get_center(self) -> Point3D:
        """
        Retrieves the coordinates of the center of a :class:`Graphene.Sphere`.
        """
    def get_radius(self) -> float:
        """
        Retrieves the radius of a :class:`Graphene.Sphere`.
        """
    def init(self, center: Point3D | None, radius: float) -> Sphere:
        """
        Initializes the given :class:`Graphene.Sphere` with the given ``center`` and ``radius``.
        """
    def init_from_points(self, points: list[Point3D], center: Point3D | None = ...) -> Sphere:
        """
        Initializes the given :class:`Graphene.Sphere` using the given array
        of 3D coordinates so that the sphere includes them.

        The center of the sphere can either be specified, or will be center
        of the 3D volume that encompasses all ``points``.
        """
    def init_from_vectors(self, vectors: list[Vec3], center: Point3D | None = ...) -> Sphere:
        """
        Initializes the given :class:`Graphene.Sphere` using the given array
        of 3D coordinates so that the sphere includes them.

        The center of the sphere can either be specified, or will be center
        of the 3D volume that encompasses all ``vectors``.
        """
    def is_empty(self) -> bool:
        """
        Checks whether the sphere has a zero radius.
        """
    def translate(self, point: Point3D) -> Sphere:
        """
        Translates the center of the given :class:`Graphene.Sphere` using the ``point``
        coordinates as the delta of the translation.
        """

class Triangle:
    """
    A triangle.
    """
    gimeta: ClassVar[_GIMeta]
    a: Vec3
    b: Vec3
    c: Vec3
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Triangle`.

        The contents of the returned structure are undefined.
        """
    def contains_point(self, p: Point3D) -> bool:
        """
        Checks whether the given triangle ``t`` contains the point ``p``.
        """
    def equal(self, b: Triangle) -> bool:
        """
        Checks whether the two given :class:`Graphene.Triangle` are equal.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by :meth:`Graphene.Triangle.alloc`.
        """
    def get_area(self) -> float:
        """
        Computes the area of the given :class:`Graphene.Triangle`.
        """
    def get_barycoords(self, p: Point3D | None = ...) -> tuple[bool, Vec2]:
        """
        Computes the `barycentric coordinates <http://en.wikipedia.org/wiki/Barycentric_coordinate_system>`_
        of the given point ``p``.

        The point ``p`` must lie on the same plane as the triangle ``t``; if the
        point is not coplanar, the result of this function is undefined.

        If we place the origin in the coordinates of the triangle's A point,
        the barycentric coordinates are ``u``, which is on the AC vector; and ``v``
        which is on the AB vector:

        ![](triangle-barycentric.png)

        The returned :class:`Graphene.Vec2` contains the following values, in order:

         - ``res.x = u``
         - ``res.y = v``
        """
    def get_bounding_box(self) -> Box:
        """
        Computes the bounding box of the given :class:`Graphene.Triangle`.
        """
    def get_midpoint(self) -> Point3D:
        """
        Computes the coordinates of the midpoint of the given :class:`Graphene.Triangle`.

        The midpoint G is the `centroid <https://en.wikipedia.org/wiki/Centroid#Triangle_centroid>`_
        of the triangle, i.e. the intersection of its medians.
        """
    def get_normal(self) -> Vec3:
        """
        Computes the normal vector of the given :class:`Graphene.Triangle`.
        """
    def get_plane(self) -> Plane:
        """
        Computes the plane based on the vertices of the given :class:`Graphene.Triangle`.
        """
    def get_points(self) -> tuple[Point3D, Point3D, Point3D]:
        """
        Retrieves the three vertices of the given :class:`Graphene.Triangle` and returns
        their coordinates as :class:`Graphene.Point3D`.
        """
    def get_uv(self, p: Point3D | None, uv_a: Vec2, uv_b: Vec2, uv_c: Vec2) -> tuple[bool, Vec2]:
        """
        Computes the UV coordinates of the given point ``p``.

        The point ``p`` must lie on the same plane as the triangle ``t``; if the point
        is not coplanar, the result of this function is undefined. If ``p`` is ``None``,
        the point will be set in (0, 0, 0).

        The UV coordinates will be placed in the ``res`` vector:

         - ``res.x = u``
         - ``res.y = v``

        See also: :meth:`Graphene.Triangle.get_barycoords`
        """
    def get_vertices(self) -> tuple[Vec3, Vec3, Vec3]:
        """
        Retrieves the three vertices of the given :class:`Graphene.Triangle`.
        """
    def init_from_float(self, a: list[float], b: list[float], c: list[float]) -> Triangle:
        """
        Initializes a :class:`Graphene.Triangle` using the three given arrays
        of floating point values, each representing the coordinates of
        a point in 3D space.
        """
    def init_from_point3d(self, a: Point3D | None = ..., b: Point3D | None = ..., c: Point3D | None = ...) -> Triangle:
        """
        Initializes a :class:`Graphene.Triangle` using the three given 3D points.
        """
    def init_from_vec3(self, a: Vec3 | None = ..., b: Vec3 | None = ..., c: Vec3 | None = ...) -> Triangle:
        """
        Initializes a :class:`Graphene.Triangle` using the three given vectors.
        """

class Vec2:
    """
    A structure capable of holding a vector with two dimensions, x and y.

    The contents of the :class:`Graphene.Vec2` structure are private and should
    never be accessed directly.
    """
    gimeta: ClassVar[_GIMeta]
    value: Simd4F
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Vec2` structure.

        The contents of the returned structure are undefined.

        Use :meth:`Graphene.Vec2.init` to initialize the vector.
        """
    def add(self, b: Vec2) -> Vec2:
        """
        Adds each component of the two passed vectors and places
        each result into the components of ``res``.
        """
    def divide(self, b: Vec2) -> Vec2:
        """
        Divides each component of the first operand ``a`` by the corresponding
        component of the second operand ``b``, and places the results into the
        vector ``res``.
        """
    def dot(self, b: Vec2) -> float:
        """
        Computes the dot product of the two given vectors.
        """
    def equal(self, v2: Vec2) -> bool:
        """
        Checks whether the two given :class:`Graphene.Vec2` are equal.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by ``v``
        """
    def get_x(self) -> float:
        """
        Retrieves the X component of the :class:`Graphene.Vec2`.
        """
    def get_y(self) -> float:
        """
        Retrieves the Y component of the :class:`Graphene.Vec2`.
        """
    def init(self, x: float, y: float) -> Vec2:
        """
        Initializes a :class:`Graphene.Vec2` using the given values.

        This function can be called multiple times.
        """
    def init_from_float(self, src: list[float]) -> Vec2:
        """
        Initializes ``v`` with the contents of the given array.
        """
    def init_from_vec2(self, src: Vec2) -> Vec2:
        """
        Copies the contents of ``src`` into ``v``.
        """
    def interpolate(self, v2: Vec2, factor: float) -> Vec2:
        """
        Linearly interpolates ``v1`` and ``v2`` using the given ``factor``.
        """
    def length(self) -> float:
        """
        Computes the length of the given vector.
        """
    def max(self, b: Vec2) -> Vec2:
        """
        Compares the two given vectors and places the maximum
        values of each component into ``res``.
        """
    def min(self, b: Vec2) -> Vec2:
        """
        Compares the two given vectors and places the minimum
        values of each component into ``res``.
        """
    def multiply(self, b: Vec2) -> Vec2:
        """
        Multiplies each component of the two passed vectors and places
        each result into the components of ``res``.
        """
    def near(self, v2: Vec2, epsilon: float) -> bool:
        """
        Compares the two given :class:`Graphene.Vec2` vectors and checks
        whether their values are within the given ``epsilon``.
        """
    def negate(self) -> Vec2:
        """
        Negates the given :class:`Graphene.Vec2`.
        """
    def normalize(self) -> Vec2:
        """
        Computes the normalized vector for the given vector ``v``.
        """
    def scale(self, factor: float) -> Vec2:
        """
        Multiplies all components of the given vector with the given scalar ``factor``.
        """
    def subtract(self, b: Vec2) -> Vec2:
        """
        Subtracts from each component of the first operand ``a`` the
        corresponding component of the second operand ``b`` and places
        each result into the components of ``res``.
        """
    def to_float(self) -> list[float]:
        """
        Stores the components of ``v`` into an array.
        """
    @staticmethod
    def one() -> Vec2:
        """
        Retrieves a constant vector with (1, 1) components.
        """
    @staticmethod
    def x_axis() -> Vec2:
        """
        Retrieves a constant vector with (1, 0) components.
        """
    @staticmethod
    def y_axis() -> Vec2:
        """
        Retrieves a constant vector with (0, 1) components.
        """
    @staticmethod
    def zero() -> Vec2:
        """
        Retrieves a constant vector with (0, 0) components.
        """

class Vec3:
    """
    A structure capable of holding a vector with three dimensions: x, y, and z.

    The contents of the :class:`Graphene.Vec3` structure are private and should
    never be accessed directly.
    """
    gimeta: ClassVar[_GIMeta]
    value: Simd4F
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Vec3` structure.

        The contents of the returned structure are undefined.

        Use :meth:`Graphene.Vec3.init` to initialize the vector.
        """
    def add(self, b: Vec3) -> Vec3:
        """
        Adds each component of the two given vectors.
        """
    def cross(self, b: Vec3) -> Vec3:
        """
        Computes the cross product of the two given vectors.
        """
    def divide(self, b: Vec3) -> Vec3:
        """
        Divides each component of the first operand ``a`` by the corresponding
        component of the second operand ``b``, and places the results into the
        vector ``res``.
        """
    def dot(self, b: Vec3) -> float:
        """
        Computes the dot product of the two given vectors.
        """
    def equal(self, v2: Vec3) -> bool:
        """
        Checks whether the two given :class:`Graphene.Vec3` are equal.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by ``v``
        """
    def get_x(self) -> float:
        """
        Retrieves the first component of the given vector ``v``.
        """
    def get_xy(self) -> Vec2:
        """
        Creates a :class:`Graphene.Vec2` that contains the first and second
        components of the given :class:`Graphene.Vec3`.
        """
    def get_xy0(self) -> Vec3:
        """
        Creates a :class:`Graphene.Vec3` that contains the first two components of
        the given :class:`Graphene.Vec3`, and the third component set to 0.
        """
    def get_xyz0(self) -> Vec4:
        """
        Converts a :class:`Graphene.Vec3` in a :class:`Graphene.Vec4` using 0.0
        as the value for the fourth component of the resulting vector.
        """
    def get_xyz1(self) -> Vec4:
        """
        Converts a :class:`Graphene.Vec3` in a :class:`Graphene.Vec4` using 1.0
        as the value for the fourth component of the resulting vector.
        """
    def get_xyzw(self, w: float) -> Vec4:
        """
        Converts a :class:`Graphene.Vec3` in a :class:`Graphene.Vec4` using ``w`` as
        the value of the fourth component of the resulting vector.
        """
    def get_y(self) -> float:
        """
        Retrieves the second component of the given vector ``v``.
        """
    def get_z(self) -> float:
        """
        Retrieves the third component of the given vector ``v``.
        """
    def init(self, x: float, y: float, z: float) -> Vec3:
        """
        Initializes a :class:`Graphene.Vec3` using the given values.

        This function can be called multiple times.
        """
    def init_from_float(self, src: list[float]) -> Vec3:
        """
        Initializes a :class:`Graphene.Vec3` with the values from an array.
        """
    def init_from_vec3(self, src: Vec3) -> Vec3:
        """
        Initializes a :class:`Graphene.Vec3` with the values of another
        :class:`Graphene.Vec3`.
        """
    def interpolate(self, v2: Vec3, factor: float) -> Vec3:
        """
        Linearly interpolates ``v1`` and ``v2`` using the given ``factor``.
        """
    def length(self) -> float:
        """
        Retrieves the length of the given vector ``v``.
        """
    def max(self, b: Vec3) -> Vec3:
        """
        Compares each component of the two given vectors and creates a
        vector that contains the maximum values.
        """
    def min(self, b: Vec3) -> Vec3:
        """
        Compares each component of the two given vectors and creates a
        vector that contains the minimum values.
        """
    def multiply(self, b: Vec3) -> Vec3:
        """
        Multiplies each component of the two given vectors.
        """
    def near(self, v2: Vec3, epsilon: float) -> bool:
        """
        Compares the two given :class:`Graphene.Vec3` vectors and checks
        whether their values are within the given ``epsilon``.
        """
    def negate(self) -> Vec3:
        """
        Negates the given :class:`Graphene.Vec3`.
        """
    def normalize(self) -> Vec3:
        """
        Normalizes the given :class:`Graphene.Vec3`.
        """
    def scale(self, factor: float) -> Vec3:
        """
        Multiplies all components of the given vector with the given scalar ``factor``.
        """
    def subtract(self, b: Vec3) -> Vec3:
        """
        Subtracts from each component of the first operand ``a`` the
        corresponding component of the second operand ``b`` and places
        each result into the components of ``res``.
        """
    def to_float(self) -> list[float]:
        """
        Copies the components of a :class:`Graphene.Vec3` into the given array.
        """
    @staticmethod
    def one() -> Vec3:
        """
        Provides a constant pointer to a vector with three components,
        all sets to 1.
        """
    @staticmethod
    def x_axis() -> Vec3:
        """
        Provides a constant pointer to a vector with three components
        with values set to (1, 0, 0).
        """
    @staticmethod
    def y_axis() -> Vec3:
        """
        Provides a constant pointer to a vector with three components
        with values set to (0, 1, 0).
        """
    @staticmethod
    def z_axis() -> Vec3:
        """
        Provides a constant pointer to a vector with three components
        with values set to (0, 0, 1).
        """
    @staticmethod
    def zero() -> Vec3:
        """
        Provides a constant pointer to a vector with three components,
        all sets to 0.
        """

class Vec4:
    """
    A structure capable of holding a vector with four dimensions: x, y, z, and w.

    The contents of the :class:`Graphene.Vec4` structure are private and should
    never be accessed directly.
    """
    gimeta: ClassVar[_GIMeta]
    value: Simd4F
    @classmethod
    def alloc(cls) -> Self:
        """
        Allocates a new :class:`Graphene.Vec4` structure.

        The contents of the returned structure are undefined.

        Use :meth:`Graphene.Vec4.init` to initialize the vector.
        """
    def add(self, b: Vec4) -> Vec4:
        """
        Adds each component of the two given vectors.
        """
    def divide(self, b: Vec4) -> Vec4:
        """
        Divides each component of the first operand ``a`` by the corresponding
        component of the second operand ``b``, and places the results into the
        vector ``res``.
        """
    def dot(self, b: Vec4) -> float:
        """
        Computes the dot product of the two given vectors.
        """
    def equal(self, v2: Vec4) -> bool:
        """
        Checks whether the two given :class:`Graphene.Vec4` are equal.
        """
    def free(self) -> None:
        """
        Frees the resources allocated by ``v``
        """
    def get_w(self) -> float:
        """
        Retrieves the value of the fourth component of the given :class:`Graphene.Vec4`.
        """
    def get_x(self) -> float:
        """
        Retrieves the value of the first component of the given :class:`Graphene.Vec4`.
        """
    def get_xy(self) -> Vec2:
        """
        Creates a :class:`Graphene.Vec2` that contains the first two components
        of the given :class:`Graphene.Vec4`.
        """
    def get_xyz(self) -> Vec3:
        """
        Creates a :class:`Graphene.Vec3` that contains the first three components
        of the given :class:`Graphene.Vec4`.
        """
    def get_y(self) -> float:
        """
        Retrieves the value of the second component of the given :class:`Graphene.Vec4`.
        """
    def get_z(self) -> float:
        """
        Retrieves the value of the third component of the given :class:`Graphene.Vec4`.
        """
    def init(self, x: float, y: float, z: float, w: float) -> Vec4:
        """
        Initializes a :class:`Graphene.Vec4` using the given values.

        This function can be called multiple times.
        """
    def init_from_float(self, src: list[float]) -> Vec4:
        """
        Initializes a :class:`Graphene.Vec4` with the values inside the given array.
        """
    def init_from_vec2(self, src: Vec2, z: float, w: float) -> Vec4:
        """
        Initializes a :class:`Graphene.Vec4` using the components of a
        :class:`Graphene.Vec2` and the values of ``z`` and ``w``.
        """
    def init_from_vec3(self, src: Vec3, w: float) -> Vec4:
        """
        Initializes a :class:`Graphene.Vec4` using the components of a
        :class:`Graphene.Vec3` and the value of ``w``.
        """
    def init_from_vec4(self, src: Vec4) -> Vec4:
        """
        Initializes a :class:`Graphene.Vec4` using the components of
        another :class:`Graphene.Vec4`.
        """
    def interpolate(self, v2: Vec4, factor: float) -> Vec4:
        """
        Linearly interpolates ``v1`` and ``v2`` using the given ``factor``.
        """
    def length(self) -> float:
        """
        Computes the length of the given :class:`Graphene.Vec4`.
        """
    def max(self, b: Vec4) -> Vec4:
        """
        Compares each component of the two given vectors and creates a
        vector that contains the maximum values.
        """
    def min(self, b: Vec4) -> Vec4:
        """
        Compares each component of the two given vectors and creates a
        vector that contains the minimum values.
        """
    def multiply(self, b: Vec4) -> Vec4:
        """
        Multiplies each component of the two given vectors.
        """
    def near(self, v2: Vec4, epsilon: float) -> bool:
        """
        Compares the two given :class:`Graphene.Vec4` vectors and checks
        whether their values are within the given ``epsilon``.
        """
    def negate(self) -> Vec4:
        """
        Negates the given :class:`Graphene.Vec4`.
        """
    def normalize(self) -> Vec4:
        """
        Normalizes the given :class:`Graphene.Vec4`.
        """
    def scale(self, factor: float) -> Vec4:
        """
        Multiplies all components of the given vector with the given scalar ``factor``.
        """
    def subtract(self, b: Vec4) -> Vec4:
        """
        Subtracts from each component of the first operand ``a`` the
        corresponding component of the second operand ``b`` and places
        each result into the components of ``res``.
        """
    def to_float(self) -> list[float]:
        """
        Stores the components of the given :class:`Graphene.Vec4` into an array
        of floating point values.
        """
    @staticmethod
    def one() -> Vec4:
        """
        Retrieves a pointer to a :class:`Graphene.Vec4` with all its
        components set to 1.
        """
    @staticmethod
    def w_axis() -> Vec4:
        """
        Retrieves a pointer to a :class:`Graphene.Vec4` with its
        components set to (0, 0, 0, 1).
        """
    @staticmethod
    def x_axis() -> Vec4:
        """
        Retrieves a pointer to a :class:`Graphene.Vec4` with its
        components set to (1, 0, 0, 0).
        """
    @staticmethod
    def y_axis() -> Vec4:
        """
        Retrieves a pointer to a :class:`Graphene.Vec4` with its
        components set to (0, 1, 0, 0).
        """
    @staticmethod
    def z_axis() -> Vec4:
        """
        Retrieves a pointer to a :class:`Graphene.Vec4` with its
        components set to (0, 0, 1, 0).
        """
    @staticmethod
    def zero() -> Vec4:
        """
        Retrieves a pointer to a :class:`Graphene.Vec4` with all its
        components set to 0.
        """

PI: float
PI_2: float
VEC2_LEN: int
"""
Evaluates to the number of components of a :class:`Graphene.Vec2`.

This symbol is useful when declaring a C array of floating
point values to be used with :meth:`Graphene.Vec2.init_from_float` and
:meth:`Graphene.Vec2.to_float`, e.g.

|[
  float v[GRAPHENE_VEC2_LEN];

  // vec is defined elsewhere
  :meth:`Graphene.Vec2.to_float` (&vec, v);

  for (int i = 0; i < GRAPHENE_VEC2_LEN; i++)
    fprintf (stdout, "component ``d``: ``g``\\n", i, v[i]);
]|
"""
VEC3_LEN: int
"""
Evaluates to the number of components of a :class:`Graphene.Vec3`.

This symbol is useful when declaring a C array of floating
point values to be used with :meth:`Graphene.Vec3.init_from_float` and
:meth:`Graphene.Vec3.to_float`, e.g.

|[
  float v[GRAPHENE_VEC3_LEN];

  // vec is defined elsewhere
  :meth:`Graphene.Vec3.to_float` (&vec, v);

  for (int i = 0; i < GRAPHENE_VEC2_LEN; i++)
    fprintf (stdout, "component ``d``: ``g``\\n", i, v[i]);
]|
"""
VEC4_LEN: int
"""
Evaluates to the number of components of a :class:`Graphene.Vec4`.

This symbol is useful when declaring a C array of floating
point values to be used with :meth:`Graphene.Vec4.init_from_float` and
:meth:`Graphene.Vec4.to_float`, e.g.

|[
  float v[GRAPHENE_VEC4_LEN];

  // vec is defined elsewhere
  :meth:`Graphene.Vec4.to_float` (&vec, v);

  for (int i = 0; i < GRAPHENE_VEC4_LEN; i++)
    fprintf (stdout, "component ``d``: ``g``\\n", i, v[i]);
]|
"""
def box_empty() -> Box:
    """
    A degenerate :class:`Graphene.Box` that can only be expanded.

    The returned value is owned by Graphene and should not be modified or freed.
    """
def box_infinite() -> Box:
    """
    A degenerate :class:`Graphene.Box` that cannot be expanded.

    The returned value is owned by Graphene and should not be modified or freed.
    """
def box_minus_one() -> Box:
    """
    A :class:`Graphene.Box` with the minimum vertex set at (-1, -1, -1) and the
    maximum vertex set at (0, 0, 0).

    The returned value is owned by Graphene and should not be modified or freed.
    """
def box_one() -> Box:
    """
    A :class:`Graphene.Box` with the minimum vertex set at (0, 0, 0) and the
    maximum vertex set at (1, 1, 1).

    The returned value is owned by Graphene and should not be modified or freed.
    """
def box_one_minus_one() -> Box:
    """
    A :class:`Graphene.Box` with the minimum vertex set at (-1, -1, -1) and the
    maximum vertex set at (1, 1, 1).

    The returned value is owned by Graphene and should not be modified or freed.
    """
def box_zero() -> Box:
    """
    A :class:`Graphene.Box` with both the minimum and maximum vertices set at (0, 0, 0).

    The returned value is owned by Graphene and should not be modified or freed.
    """
def point3d_zero() -> Point3D:
    """
    Retrieves a constant point with all three coordinates set to 0.
    """
def point_zero() -> Point:
    """
    Returns a point fixed at (0, 0).
    """
def rect_alloc() -> Rect:
    """
    Allocates a new :class:`Graphene.Rect`.

    The contents of the returned rectangle are undefined.
    """
def rect_zero() -> Rect:
    """
    Returns a degenerate rectangle with origin fixed at (0, 0) and
    a size of 0, 0.
    """
def size_zero() -> Size:
    """
    A constant pointer to a zero :class:`Graphene.Size`, useful for
    equality checks and interpolations.
    """
def vec2_one() -> Vec2:
    """
    Retrieves a constant vector with (1, 1) components.
    """
def vec2_x_axis() -> Vec2:
    """
    Retrieves a constant vector with (1, 0) components.
    """
def vec2_y_axis() -> Vec2:
    """
    Retrieves a constant vector with (0, 1) components.
    """
def vec2_zero() -> Vec2:
    """
    Retrieves a constant vector with (0, 0) components.
    """
def vec3_one() -> Vec3:
    """
    Provides a constant pointer to a vector with three components,
    all sets to 1.
    """
def vec3_x_axis() -> Vec3:
    """
    Provides a constant pointer to a vector with three components
    with values set to (1, 0, 0).
    """
def vec3_y_axis() -> Vec3:
    """
    Provides a constant pointer to a vector with three components
    with values set to (0, 1, 0).
    """
def vec3_z_axis() -> Vec3:
    """
    Provides a constant pointer to a vector with three components
    with values set to (0, 0, 1).
    """
def vec3_zero() -> Vec3:
    """
    Provides a constant pointer to a vector with three components,
    all sets to 0.
    """
def vec4_one() -> Vec4:
    """
    Retrieves a pointer to a :class:`Graphene.Vec4` with all its
    components set to 1.
    """
def vec4_w_axis() -> Vec4:
    """
    Retrieves a pointer to a :class:`Graphene.Vec4` with its
    components set to (0, 0, 0, 1).
    """
def vec4_x_axis() -> Vec4:
    """
    Retrieves a pointer to a :class:`Graphene.Vec4` with its
    components set to (1, 0, 0, 0).
    """
def vec4_y_axis() -> Vec4:
    """
    Retrieves a pointer to a :class:`Graphene.Vec4` with its
    components set to (0, 1, 0, 0).
    """
def vec4_z_axis() -> Vec4:
    """
    Retrieves a pointer to a :class:`Graphene.Vec4` with its
    components set to (0, 0, 1, 0).
    """
def vec4_zero() -> Vec4:
    """
    Retrieves a pointer to a :class:`Graphene.Vec4` with all its
    components set to 0.
    """
