# Auto-generated by ginext-stubgen from GstApp-1.0.gir.
# Do not edit by hand.
# mypy: disable-error-code="override,type-arg,misc,valid-type"
from __future__ import annotations

from collections.abc import Iterator
from typing_extensions import deprecated
from contextlib import AbstractContextManager
from typing import Any, Awaitable, Callable, ClassVar, Concatenate, Generic, Final, Literal, NamedTuple, ParamSpec as _ParamSpec, Self, TypeVar, override, overload
from enum import IntEnum, IntFlag
from ginext import Gst
from ginext import GstBase
from ginext.overlay.registrar import OverlayRegistrar as _OverlayRegistrar
from ginext.private import GIMeta as _GIMeta

overlay: _OverlayRegistrar
__version__: tuple[int, ...]
def __getattr__(name: str) -> Any: ...

_SigO = TypeVar('_SigO')
_SigP = _ParamSpec('_SigP')
_SigR = TypeVar('_SigR')

class SignalConnection:
    handler_id: int
    signal_name: str
    source: Any
    callback: Callable[..., Any]
    after: bool
    once: bool
    owner: Any
    is_connected: bool
    def disconnect(self) -> None: ...
    def blocked(self) -> AbstractContextManager[SignalConnection]: ...

class Signal(Generic[_SigO, _SigP, _SigR]):
    def __call__(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...
    def connect(self, handler: Callable[Concatenate[_SigO, _SigP], _SigR], *, after: bool = ..., once: bool = ..., owner: Any = ...) -> SignalConnection: ...
    def connect_after(self, handler: Callable[Concatenate[_SigO, _SigP], _SigR]) -> SignalConnection: ...
    def emit(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...
    def disconnect(self, connection: SignalConnection) -> None: ...
class SignalMethod(Signal[_SigO, _SigP, _SigR]):
    def __call__(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...

class DetailedSignal(Signal[_SigO, _SigP, _SigR]):
    def __call__(self, detail: str | GObject.Property) -> 'Signal[_SigO, _SigP, _SigR]': ...

class AppLeakyType(IntEnum):
    NONE = 0
    UPSTREAM = 1
    DOWNSTREAM = 2

class AppStreamType(IntEnum):
    STREAM = 0
    SEEKABLE = 1
    RANDOM_ACCESS = 2

AppSinkEosCallback = Callable[[AppSink], None]
AppSinkNewEventCallback = Callable[[AppSink], bool]
AppSinkNewPrerollCallback = Callable[[AppSink], Gst.FlowReturn | int]
AppSinkNewSampleCallback = Callable[[AppSink], Gst.FlowReturn | int]
AppSinkProposeAllocationCallback = Callable[[AppSink, Gst.Query], bool]
AppSrcEnoughDataCallback = Callable[[AppSrc], None]
AppSrcNeedDataCallback = Callable[[AppSrc, int], None]
AppSrcSeekDataCallback = Callable[[AppSrc, int], bool]
class AppSink(GstBase.BaseSink, Gst.URIHandler):
    """
    Appsink is a sink plugin that supports many different methods for making
    the application get a handle on the GStreamer data in a pipeline. Unlike
    most GStreamer elements, Appsink provides external API functions.

    appsink can be used by linking to the gstappsink.h header file to access the
    methods or by using the appsink action signals and properties.

    The normal way of retrieving samples from appsink is by using the
    :meth:`GstApp.AppSink.pull_sample` and :meth:`GstApp.AppSink.pull_preroll` methods.
    These methods block until a sample becomes available in the sink or when the
    sink is shut down or reaches EOS. There are also timed variants of these
    methods, :meth:`GstApp.AppSink.try_pull_sample` and :meth:`GstApp.AppSink.try_pull_preroll`,
    which accept a timeout parameter to limit the amount of time to wait.

    Appsink will internally use a queue to collect buffers from the streaming
    thread. If the application is not pulling samples fast enough, this queue
    will consume a lot of memory over time. The "max-buffers", "max-time" and "max-bytes"
    properties can be used to limit the queue size. The "leaky-type" property controls whether the
    streaming thread blocks or if older buffers are dropped when the maximum
    queue size is reached. Note that blocking the streaming thread can negatively
    affect real-time performance and should be avoided.

    If a blocking behaviour is not desirable, setting the "emit-signals" property
    to ``True`` will make appsink emit the "new-sample" and "new-preroll" signals
    when a sample can be pulled without blocking.

    The "caps" property on appsink can be used to control the formats that
    appsink can receive. This property can contain non-fixed caps, the format of
    the pulled samples can be obtained by getting the sample caps.

    If one of the pull-preroll or pull-sample methods return ``None``, the appsink
    is stopped or in the EOS state. You can check for the EOS state with the
    "eos" property or with the :meth:`GstApp.AppSink.is_eos` method.

    The eos signal can also be used to be informed when the EOS state is reached
    to avoid polling.
    """
    gimeta: ClassVar[_GIMeta]
    buffer_list: bool
    caps: Gst.Caps
    current_level_buffers: int
    current_level_bytes: int
    current_level_time: int
    @deprecated("Deprecated since 1.28.")
    @property
    def drop(self) -> bool: ...
    dropped: int
    emit_signals: bool
    eos: bool
    in_: int
    leaky_type: AppLeakyType | int
    max_buffers: int
    max_bytes: int
    max_time: int
    out: int
    silent: bool
    wait_on_eos: bool
    def __init__(self, *, buffer_list: bool = ..., caps: Gst.Caps = ..., drop: bool = ..., emit_signals: bool = ..., leaky_type: AppLeakyType | int = ..., max_buffers: int = ..., max_bytes: int = ..., max_time: int = ..., silent: bool = ..., wait_on_eos: bool = ..., **kwargs: Any) -> None: ...
    def get_buffer_list_support(self) -> bool:
        """
        Check if ``appsink`` supports buffer lists.
        """
    def get_caps(self) -> Gst.Caps | None:
        """
        Get the configured caps on ``appsink``.
        """
    def get_current_level_buffers(self) -> int:
        """
        Get the number of currently queued buffers inside ``appsink``.
        """
    def get_current_level_bytes(self) -> int:
        """
        Get the number of currently queued bytes inside ``appsink``.
        """
    def get_current_level_time(self) -> Gst.ClockTime:
        """
        Get the amount of currently queued time inside ``appsink``.
        """
    @deprecated("Deprecated since 1.28.")
    def get_drop(self) -> bool:
        """
        Check if ``appsink`` will drop old buffers when the maximum amount of queued
        data is reached (meaning max buffers, time or bytes limit, whichever is hit first).
        """
    def get_emit_signals(self) -> bool:
        """
        Check if appsink will emit the "new-preroll" and "new-sample" signals.
        """
    def get_leaky_type(self) -> AppLeakyType:
        """
        Returns the currently set :class:`GstApp.AppLeakyType`. See :meth:`GstApp.AppSink.set_leaky_type`
        for more details.
        """
    def get_max_buffers(self) -> int:
        """
        Get the maximum amount of buffers that can be queued in ``appsink``.
        """
    def get_max_bytes(self) -> int:
        """
        Get the maximum total size, in bytes, that can be queued in ``appsink``.
        """
    def get_max_time(self) -> Gst.ClockTime:
        """
        Get the maximum total duration that can be queued in ``appsink``.
        """
    def get_wait_on_eos(self) -> bool:
        """
        Check if ``appsink`` will wait for all buffers to be consumed when an EOS is
        received.
        """
    def is_eos(self) -> bool:
        """
        Check if ``appsink`` is EOS, which is when no more samples can be pulled because
        an EOS event was received.

        This function also returns ``True`` when the appsink is not in the PAUSED or
        PLAYING state.
        """
    def pull_object(self) -> Gst.MiniObject | None:
        """
        This function blocks until a sample or an event becomes available or the appsink
        element is set to the READY/NULL state.

        This function will only return samples when the appsink is in the PLAYING
        state. All rendered buffers and events will be put in a queue so that the application
        can pull them at its own rate. Note that when the application does not
        pull samples fast enough, the queued buffers could consume a lot of memory,
        especially when dealing with raw video frames.
        Events can be pulled when the appsink is in the READY, PAUSED or PLAYING state.

        This function will only pull serialized events, excluding
        the EOS event for which this functions returns
        ``None``. Use :meth:`GstApp.AppSink.is_eos` to check for the EOS condition.

        This method is a variant of :meth:`GstApp.AppSink.pull_sample` that can be used
        to handle incoming events events as well as samples.

        Note that future releases may extend this API to return other object types
        so make sure that your code is checking for the actual type it is handling.
        """
    def set_buffer_list_support(self, enable_lists: bool) -> None:
        """
        Instruct ``appsink`` to enable or disable buffer list support.

        For backwards-compatibility reasons applications need to opt in
        to indicate that they will be able to handle buffer lists.
        """
    def set_caps(self, caps: Gst.Caps | None = ...) -> None:
        """
        Set the capabilities on the appsink element.  This function takes
        a copy of the caps structure. After calling this method, the sink will only
        accept caps that match ``caps``. If ``caps`` is non-fixed, or incomplete,
        you must check the caps on the samples to get the actual used caps.
        """
    @deprecated("Deprecated since 1.28.")
    def set_drop(self, drop: bool) -> None:
        """
        Instruct ``appsink`` to drop old buffers when the maximum amount of queued
        data is reached, that is, when any configured limit is hit (max-buffers, max-time or max-bytes).
        """
    def set_emit_signals(self, emit: bool) -> None:
        """
        Make appsink emit the "new-preroll" and "new-sample" signals. This option is
        by default disabled because signal emission is expensive and unneeded when
        the application prefers to operate in pull mode.
        """
    def set_leaky_type(self, leaky: AppLeakyType | int) -> None:
        """
        When set to any other value than GST_APP_LEAKY_TYPE_NONE then the appsink
        will drop any buffers that are pushed into it once its internal queue is
        full. The selected type defines whether to drop the oldest or new
        buffers.
        """
    def set_max_buffers(self, max: int) -> None:
        """
        Set the maximum amount of buffers that can be queued in ``appsink``. After this
        amount of buffers are queued in appsink, any more buffers will block upstream
        elements until a sample is pulled from ``appsink``, unless 'drop' is set, in which
        case new buffers will be discarded.
        """
    def set_max_bytes(self, max: int) -> None:
        """
        Set the maximum total size that can be queued in ``appsink``. After this
        amount of buffers are queued in appsink, any more buffers will block upstream
        elements until a sample is pulled from ``appsink``, unless 'drop' is set, in which
        case new buffers will be discarded.
        """
    def set_max_time(self, max: Gst.ClockTime) -> None:
        """
        Set the maximum total duration that can be queued in ``appsink``. After this
        amount of buffers are queued in appsink, any more buffers will block upstream
        elements until a sample is pulled from ``appsink``, unless 'drop' is set, in which
        case new buffers will be discarded.
        """
    def set_simple_callbacks(self, cb: AppSinkSimpleCallbacks | None = ...) -> None:
        """
        Set callbacks which will be executed for each new preroll, new sample and eos.
        This is an alternative to using the signals, it has lower overhead and is thus
        less expensive, but also less flexible.

        If callbacks are installed, no signals will be emitted for performance
        reasons.

        Once ``cb`` is set on an :class:`GstApp.AppSink` it is not possible anymore to change any of
        the callbacks inside it.

        Note that gst_app_sink_set_callbacks() and
        :meth:`GstApp.AppSink.set_simple_callbacks` are mutually exclusive and setting one
        will unset the other.
        """
    def set_wait_on_eos(self, wait: bool) -> None:
        """
        Instruct ``appsink`` to wait for all buffers to be consumed when an EOS is received.
        """
    def do_eos(self) -> None: ...
    def do_new_preroll(self) -> Gst.FlowReturn: ...
    def do_new_sample(self) -> Gst.FlowReturn: ...
    def do_pull_preroll(self) -> Gst.Sample | None:
        """
        Get the last preroll sample in ``appsink``. This was the sample that caused the
        appsink to preroll in the PAUSED state.

        This function is typically used when dealing with a pipeline in the PAUSED
        state. Calling this function after doing a seek will give the sample right
        after the seek position.

        Calling this function will clear the internal reference to the preroll
        buffer.

        Note that the preroll sample will also be returned as the first sample
        when calling :meth:`GstApp.AppSink.pull_sample`.

        If an EOS event was received before any buffers, this function returns
        ``None``. Use :meth:`GstApp.AppSink.is_eos` to check for the EOS condition.

        This function blocks until a preroll sample or EOS is received or the appsink
        element is set to the READY/NULL state.
        """
    def do_pull_sample(self) -> Gst.Sample | None:
        """
        This function blocks until a sample or EOS becomes available or the appsink
        element is set to the READY/NULL state.

        This function will only return samples when the appsink is in the PLAYING
        state. All rendered buffers will be put in a queue so that the application
        can pull samples at its own rate. Note that when the application does not
        pull samples fast enough, the queued buffers could consume a lot of memory,
        especially when dealing with raw video frames.

        If an EOS event was received before any buffers, this function returns
        ``None``. Use :meth:`GstApp.AppSink.is_eos` to check for the EOS condition.
        """
    def do_try_pull_object(self, timeout: Gst.ClockTime) -> Gst.MiniObject | None:
        """
        This function blocks until a sample or an event or EOS becomes available or the appsink
        element is set to the READY/NULL state or the timeout expires.

        This function will only return samples when the appsink is in the PLAYING
        state. All rendered buffers and events will be put in a queue so that the application
        can pull them at its own rate. Note that when the application does not
        pull samples fast enough, the queued buffers could consume a lot of memory,
        especially when dealing with raw video frames.
        Events can be pulled when the appsink is in the READY, PAUSED or PLAYING state.

        This function will only pull serialized events, excluding
        the EOS event for which this functions returns
        ``None``. Use :meth:`GstApp.AppSink.is_eos` to check for the EOS condition.

        This method is a variant of :meth:`GstApp.AppSink.try_pull_sample` that can be used
        to handle incoming events events as well as samples.

        Note that future releases may extend this API to return other object types
        so make sure that your code is checking for the actual type it is handling.
        """
    def do_try_pull_preroll(self, timeout: Gst.ClockTime) -> Gst.Sample | None:
        """
        Get the last preroll sample in ``appsink``. This was the sample that caused the
        appsink to preroll in the PAUSED state.

        This function is typically used when dealing with a pipeline in the PAUSED
        state. Calling this function after doing a seek will give the sample right
        after the seek position.

        Calling this function will clear the internal reference to the preroll
        buffer.

        Note that the preroll sample will also be returned as the first sample
        when calling :meth:`GstApp.AppSink.pull_sample`.

        If an EOS event was received before any buffers or the timeout expires,
        this function returns ``None``. Use :meth:`GstApp.AppSink.is_eos` to check for the EOS
        condition.

        This function blocks until a preroll sample or EOS is received, the appsink
        element is set to the READY/NULL state, or the timeout expires.
        """
    def do_try_pull_sample(self, timeout: Gst.ClockTime) -> Gst.Sample | None:
        """
        This function blocks until a sample or EOS becomes available or the appsink
        element is set to the READY/NULL state or the timeout expires.

        This function will only return samples when the appsink is in the PLAYING
        state. All rendered buffers will be put in a queue so that the application
        can pull samples at its own rate. Note that when the application does not
        pull samples fast enough, the queued buffers could consume a lot of memory,
        especially when dealing with raw video frames.

        If an EOS event was received before any buffers or the timeout expires,
        this function returns ``None``. Use :meth:`GstApp.AppSink.is_eos` to check for the EOS
        condition.
        """
    new_preroll: Signal[Self, [], Gst.FlowReturn]
    new_sample: Signal[Self, [], Gst.FlowReturn]
    new_serialized_event: Signal[Self, [], bool]
    propose_allocation: Signal[Self, [Gst.Query], bool]
    pull_preroll: SignalMethod[Self, [], Gst.Sample | None]
    pull_sample: SignalMethod[Self, [], Gst.Sample | None]
    try_pull_object: SignalMethod[Self, [int], Gst.MiniObject | None]
    try_pull_preroll: SignalMethod[Self, [int], Gst.Sample | None]
    try_pull_sample: SignalMethod[Self, [int], Gst.Sample | None]
    def do_new_serialized_event(self) -> bool: ...
    def do_propose_allocation(self, query: Gst.Query) -> bool: ...

class AppSinkClass:
    gimeta: ClassVar[_GIMeta]
    basesink_class: GstBase.BaseSinkClass
    eos: Any
    new_preroll: Any
    new_sample: Any
    pull_preroll: Any
    pull_sample: Any
    try_pull_preroll: Any
    try_pull_sample: Any
    try_pull_object: Any
    _gst_reserved: list[int]

class AppSinkPrivate:
    gimeta: ClassVar[_GIMeta]

class AppSinkSimpleCallbacks:
    """
    A set of callbacks that can be installed on the appsink with
    :meth:`GstApp.AppSink.set_simple_callbacks`.

    Unlike GstAppSinkCallbacks this can also be used from bindings.
    """
    gimeta: ClassVar[_GIMeta]
    def __init__(self) -> None:
        """
        Creates a new instance of callbacks.
        """
    @classmethod
    def new(cls) -> Self:
        """
        Creates a new instance of callbacks.
        """
    def ref(self) -> AppSinkSimpleCallbacks:
        """
        Increases the reference count of ``cb``.
        """
    def set_eos(self, eos_cb: AppSinkEosCallback) -> None:
        """
        Sets the EOS callback on ``cb``.

        Once ``cb`` is set on an :class:`GstApp.AppSink` it is not possible anymore to change any of
        the callbacks inside it.
        """
    def set_new_event(self, new_event_cb: AppSinkNewEventCallback) -> None:
        """
        Sets the new event callback on ``cb``.

        Once ``cb`` is set on an :class:`GstApp.AppSink` it is not possible anymore to change any of
        the callbacks inside it.
        """
    def set_new_preroll(self, new_preroll_cb: AppSinkNewPrerollCallback) -> None:
        """
        Sets the new preroll callback on ``cb``.

        Once ``cb`` is set on an :class:`GstApp.AppSink` it is not possible anymore to change any of
        the callbacks inside it.
        """
    def set_new_sample(self, new_sample_cb: AppSinkNewSampleCallback) -> None:
        """
        Sets the new sample callback on ``cb``.

        Once ``cb`` is set on an :class:`GstApp.AppSink` it is not possible anymore to change any of
        the callbacks inside it.
        """
    def set_propose_allocation(self, propose_allocation_cb: AppSinkProposeAllocationCallback) -> None:
        """
        Sets the new event callback on ``cb``.

        Once ``cb`` is set on an :class:`GstApp.AppSink` it is not possible anymore to change any of
        the callbacks inside it.
        """
    def unref(self) -> None:
        """
        Decreases the reference count of ``cb`` and frees it after the
        last reference is dropped.
        """

class AppSrc(GstBase.BaseSrc, Gst.URIHandler):
    """
    The appsrc element can be used by applications to insert data into a
    GStreamer pipeline. Unlike most GStreamer elements, appsrc provides
    external API functions.

    appsrc can be used by linking with the libgstapp library to access the
    methods directly or by using the appsrc action signals.

    Before operating appsrc, the caps property must be set to fixed caps
    describing the format of the data that will be pushed with appsrc. An
    exception to this is when pushing buffers with unknown caps, in which case no
    caps should be set. This is typically true of file-like sources that push raw
    byte buffers. If you don't want to explicitly set the caps, you can use
    :meth:`GstApp.AppSrc.push_sample`. This method gets the caps associated with the
    sample and sets them on the appsrc replacing any previously set caps (if
    different from sample's caps).

    The main way of handing data to the appsrc element is by calling the
    :meth:`GstApp.AppSrc.push_buffer` method or by emitting the push-buffer action signal.
    This will put the buffer onto a queue from which appsrc will read from in its
    streaming thread. It is important to note that data transport will not happen
    from the thread that performed the push-buffer call.

    The "max-bytes", "max-buffers" and "max-time" properties control how much
    data can be queued in appsrc before appsrc considers the queue full. A
    filled internal queue will always signal the "enough-data" signal, which
    signals the application that it should stop pushing data into appsrc. The
    "block" property will cause appsrc to block the push-buffer method until
    free data becomes available again.

    When the internal queue is running out of data, the "need-data" signal is
    emitted, which signals the application that it should start pushing more data
    into appsrc.

    In addition to the "need-data" and "enough-data" signals, appsrc can emit the
    "seek-data" signal when the "stream-mode" property is set to "seekable" or
    "random-access". The signal argument will contain the new desired position in
    the stream expressed in the unit set with the "format" property. After
    receiving the seek-data signal, the application should push-buffers from the
    new position.

    These signals allow the application to operate the appsrc in two different
    ways:

    The push mode, in which the application repeatedly calls the push-buffer/push-sample
    method with a new buffer/sample. Optionally, the queue size in the appsrc
    can be controlled with the enough-data and need-data signals by respectively
    stopping/starting the push-buffer/push-sample calls. This is a typical
    mode of operation for the stream-type "stream" and "seekable". Use this
    mode when implementing various network protocols or hardware devices.

    The pull mode, in which the need-data signal triggers the next push-buffer call.
    This mode is typically used in the "random-access" stream-type. Use this
    mode for file access or other randomly accessible sources. In this mode, a
    buffer of exactly the amount of bytes given by the need-data signal should be
    pushed into appsrc.

    In all modes, the size property on appsrc should contain the total stream
    size in bytes. Setting this property is mandatory in the random-access mode.
    For the stream and seekable modes, setting this property is optional but
    recommended.

    When the application has finished pushing data into appsrc, it should call
    :meth:`GstApp.AppSrc.end_of_stream` or emit the end-of-stream action signal. After
    this call, no more buffers can be pushed into appsrc until a flushing seek
    occurs or the state of the appsrc has gone through READY.
    """
    gimeta: ClassVar[_GIMeta]
    block: bool
    caps: Gst.Caps
    current_level_buffers: int
    current_level_bytes: int
    current_level_time: int
    dropped: int
    duration: int
    emit_signals: bool
    format: Gst.Format | int
    handle_segment_change: bool
    in_: int
    is_live: bool
    leaky_type: AppLeakyType | int
    max_buffers: int
    max_bytes: int
    max_latency: int
    max_time: int
    min_latency: int
    min_percent: int
    out: int
    silent: bool
    size: int
    stream_type: AppStreamType | int
    def __init__(self, *, block: bool = ..., caps: Gst.Caps = ..., duration: int = ..., emit_signals: bool = ..., format: Gst.Format | int = ..., handle_segment_change: bool = ..., is_live: bool = ..., leaky_type: AppLeakyType | int = ..., max_buffers: int = ..., max_bytes: int = ..., max_latency: int = ..., max_time: int = ..., min_latency: int = ..., min_percent: int = ..., silent: bool = ..., size: int = ..., stream_type: AppStreamType | int = ..., **kwargs: Any) -> None: ...
    def get_caps(self) -> Gst.Caps | None:
        """
        Get the configured caps on ``appsrc``.
        """
    def get_current_level_buffers(self) -> int:
        """
        Get the number of currently queued buffers inside ``appsrc``.
        """
    def get_current_level_bytes(self) -> int:
        """
        Get the number of currently queued bytes inside ``appsrc``.
        """
    def get_current_level_time(self) -> Gst.ClockTime:
        """
        Get the amount of currently queued time inside ``appsrc``.
        """
    def get_duration(self) -> Gst.ClockTime:
        """
        Get the duration of the stream in nanoseconds. A value of GST_CLOCK_TIME_NONE means that the duration is
        not known.
        """
    def get_emit_signals(self) -> bool:
        """
        Check if appsrc will emit the "new-preroll" and "new-buffer" signals.
        """
    def get_latency(self) -> tuple[int, int]:
        """
        Retrieve the min and max latencies in ``min`` and ``max`` respectively.
        """
    def get_leaky_type(self) -> AppLeakyType:
        """
        Returns the currently set :class:`GstApp.AppLeakyType`. See :meth:`GstApp.AppSrc.set_leaky_type`
        for more details.
        """
    def get_max_buffers(self) -> int:
        """
        Get the maximum amount of buffers that can be queued in ``appsrc``.
        """
    def get_max_bytes(self) -> int:
        """
        Get the maximum amount of bytes that can be queued in ``appsrc``.
        """
    def get_max_time(self) -> Gst.ClockTime:
        """
        Get the maximum amount of time that can be queued in ``appsrc``.
        """
    def get_size(self) -> int:
        """
        Get the size of the stream in bytes. A value of -1 means that the size is
        not known.
        """
    def get_stream_type(self) -> AppStreamType:
        """
        Get the stream type. Control the stream type of ``appsrc``
        with :meth:`GstApp.AppSrc.set_stream_type`.
        """
    def set_caps(self, caps: Gst.Caps | None = ...) -> None:
        """
        Set the capabilities on the appsrc element.  This function takes
        a copy of the caps structure. After calling this method, the source will
        only produce caps that match ``caps``. ``caps`` must be fixed and the caps on the
        buffers must match the caps or left NULL.
        """
    def set_duration(self, duration: Gst.ClockTime) -> None:
        """
        Set the duration of the stream in nanoseconds. A value of GST_CLOCK_TIME_NONE means that the duration is
        not known.
        """
    def set_emit_signals(self, emit: bool) -> None:
        """
        Make appsrc emit the "new-preroll" and "new-buffer" signals. This option is
        by default disabled because signal emission is expensive and unneeded when
        the application prefers to operate in pull mode.
        """
    def set_latency(self, min: int, max: int) -> None:
        """
        Configure the ``min`` and ``max`` latency in ``src``. If ``min`` is set to -1, the
        default latency calculations for pseudo-live sources will be used.
        """
    def set_leaky_type(self, leaky: AppLeakyType | int) -> None:
        """
        When set to any other value than GST_APP_LEAKY_TYPE_NONE then the appsrc
        will drop any buffers that are pushed into it once its internal queue is
        full. The selected type defines whether to drop the oldest or new
        buffers.
        """
    def set_max_buffers(self, max: int) -> None:
        """
        Set the maximum amount of buffers that can be queued in ``appsrc``.
        After the maximum amount of buffers are queued, ``appsrc`` will emit the
        "enough-data" signal.
        """
    def set_max_bytes(self, max: int) -> None:
        """
        Set the maximum amount of bytes that can be queued in ``appsrc``.
        After the maximum amount of bytes are queued, ``appsrc`` will emit the
        "enough-data" signal.
        """
    def set_max_time(self, max: Gst.ClockTime) -> None:
        """
        Set the maximum amount of time that can be queued in ``appsrc``.
        After the maximum amount of time are queued, ``appsrc`` will emit the
        "enough-data" signal.
        """
    def set_simple_callbacks(self, cb: AppSrcSimpleCallbacks | None = ...) -> None:
        """
        Set callbacks which will be executed when data is needed, enough data has
        been collected or when a seek should be performed.
        This is an alternative to using the signals, it has lower overhead and is thus
        less expensive, but also less flexible.

        If callbacks are installed, no signals will be emitted for performance
        reasons.

        Once ``cb`` is set on an :class:`GstApp.AppSrc` it is not possible anymore to change any of
        the callbacks inside it.

        Note that gst_app_src_set_callbacks() and
        :meth:`GstApp.AppSrc.set_simple_callbacks` are mutually exclusive and setting one
        will unset the other.
        """
    def set_size(self, size: int) -> None:
        """
        Set the size of the stream in bytes. A value of -1 means that the size is
        not known.
        """
    def set_stream_type(self, type: AppStreamType | int) -> None:
        """
        Set the stream type on ``appsrc``. For seekable streams, the "seek" signal must
        be connected to.

        A stream_type stream
        """
    def do_end_of_stream(self) -> Gst.FlowReturn:
        """
        Indicates to the appsrc element that the last buffer queued in the
        element is the last buffer of the stream.
        """
    def do_enough_data(self) -> None: ...
    def do_need_data(self, length: int) -> None: ...
    def do_push_buffer(self, buffer: Gst.Buffer) -> Gst.FlowReturn:
        """
        Adds a buffer to the queue of buffers that the appsrc element will
        push to its source pad.  This function takes ownership of the buffer.

        When the block property is TRUE, this function can block until free
        space becomes available in the queue.
        """
    def do_push_buffer_list(self, buffer_list: Gst.BufferList) -> Gst.FlowReturn:
        """
        Adds a buffer list to the queue of buffers and buffer lists that the
        appsrc element will push to its source pad.  This function takes ownership
        of ``buffer_list``.

        When the block property is TRUE, this function can block until free
        space becomes available in the queue.
        """
    def do_push_sample(self, sample: Gst.Sample) -> Gst.FlowReturn:
        """
        Extract a buffer from the provided sample and adds it to the queue of
        buffers that the appsrc element will push to its source pad. Any
        previous caps that were set on appsrc will be replaced by the caps
        associated with the sample if not equal.

        This function does not take ownership of the
        sample so the sample needs to be unreffed after calling this function.

        When the block property is TRUE, this function can block until free
        space becomes available in the queue.
        """
    def do_seek_data(self, offset: int) -> bool: ...
    end_of_stream: SignalMethod[Self, [], Gst.FlowReturn]
    enough_data: Signal[Self, [], None]
    need_data: Signal[Self, [int], None]
    push_buffer: SignalMethod[Self, [Gst.Buffer], Gst.FlowReturn]
    push_buffer_list: SignalMethod[Self, [Gst.BufferList], Gst.FlowReturn]
    push_sample: SignalMethod[Self, [Gst.Sample], Gst.FlowReturn]
    seek_data: Signal[Self, [int], bool]

class AppSrcClass:
    gimeta: ClassVar[_GIMeta]
    basesrc_class: GstBase.BaseSrcClass
    need_data: Any
    enough_data: Any
    seek_data: Any
    push_buffer: Any
    end_of_stream: Any
    push_sample: Any
    push_buffer_list: Any
    _gst_reserved: list[int]

class AppSrcPrivate:
    gimeta: ClassVar[_GIMeta]

class AppSrcSimpleCallbacks:
    """
    A set of callbacks that can be installed on the appsink with
    :meth:`GstApp.AppSink.set_simple_callbacks`.

    Unlike GstAppSrcCallbacks this can also be used from bindings.
    """
    gimeta: ClassVar[_GIMeta]
    def __init__(self) -> None:
        """
        Creates a new instance of callbacks.
        """
    @classmethod
    def new(cls) -> Self:
        """
        Creates a new instance of callbacks.
        """
    def ref(self) -> AppSrcSimpleCallbacks:
        """
        Increases the reference count of ``cb``.
        """
    def set_enough_data(self, enough_data_cb: AppSrcEnoughDataCallback) -> None:
        """
        Sets the enough data callback on ``cb``.

        Once ``cb`` is set on an :class:`GstApp.AppSrc` it is not possible anymore to change any of
        the callbacks inside it.
        """
    def set_need_data(self, need_data_cb: AppSrcNeedDataCallback) -> None:
        """
        Sets the need data callback on ``cb``.

        Once ``cb`` is set on an :class:`GstApp.AppSrc` it is not possible anymore to change any of
        the callbacks inside it.
        """
    def set_seek_data(self, seek_data_cb: AppSrcSeekDataCallback) -> None:
        """
        Sets the seek data callback on ``cb``.

        Once ``cb`` is set on an :class:`GstApp.AppSrc` it is not possible anymore to change any of
        the callbacks inside it.
        """
    def unref(self) -> None:
        """
        Decreases the reference count of ``cb`` and frees it after the
        last reference is dropped.
        """
