# Auto-generated by ginext-stubgen from PangoCairo-1.0.gir.
# Do not edit by hand.
# mypy: disable-error-code="override,type-arg,misc,valid-type"
from __future__ import annotations

from collections.abc import Iterator
from typing import Any, Awaitable, Callable, ClassVar, Final, Generic, Literal, NamedTuple, Self, TypeVar, override, overload
from ginext import Pango
import cairo
from ginext.overlay.registrar import OverlayRegistrar as _OverlayRegistrar
from ginext.private import GIMeta as _GIMeta

overlay: _OverlayRegistrar
__version__: tuple[int, ...]
def __getattr__(name: str) -> Any: ...

ShapeRendererFunc = Callable[[cairo.Context[cairo.Surface], Pango.AttrShape, bool], None]
class Font:
    """
    :class:`PangoCairo.Font` is an interface exported by fonts for
    use with Cairo.

    The actual type of the font will depend on the particular
    font technology Cairo was compiled to use.
    """
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    def get_scaled_font(self) -> cairo.ScaledFont | None:
        """
        Gets the ``cairo_scaled_font_t`` used by ``font``.
        The scaled font can be referenced and kept using
        cairo_scaled_font_reference().
        """

class FontMap:
    """
    :class:`PangoCairo.FontMap` is an interface exported by font maps for
    use with Cairo.

    The actual type of the font map will depend on the particular
    font technology Cairo was compiled to use.
    """
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    def get_font_type(self) -> cairo.FontType:
        """
        Gets the type of Cairo font backend that ``fontmap`` uses.
        """
    def get_resolution(self) -> float:
        """
        Gets the resolution for the fontmap.

        See :meth:`PangoCairo.FontMap.set_resolution`.
        """
    def set_default(self) -> None:
        """
        Sets a default :class:`PangoCairo.FontMap` to use with Cairo.

        This can be used to change the Cairo font backend that the
        default fontmap uses for example. The old default font map
        is unreffed and the new font map referenced.

        Note that since Pango 1.32.6, the default fontmap is per-thread.
        This function only changes the default fontmap for
        the current thread. Default fontmaps of existing threads
        are not changed. Default fontmaps of any new threads will
        still be created using :func:`PangoCairo.FontMap.new`.

        A value of ``None`` for ``fontmap`` will cause the current default
        font map to be released and a new default font map to be created
        on demand, using :func:`PangoCairo.FontMap.new`.
        """
    def set_resolution(self, dpi: float) -> None:
        """
        Sets the resolution for the fontmap.

        This is a scale factor between
        points specified in a ``PangoFontDescription`` and Cairo units. The
        default value is 96, meaning that a 10 point font will be 13
        units high. (10 * 96. / 72. = 13.3).
        """
    @staticmethod
    def get_default() -> Pango.FontMap:
        """
        Gets a default :class:`PangoCairo.FontMap` to use with Cairo.

        Note that the type of the returned object will depend on the
        particular font backend Cairo was compiled to use; you generally
        should only use the ``PangoFontMap`` and :class:`PangoCairo.FontMap`
        interfaces on the returned object.

        The default Cairo fontmap can be changed by using
        :meth:`PangoCairo.FontMap.set_default`. This can be used to
        change the Cairo font backend that the default fontmap uses
        for example.

        Note that since Pango 1.32.6, the default fontmap is per-thread.
        Each thread gets its own default fontmap. In this way, PangoCairo
        can be used safely from multiple threads.
        """
    @staticmethod
    def new() -> Pango.FontMap:
        """
        Creates a new :class:`PangoCairo.FontMap` object.

        A fontmap is used to cache information about available fonts,
        and holds certain global parameters such as the resolution.
        In most cases, you can use `func``PangoCairo``.font_map_get_default]
        instead.

        Note that the type of the returned object will depend
        on the particular font backend Cairo was compiled to use;
        You generally should only use the ``PangoFontMap`` and
        :class:`PangoCairo.FontMap` interfaces on the returned object.

        You can override the type of backend returned by using an
        environment variable ``PANGOCAIRO_BACKEND``. Supported types,
        based on your build, are fc (fontconfig), win32, and coretext.
        If requested type is not available, NULL is returned. Ie.
        this is only useful for testing, when at least two backends
        are compiled in.
        """
    @staticmethod
    def new_for_font_type(fonttype: cairo.FontType | int) -> Pango.FontMap | None:
        """
        Creates a new :class:`PangoCairo.FontMap` object of the type suitable
        to be used with cairo font backend of type ``fonttype``.

        In most cases one should simply use :func:`PangoCairo.FontMap.new`, or
        in fact in most of those cases, just use :func:`PangoCairo.FontMap.get_default`.
        """

def context_get_font_options(context: Pango.Context) -> cairo.FontOptions | None:
    """
    Retrieves any font rendering options previously set with
    :func:`PangoCairo.context_set_font_options`.

    This function does not report options that are derived from
    the target surface by :func:`update_context`.
    """
def context_get_resolution(context: Pango.Context) -> float:
    """
    Gets the resolution for the context.

    See :func:`PangoCairo.context_set_resolution`
    """
def context_set_font_options(context: Pango.Context, options: cairo.FontOptions | None = ...) -> None:
    """
    Sets the font options used when rendering text with this context.

    These options override any options that :func:`update_context`
    derives from the target surface.
    """
def context_set_resolution(context: Pango.Context, dpi: float) -> None:
    """
    Sets the resolution for the context.

    This is a scale factor between points specified in a ``PangoFontDescription``
    and Cairo units. The default value is 96, meaning that a 10 point font will
    be 13 units high. (10 * 96. / 72. = 13.3).
    """
def context_set_shape_renderer(context: Pango.Context, func: ShapeRendererFunc | None = ...) -> None:
    """
    Sets callback function for context to use for rendering attributes
    of type ``PANGO_ATTR_SHAPE``.

    See ``PangoCairoShapeRendererFunc`` for details.
    """
def create_context(cr: cairo.Context[cairo.Surface]) -> Pango.Context:
    """
    Creates a context object set up to match the current transformation
    and target surface of the Cairo context.

    This context can then be
    used to create a layout using :meth:`Pango.Layout.new`.

    This function is a convenience function that creates a context using
    the default font map, then updates it to ``cr``. If you just need to
    create a layout for use with ``cr`` and do not need to access ``PangoContext``
    directly, you can use :func:`create_layout` instead.
    """
def create_layout(cr: cairo.Context[cairo.Surface]) -> Pango.Layout:
    """
    Creates a layout object set up to match the current transformation
    and target surface of the Cairo context.

    This layout can then be used for text measurement with functions
    like :meth:`Pango.Layout.get_size` or drawing with functions like
    :func:`show_layout`. If you change the transformation or target
    surface for ``cr``, you need to call :func:`update_layout`.

    This function is the most convenient way to use Cairo with Pango,
    however it is slightly inefficient since it creates a separate
    ``PangoContext`` object for each layout. This might matter in an
    application that was laying out large amounts of text.
    """
def error_underline_path(cr: cairo.Context[cairo.Surface], x: float, y: float, width: float, height: float) -> None:
    """
    Add a squiggly line to the current path in the specified cairo context that
    approximately covers the given rectangle in the style of an underline used
    to indicate a spelling error.

    The width of the underline is rounded to an integer number of up/down
    segments and the resulting rectangle is centered in the original rectangle.
    """
def font_map_get_default() -> Pango.FontMap:
    """
    Gets a default :class:`PangoCairo.FontMap` to use with Cairo.

    Note that the type of the returned object will depend on the
    particular font backend Cairo was compiled to use; you generally
    should only use the ``PangoFontMap`` and :class:`PangoCairo.FontMap`
    interfaces on the returned object.

    The default Cairo fontmap can be changed by using
    :meth:`PangoCairo.FontMap.set_default`. This can be used to
    change the Cairo font backend that the default fontmap uses
    for example.

    Note that since Pango 1.32.6, the default fontmap is per-thread.
    Each thread gets its own default fontmap. In this way, PangoCairo
    can be used safely from multiple threads.
    """
def font_map_new() -> Pango.FontMap:
    """
    Creates a new :class:`PangoCairo.FontMap` object.

    A fontmap is used to cache information about available fonts,
    and holds certain global parameters such as the resolution.
    In most cases, you can use `func``PangoCairo``.font_map_get_default]
    instead.

    Note that the type of the returned object will depend
    on the particular font backend Cairo was compiled to use;
    You generally should only use the ``PangoFontMap`` and
    :class:`PangoCairo.FontMap` interfaces on the returned object.

    You can override the type of backend returned by using an
    environment variable ``PANGOCAIRO_BACKEND``. Supported types,
    based on your build, are fc (fontconfig), win32, and coretext.
    If requested type is not available, NULL is returned. Ie.
    this is only useful for testing, when at least two backends
    are compiled in.
    """
def font_map_new_for_font_type(fonttype: cairo.FontType | int) -> Pango.FontMap | None:
    """
    Creates a new :class:`PangoCairo.FontMap` object of the type suitable
    to be used with cairo font backend of type ``fonttype``.

    In most cases one should simply use :func:`PangoCairo.FontMap.new`, or
    in fact in most of those cases, just use :func:`PangoCairo.FontMap.get_default`.
    """
def glyph_string_path(cr: cairo.Context[cairo.Surface], font: Pango.Font, glyphs: Pango.GlyphString) -> None:
    """
    Adds the glyphs in ``glyphs`` to the current path in the specified
    cairo context.

    The origin of the glyphs (the left edge of the baseline)
    will be at the current point of the cairo context.
    """
def layout_line_path(cr: cairo.Context[cairo.Surface], line: Pango.LayoutLine) -> None:
    """
    Adds the text in ``PangoLayoutLine`` to the current path in the
    specified cairo context.

    The origin of the glyphs (the left edge of the line) will be
    at the current point of the cairo context.
    """
def layout_path(cr: cairo.Context[cairo.Surface], layout: Pango.Layout) -> None:
    """
    Adds the text in a ``PangoLayout`` to the current path in the
    specified cairo context.

    The top-left corner of the ``PangoLayout`` will be at the
    current point of the cairo context.
    """
def show_error_underline(cr: cairo.Context[cairo.Surface], x: float, y: float, width: float, height: float) -> None:
    """
    Draw a squiggly line in the specified cairo context that approximately
    covers the given rectangle in the style of an underline used to indicate a
    spelling error.

    The width of the underline is rounded to an integer
    number of up/down segments and the resulting rectangle is centered in the
    original rectangle.
    """
def show_glyph_item(cr: cairo.Context[cairo.Surface], text: str, glyph_item: Pango.GlyphItem) -> None:
    """
    Draws the glyphs in ``glyph_item`` in the specified cairo context,

    embedding the text associated with the glyphs in the output if the
    output format supports it (PDF for example), otherwise it acts
    similar to :func:`show_glyph_string`.

    The origin of the glyphs (the left edge of the baseline) will
    be drawn at the current point of the cairo context.

    Note that ``text`` is the start of the text for layout, which is then
    indexed by ``glyph_item->item->offset``.
    """
def show_glyph_string(cr: cairo.Context[cairo.Surface], font: Pango.Font, glyphs: Pango.GlyphString) -> None:
    """
    Draws the glyphs in ``glyphs`` in the specified cairo context.

    The origin of the glyphs (the left edge of the baseline) will
    be drawn at the current point of the cairo context.
    """
def show_layout(cr: cairo.Context[cairo.Surface], layout: Pango.Layout) -> None:
    """
    Draws a ``PangoLayout`` in the specified cairo context.

    The top-left corner of the ``PangoLayout`` will be drawn
    at the current point of the cairo context.
    """
def show_layout_line(cr: cairo.Context[cairo.Surface], line: Pango.LayoutLine) -> None:
    """
    Draws a ``PangoLayoutLine`` in the specified cairo context.

    The origin of the glyphs (the left edge of the line) will
    be drawn at the current point of the cairo context.
    """
def update_context(cr: cairo.Context[cairo.Surface], context: Pango.Context) -> None:
    """
    Updates a ``PangoContext`` previously created for use with Cairo to
    match the current transformation and target surface of a Cairo
    context.

    If any layouts have been created for the context, it's necessary
    to call :meth:`Pango.Layout.context_changed` on those layouts.
    """
def update_layout(cr: cairo.Context[cairo.Surface], layout: Pango.Layout) -> None:
    """
    Updates the private ``PangoContext`` of a ``PangoLayout`` created with
    :func:`create_layout` to match the current transformation and target
    surface of a Cairo context.
    """
