# Auto-generated by ginext-stubgen from Regress-1.0.gir.
# Do not edit by hand.
# mypy: disable-error-code="override,type-arg,misc,valid-type"
from __future__ import annotations

import os
from collections.abc import Iterator
from typing_extensions import deprecated
from contextlib import AbstractContextManager
from typing import Any, Awaitable, Callable, ClassVar, Concatenate, Generic, Final, Literal, NamedTuple, ParamSpec as _ParamSpec, Self, TypeVar, override, overload
from enum import IntEnum, IntFlag
from ginext import GLib
from ginext import GObject
from ginext import Gio
from ginext import Utility
import cairo
from ginext.overlay.registrar import OverlayRegistrar as _OverlayRegistrar
from ginext.private import GIMeta as _GIMeta

overlay: _OverlayRegistrar
__version__: tuple[int, ...]
def __getattr__(name: str) -> Any: ...

_SigO = TypeVar('_SigO')
_SigP = _ParamSpec('_SigP')
_SigR = TypeVar('_SigR')

class SignalConnection:
    handler_id: int
    signal_name: str
    source: Any
    callback: Callable[..., Any]
    after: bool
    once: bool
    owner: Any
    is_connected: bool
    def disconnect(self) -> None: ...
    def blocked(self) -> AbstractContextManager[SignalConnection]: ...

class Signal(Generic[_SigO, _SigP, _SigR]):
    def __call__(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...
    def connect(self, handler: Callable[Concatenate[_SigO, _SigP], _SigR], *, after: bool = ..., once: bool = ..., owner: Any = ...) -> SignalConnection: ...
    def connect_after(self, handler: Callable[Concatenate[_SigO, _SigP], _SigR]) -> SignalConnection: ...
    def emit(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...
    def disconnect(self, connection: SignalConnection) -> None: ...
class SignalMethod(Signal[_SigO, _SigP, _SigR]):
    def __call__(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...

class DetailedSignal(Signal[_SigO, _SigP, _SigR]):
    def __call__(self, detail: str | GObject.Property) -> 'Signal[_SigO, _SigP, _SigR]': ...

AliasedTestBoxed = TestBoxed
FooObjectCookie = int
class FooXEvent:
    pass

PtrArrayAlias = list[Any]
TestTypeGUInt64 = int
class ATestError(IntEnum):
    CODE0 = 0
    CODE1 = 1
    CODE2 = 2

class AnnotationBitfield(IntFlag):
    FOO = 1
    BAR = 2
    FOOBAR = 3

class FooASingle(IntEnum):
    FOO_SOME_SINGLE_ENUM = 0

class FooAddressType(IntEnum):
    INVALID = 0
    IPV4 = 1
    IPV6 = 2

class FooEnumFullname(IntEnum):
    ONE = 1
    TWO = 2
    THREE = 3

class FooEnumNoType(IntEnum):
    UN = 1
    DEUX = 2
    TROIS = 3
    NEUF = 9

class FooEnumType(IntEnum):
    ALPHA = 0
    BETA = 1
    DELTA = 2

class FooError(IntEnum):
    GOOD = 0
    BAD = 1
    UGLY = 2

class FooFlagsNoType(IntFlag):
    ETT = 1
    TVA = 2
    FYRA = 4

class FooFlagsType(IntFlag):
    FIRST = 1
    SECOND = 2
    THIRD = 4

class FooStackLayer(IntEnum):
    DESKTOP = 0
    BOTTOM = 1
    NORMAL = 2
    TOP = 4
    DOCK = 4
    FULLSCREEN = 5
    FOCUSED_WINDOW = 6
    OVERRIDE_REDIRECT = 7
    LAST = 8

class TestABCError(IntEnum):
    CODE1 = 1
    CODE2 = 2
    CODE3 = 3

class TestDEFError(IntEnum):
    CODE0 = 0
    CODE1 = 1
    CODE2 = 2

class TestDiscontinuousFlags(IntFlag):
    DISCONTINUOUS1 = 512
    DISCONTINUOUS2 = 536870912

class TestEnum(IntEnum):
    VALUE1 = 0
    VALUE2 = 1
    VALUE3 = -1
    VALUE4 = 48
    VALUE5 = 49

class TestEnumNoGEnum(IntEnum):
    EVALUE1 = 0
    EVALUE2 = 42
    EVALUE3 = 48

class TestEnumUnsigned(IntEnum):
    VALUE1 = 1
    VALUE2 = 2147483648

class TestError(IntEnum):
    CODE1 = 1
    CODE2 = 2
    CODE3 = 3

class TestFlags(IntFlag):
    FLAG1 = 1
    FLAG2 = 2
    FLAG3 = 4

class TestOtherError(IntEnum):
    CODE1 = 1
    CODE2 = 2
    CODE3 = 3

class TestPrivateEnum(IntFlag):
    PUBLIC_ENUM_BEFORE = 1
    PUBLIC_ENUM_AFTER = 4

class TestReferenceEnum(IntEnum):
    ZERO = 4
    ONE = 2
    TWO = 54
    THREE = 4
    FOUR = 216
    FIVE = -217

AnnotationCallback = Callable[[int], int]
AnnotationForeachFunc = Callable[[AnnotationObject, str], None]
AnnotationListCallback = Callable[[list[str]], list[str]]
AnnotationNotifyFunc = Callable[[], None]
FooCallback = Callable[[FooObject, bool], bool]
TestCallback = Callable[[], int]
TestCallbackArray = Callable[[list[int], list[str]], int]
TestCallbackArrayInOut = Callable[[list[int]], None]
TestCallbackFull = Callable[[int, float, str | bytes | os.PathLike[str] | os.PathLike[bytes]], int]
TestCallbackGError = Callable[[GLib.Error], None]
TestCallbackHashtable = Callable[[dict[str, int]], None]
TestCallbackOwnedGError = Callable[[GLib.Error], None]
TestCallbackReturnFull = Callable[[], TestObj]
TestCallbackUserData = Callable[[], int]
TestExternallyDefinedCallback = Callable[[TestObj, int], None]
TestFundamentalObjectCopyFunction = Callable[[TestFundamentalObject], TestFundamentalObject]
TestFundamentalObjectFinalizeFunction = Callable[[TestFundamentalObject], None]
TestNoPtrCallback = Callable[[], None]
TestSimpleCallback = Callable[[], None]
class AnAnonymousUnion:
    gimeta: ClassVar[_GIMeta]
    x: int

class AnnotationFields:
    """
    This is a struct for testing field documentation and annotations
    """
    gimeta: ClassVar[_GIMeta]
    field1: int
    arr: list[int]
    len: int
    field4: int

class AnnotationObject(GObject.Object):
    """
    This is an object used to test annotations.
    """
    gimeta: ClassVar[_GIMeta]
    function_property: AnnotationCallback
    @deprecated("Deprecated since 1.2.")
    @property
    def string_property(self) -> str: ...
    tab_property: str
    def __init__(self, *, function_property: AnnotationCallback = ..., string_property: str = ..., tab_property: str = ..., **kwargs: Any) -> None: ...
    def allow_none(self, somearg: str | None = ...) -> GObject.Object: ...
    def calleeowns(self) -> tuple[int, GObject.Object]:
        """
        This is a test for out arguments; GObject defaults to transfer
        """
    def calleesowns(self) -> tuple[int, GObject.Object, GObject.Object]:
        """
        This is a test for out arguments, one transferred, other not
        """
    def compute_sum(self, nums: list[int]) -> None:
        """
        Test taking a zero-terminated array
        """
    def compute_sum_n(self, nums: list[int]) -> None:
        """
        Test taking an array with length parameter
        """
    def compute_sum_nz(self, nums: list[int]) -> None:
        """
        Test taking a zero-terminated array with length parameter
        """
    def create_object(self) -> GObject.Object:
        """
        Test returning a caller-owned object
        """
    @deprecated("Deprecated since 0.12.")
    def do_not_use(self) -> GObject.Object: ...
    def extra_annos(self) -> None: ...
    def foreach(self, func: AnnotationForeachFunc) -> None:
        """
        Test taking a call-scoped callback
        """
    def get_hash(self) -> dict[str, GObject.Object]:
        """
        This is a test for returning a hash table mapping strings to
        objects.
        """
    def get_objects(self) -> list[AnnotationObject]:
        """
        This is a test for returning a list of objects.
        The list itself should be freed, but not the internal objects,
        intentionally similar example to gtk_container_get_children
        """
    def get_strings(self) -> list[str]:
        """
        This is a test for returning a list of strings, where
        each string needs to be freed.
        """
    def hidden_self(self) -> None: ...
    def in_(self, inarg: int) -> int:
        """
        This is a test for in arguments
        """
    def inout(self, inoutarg: int) -> tuple[int, int]:
        """
        This is a test for out arguments
        """
    def inout2(self, inoutarg: int) -> tuple[int, int]:
        """
        This is a second test for out arguments
        """
    def inout3(self, inoutarg: int) -> tuple[int, int]:
        """
        This is a 3th test for out arguments
        """
    def method(self) -> int: ...
    def notrans(self) -> GObject.Object: ...
    def out(self) -> tuple[int, int]:
        """
        This is a test for out arguments
        """
    def parse_args(self, argv: list[str]) -> list[str]:
        """
        Test taking a zero-terminated array with length parameter
        """
    def set_data(self, data: list[int]) -> None:
        """
        Test taking a guchar * with a length.
        """
    def set_data2(self, data: list[int]) -> None:
        """
        Test taking a gchar * with a length.
        """
    def set_data3(self, data: list[int]) -> None:
        """
        Test taking a gchar * with a length, overriding the array element
        type.
        """
    def string_out(self) -> tuple[bool, str]:
        """
        Test returning a string as an out parameter
        """
    def use_buffer(self, bytes: int) -> None: ...
    def watch(self, func: AnnotationForeachFunc) -> None:
        """
        Test overriding via the "Rename To" annotation.
        """
    def with_voidp(self, data: int | None = ...) -> None: ...
    attribute_signal: Signal[Self, [str, str], str]
    doc_empty_arg_parsing: Signal[Self, [int | None], None]
    list_signal: Signal[Self, [list[str]], None]
    string_signal: Signal[Self, [str], None]
    def do_attribute_signal(self, arg1: str, arg2: str) -> str: ...
    def do_doc_empty_arg_parsing(self, arg1: int | None) -> None: ...
    def do_list_signal(self, list: list[str]) -> None: ...
    def do_string_signal(self, string: str) -> None: ...

class AnnotationObjectClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: GObject.ObjectClass

class AnnotationStruct:
    """
    This is a test of an array of object in an field of a struct.
    """
    gimeta: ClassVar[_GIMeta]
    objects: list[AnnotationObject]

class AnonymousUnionAndStruct:
    gimeta: ClassVar[_GIMeta]
    x: int

class Bitmask:
    """
    A fundamental type that describes a 64-bit bitmask.

    This type resembles GStreamer's Bitmask type.
    """
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...

class FooBRect:
    gimeta: ClassVar[_GIMeta]
    x: float
    y: float
    def __init__(self, x: float, y: float) -> None: ...
    @classmethod
    def new(cls, x: float, y: float) -> Self: ...
    def add(self, b2: FooBRect) -> None: ...

class FooBUnion:
    gimeta: ClassVar[_GIMeta]
    type: int
    v: float
    rect: FooBRect
    def __init__(self) -> None: ...
    @classmethod
    def new(cls) -> Self: ...
    def get_contained_type(self) -> int: ...

class FooBoxed:
    gimeta: ClassVar[_GIMeta]
    def __init__(self) -> None: ...
    @classmethod
    def new(cls) -> Self: ...
    def method(self) -> None: ...

class FooBuffer(FooObject, FooInterface):
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    def some_method(self) -> None: ...

class FooBufferClass:
    gimeta: ClassVar[_GIMeta]

class FooDBusData:
    gimeta: ClassVar[_GIMeta]
    def method(self) -> None: ...

class FooEvent:
    gimeta: ClassVar[_GIMeta]
    type: int
    any: FooEventAny
    expose: FooEventExpose

class FooEventAny:
    gimeta: ClassVar[_GIMeta]
    send_event: int

class FooEventExpose:
    gimeta: ClassVar[_GIMeta]
    send_event: int
    count: int

class FooForeignStruct:
    gimeta: ClassVar[_GIMeta]
    regress_foo: int
    def __init__(self) -> None: ...
    @classmethod
    def new(cls) -> Self: ...
    def copy(self) -> FooForeignStruct: ...

class FooInterface:
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    def do_regress_foo(self, x: int) -> None: ...
    def do_do_regress_foo(self, x: int) -> None: ...
    @staticmethod
    def static_method(x: int) -> None: ...

class FooInterfaceIface:
    gimeta: ClassVar[_GIMeta]
    parent_iface: GObject.TypeInterface
    do_regress_foo: Any

class FooObject(GObject.Object, FooInterface):
    gimeta: ClassVar[_GIMeta]
    string: str
    def __init__(self, *, string: str = ..., **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...
    @classmethod
    def new_as_super(cls) -> Self: ...
    def append_new_stack_layer(self, x: int) -> FooOtherObject:
        """
        This shouldn't be scanned as a constructor.
        """
    def dup_name(self) -> str: ...
    def external_type(self) -> Utility.Object: ...
    def get_name(self) -> str: ...
    def handle_glyph(self, glyph: Utility.Glyph) -> None: ...
    def is_it_time_yet(self, time: int) -> None: ...
    def read(self, offset: int, length: int) -> None:
        """
        Read some stuff.
        """
    def seek(self, offset: int) -> None: ...
    def various(self, data: int | None, some_type: type | GObject.Type) -> None: ...
    def virtual_method(self, first_param: int) -> bool: ...
    def do_read_fn(self, offset: int, length: int) -> None:
        """
        Read some stuff.
        """
    def do_virtual_method(self, first_param: int) -> bool: ...
    @staticmethod
    def a_global_method(obj: Utility.Object) -> None:
        """
        This shouldn't be scanned as a method of UtilityObject.
        """
    @staticmethod
    def get_default() -> FooSubobject:
        """
        This function is intended to match clutter_stage_get_default which
        uses a C sugar return type.
        """
    @staticmethod
    def static_meth() -> int: ...
    signal: Signal[Self, [GObject.Object, int | None], str]
    def do_signal(self, object: GObject.Object, p0: int | None) -> str: ...

class FooObjectClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: GObject.ObjectClass
    virtual_method: Any
    read_fn: Any
    _reserved: list[GObject.Callback]

class FooOtherObject(GObject.Object):
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...

class FooOtherObjectClass:
    gimeta: ClassVar[_GIMeta]

class FooRectangle:
    gimeta: ClassVar[_GIMeta]
    x: int
    y: int
    width: int
    height: int
    def add(self, r2: FooRectangle) -> None: ...

class FooStruct:
    gimeta: ClassVar[_GIMeta]
    priv: FooStructPrivate
    member: int

class FooStructPrivate:
    gimeta: ClassVar[_GIMeta]

class FooSubInterface:
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    def do_bar(self) -> None: ...
    def do_baz(self, callback: GObject.Callback) -> None: ...
    def do_destroy_event(self) -> None: ...
    def do_do_bar(self) -> None: ...
    def do_do_baz(self, callback: GObject.Callback) -> None: ...
    destroy_event: Signal[Self, [], None]

class FooSubInterfaceIface:
    gimeta: ClassVar[_GIMeta]
    parent_iface: GObject.TypeInterface
    destroy_event: Any
    do_bar: Any
    do_baz: Any

class FooSubobject(FooObject, FooInterface):
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...

class FooSubobjectClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: FooObjectClass

class FooThingWithArray:
    gimeta: ClassVar[_GIMeta]
    x: int
    y: int
    lines: list[int]
    data: int

class FooUnion:
    gimeta: ClassVar[_GIMeta]
    regress_foo: int

class FooUtilityStruct:
    gimeta: ClassVar[_GIMeta]
    bar: Utility.Struct

class Intset:
    """
    Like telepathy-glib's TpIntset.
    """
    gimeta: ClassVar[_GIMeta]

class LikeGnomeKeyringPasswordSchema:
    gimeta: ClassVar[_GIMeta]
    dummy: int
    attributes: list[int]
    dummy2: float

class LikeXklConfigItem:
    gimeta: ClassVar[_GIMeta]
    name: list[int]
    def set_name(self, name: str) -> None: ...

class TestAction(GObject.InitiallyUnowned):
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    action: Signal[Self, [], TestAction]
    action2: Signal[Self, [], TestAction]
    def do_action(self) -> TestAction: ...
    def do_action2(self) -> TestAction: ...

class TestActionClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: GObject.InitiallyUnownedClass

class TestBoxed:
    gimeta: ClassVar[_GIMeta]
    some_int8: int
    nested_a: TestSimpleBoxedA
    priv: TestBoxedPrivate
    def __init__(self) -> None: ...
    @classmethod
    def new(cls) -> Self: ...
    @classmethod
    def new_alternative_constructor1(cls, i: int) -> Self: ...
    @classmethod
    def new_alternative_constructor2(cls, i: int, j: int) -> Self: ...
    @classmethod
    def new_alternative_constructor3(cls, s: str) -> Self: ...
    def _not_a_method(self) -> None: ...
    def copy(self) -> TestBoxed: ...
    def equals(self, other: TestBoxed) -> bool: ...

class TestBoxedB:
    gimeta: ClassVar[_GIMeta]
    some_int8: int
    some_long: int
    def __init__(self, some_int8: int, some_long: int) -> None: ...
    @classmethod
    def new(cls, some_int8: int, some_long: int) -> Self: ...
    def copy(self) -> TestBoxedB: ...

class TestBoxedC:
    gimeta: ClassVar[_GIMeta]
    refcount: int
    another_thing: int
    name_conflict: bool
    def __init__(self) -> None: ...
    @classmethod
    def new(cls) -> Self: ...

class TestBoxedCWrapper:
    gimeta: ClassVar[_GIMeta]
    def __init__(self) -> None: ...
    @classmethod
    def new(cls) -> Self: ...
    def copy(self) -> TestBoxedCWrapper: ...
    def get(self) -> TestBoxedC: ...

class TestBoxedD:
    gimeta: ClassVar[_GIMeta]
    def __init__(self, a_string: str, a_int: int) -> None: ...
    @classmethod
    def new(cls, a_string: str, a_int: int) -> Self: ...
    def copy(self) -> TestBoxedD: ...
    def free(self) -> None: ...
    def get_magic(self) -> int: ...

class TestBoxedPrivate:
    gimeta: ClassVar[_GIMeta]

class TestFloating(GObject.InitiallyUnowned):
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...

class TestFloatingClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: GObject.InitiallyUnownedClass

class TestFundamentalObject:
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    def ref(self) -> TestFundamentalObject: ...
    def unref(self) -> None: ...
    def do_copy(self) -> TestFundamentalObject: ...
    def do_finalize(self) -> None: ...

class TestFundamentalObjectClass:
    gimeta: ClassVar[_GIMeta]
    type_class: GObject.TypeClass
    copy: TestFundamentalObjectCopyFunction
    finalize: TestFundamentalObjectFinalizeFunction

class TestFundamentalObjectNoGetSetFunc:
    """
    Just like a :class:`Regress.TestFundamentalObject` but without gvalue setter and getter
    """
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...
    def get_data(self) -> str: ...
    @staticmethod
    def make_compatible_with_fundamental_sub_object() -> None: ...

class TestFundamentalObjectNoGetSetFuncClass:
    gimeta: ClassVar[_GIMeta]
    fundamental_object_class: TestFundamentalObjectClass

class TestFundamentalSubObject(TestFundamentalObject):
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...

class TestFundamentalSubObjectClass:
    gimeta: ClassVar[_GIMeta]
    fundamental_object_class: TestFundamentalObjectClass

class TestFundamentalSubObjectNoGetSetFunc(TestFundamentalObjectNoGetSetFunc):
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...

class TestFundamentalSubObjectNoGetSetFuncClass:
    gimeta: ClassVar[_GIMeta]
    fundamental_object_class: TestFundamentalObjectNoGetSetFuncClass

class TestInheritDrawable(GObject.Object):
    gimeta: ClassVar[_GIMeta]
    def __init__(self, **kwargs: Any) -> None: ...
    def do_foo(self, x: int) -> None: ...
    def do_foo_maybe_throw(self, x: int) -> None: ...
    def get_origin(self) -> tuple[int, int]: ...
    def get_size(self) -> tuple[int, int]: ...

class TestInheritDrawableClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: GObject.ObjectClass

class TestInheritPixmapObjectClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: TestInheritDrawableClass

class TestInterface:
    gimeta: ClassVar[_GIMeta]
    number: int
    def __init__(self, *, number: int = ..., **kwargs: Any) -> None: ...
    def emit_signal(self) -> None: ...
    interface_signal: Signal[Self, [int], None]
    def do_interface_signal(self, ptr: int) -> None: ...

class TestInterfaceIface:
    gimeta: ClassVar[_GIMeta]
    base_iface: GObject.TypeInterface

class TestObj(GObject.Object):
    gimeta: ClassVar[_GIMeta]
    bare: GObject.Object
    boxed: TestBoxed
    byte_array: list[int]
    double: float
    float: float
    gtype: type | GObject.Type
    hash_table: dict[str, int]
    hash_table_old: dict[str, int]
    int: int
    list: list[str]
    list_old: list[str]
    name_conflict: int
    pptrarray: list[str]
    string: str
    unichar: int
    write_only: bool
    def __init__(self, *, bare: GObject.Object = ..., boxed: TestBoxed = ..., byte_array: list[int] = ..., double: float = ..., float: float = ..., gtype: type | GObject.Type = ..., hash_table: dict[str, int] = ..., hash_table_old: dict[str, int] = ..., int: int = ..., list: list[str] = ..., list_old: list[str] = ..., name_conflict: int = ..., pptrarray: list[str] = ..., string: str = ..., unichar: int = ..., write_only: bool = ..., **kwargs: Any) -> None: ...
    @classmethod
    def constructor(cls) -> Self: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...
    @classmethod
    def new_callback(cls, callback: TestCallbackUserData) -> Self: ...
    @classmethod
    def new_finish(cls, res: Gio.AsyncResult) -> Self: ...
    @classmethod
    def new_from_file(cls, x: str) -> Self: ...
    def do_matrix(self, somestr: str) -> int:
        """
        This method is virtual.  Notably its name differs from the virtual
        slot name, which makes it useful for testing bindings handle this
        case.
        """
    def emit_sig_with_array_len_prop(self) -> None: ...
    def emit_sig_with_error(self) -> None: ...
    def emit_sig_with_foreign_struct(self) -> None: ...
    def emit_sig_with_gstrv_full(self) -> None: ...
    def emit_sig_with_inout_int(self) -> None:
        """
        The signal handler must increment the inout parameter by 1.
        """
    def emit_sig_with_int64(self) -> None: ...
    def emit_sig_with_null_error(self) -> None: ...
    def emit_sig_with_obj(self) -> None: ...
    def emit_sig_with_obj_full(self) -> None: ...
    def emit_sig_with_uint64(self) -> None: ...
    def forced_method(self) -> None: ...
    def function2(self, io_priority: int, cancellable: Gio.Cancellable | None = ..., test_cb: TestCallbackUserData | None = ..., callback: Gio.AsyncReadyCallback | None = ...) -> None:
        """
        This is an example taken from FPrint: ``fp_device_verify``.
        """
    def function2_finish(self, result: Gio.AsyncResult) -> tuple[bool, bool, GObject.Object]:
        """
        Finish function for ``regress_test_obj_function2_async()``.
        """
    def function2_sync(self, io_priority: int) -> bool: ...
    @overload
    def function_async(self, io_priority: int, cancellable: Gio.Cancellable | None = ..., callback: None = ...) -> Awaitable[bool]: ...
    @overload
    def function_async(self, io_priority: int, cancellable: Gio.Cancellable | None = ..., callback: Gio.AsyncReadyCallback = ...) -> None: ...
    def function_finish(self, res: Gio.AsyncResult) -> bool: ...
    def function_sync(self, io_priority: int) -> bool: ...
    def function_thaw_async(self) -> int: ...
    def get_string(self) -> str: ...
    def instance_method(self) -> int: ...
    def instance_method_callback(self, callback: TestCallback | None = ...) -> None: ...
    def instance_method_full(self) -> None: ...
    def not_nullable_element_typed_gpointer_in(self, input: list[int]) -> None: ...
    def not_nullable_typed_gpointer_in(self, input: GObject.Object) -> None: ...
    def set_bare(self, bare: GObject.Object | None = ...) -> None: ...
    def set_string(self, str: str) -> None: ...
    def skip_inout_param(self, a: int, c: float, inout_d: int, num1: int, num2: int) -> tuple[bool, int, int, int]:
        """
        Check that the out value is skipped
        """
    def skip_out_param(self, a: int, c: float, inout_d: int, num1: int, num2: int) -> tuple[bool, int, int, int]:
        """
        Check that the out value is skipped
        """
    def skip_param(self, a: int, c: float, inout_d: int, num1: int, num2: int) -> tuple[bool, int, int, int]:
        """
        Check that a parameter is skipped
        """
    def skip_return_val(self, a: int, c: float, inout_d: int, num1: int, num2: int) -> tuple[bool, int, int, int]:
        """
        Check that the return value is skipped
        """
    def skip_return_val_no_out(self, a: int) -> bool:
        """
        Check that the return value is skipped. Succeed if a is nonzero, otherwise
        raise an error.
        """
    def torture_signature_0(self, x: int, foo: str, m: int) -> tuple[float, int, int]: ...
    def torture_signature_1(self, x: int, foo: str, m: int) -> tuple[bool, float, int, int]:
        """
        This function throws an error if m is odd.
        """
    def do_allow_none_vfunc(self, two: TestObj | None = ...) -> None: ...
    def do_complex_vfunc(self, someint: int) -> None: ...
    def do_static_vfunc_out(self) -> None: ...
    @staticmethod
    def constructor_thaw_async() -> int: ...
    @staticmethod
    def new_async(x: str, cancellable: Gio.Cancellable | None = ..., callback: Gio.AsyncReadyCallback | None = ...) -> None: ...
    @staticmethod
    def null_out() -> TestObj: ...
    @staticmethod
    def static_method(x: int) -> float: ...
    @staticmethod
    def static_method_callback(callback: TestCallback | None = ...) -> None: ...
    all: Signal[Self, [], None]
    cleanup: Signal[Self, [], None]
    first: Signal[Self, [], None]
    sig_with_array_len_prop: Signal[Self, [list[int] | None], None]
    sig_with_array_prop: Signal[Self, [list[int]], None]
    sig_with_foreign_struct: Signal[Self, [cairo.Context[cairo.Surface]], None]
    sig_with_gerror: Signal[Self, [GLib.Error | None], None]
    sig_with_hash_prop: Signal[Self, [dict[str, GObject.Value]], None]
    sig_with_inout_int: Signal[Self, [int], None]
    sig_with_int64_prop: Signal[Self, [int], int]
    sig_with_intarray_ret: Signal[Self, [int], list[int]]
    sig_with_obj: Signal[Self, [GObject.Object], None]
    sig_with_obj_full: Signal[Self, [GObject.Object], None]
    sig_with_strv: Signal[Self, [list[str]], None]
    sig_with_strv_full: Signal[Self, [list[str]], None]
    sig_with_uint64_prop: Signal[Self, [int], int]
    test: Signal[Self, [], None]
    test_with_static_scope_arg: Signal[Self, [TestSimpleBoxedA], None]
    def do_all(self) -> None: ...
    def do_cleanup(self) -> None: ...
    def do_first(self) -> None: ...
    def do_sig_with_array_len_prop(self, arr: list[int] | None) -> None: ...
    def do_sig_with_array_prop(self, arr: list[int]) -> None: ...
    def do_sig_with_foreign_struct(self, cr: cairo.Context[cairo.Surface]) -> None: ...
    def do_sig_with_gerror(self, error: GLib.Error | None) -> None: ...
    def do_sig_with_hash_prop(self, hash: dict[str, GObject.Value]) -> None: ...
    def do_sig_with_inout_int(self, position: int) -> None: ...
    def do_sig_with_int64_prop(self, i: int) -> int: ...
    def do_sig_with_intarray_ret(self, i: int) -> list[int]: ...
    def do_sig_with_obj(self, obj: GObject.Object) -> None: ...
    def do_sig_with_obj_full(self, obj: GObject.Object) -> None: ...
    def do_sig_with_strv(self, strs: list[str]) -> None: ...
    def do_sig_with_strv_full(self, strs: list[str]) -> None: ...
    def do_sig_with_uint64_prop(self, i: int) -> int: ...
    def do_test(self) -> None: ...
    def do_test_with_static_scope_arg(self, object: TestSimpleBoxedA) -> None: ...

class TestObjClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: GObject.ObjectClass
    matrix: Any
    allow_none_vfunc: Any
    static_vfunc: Any
    static_vfunc_out: Any
    test_signal: int
    test_signal_with_static_scope_arg: int
    complex_vfunc: TestExternallyDefinedCallback

class TestPrivateStruct:
    gimeta: ClassVar[_GIMeta]
    this_is_public_before: int
    this_is_private: int
    this_is_public_after: int

class TestReferenceCounters:
    gimeta: ClassVar[_GIMeta]
    refcount: int
    atomicrefcount: int

class TestSimpleBoxedA:
    """
    ...
    """
    gimeta: ClassVar[_GIMeta]
    some_int: int
    some_int8: int
    some_double: float
    some_enum: TestEnum | int
    def copy(self) -> TestSimpleBoxedA: ...
    def equals(self, other_a: TestSimpleBoxedA) -> bool: ...
    @staticmethod
    def const_return() -> TestSimpleBoxedA: ...

class TestSimpleBoxedB:
    gimeta: ClassVar[_GIMeta]
    some_int8: int
    nested_a: TestSimpleBoxedA
    def copy(self) -> TestSimpleBoxedB: ...

class TestStructA:
    gimeta: ClassVar[_GIMeta]
    some_int: int
    some_int8: int
    some_double: float
    some_enum: TestEnum | int
    def clone(self) -> TestStructA:
        """
        Make a copy of a :class:`Regress.TestStructA`
        """
    @staticmethod
    def parse(string: str) -> TestStructA: ...

class TestStructB:
    gimeta: ClassVar[_GIMeta]
    some_int8: int
    nested_a: TestStructA
    def clone(self) -> TestStructB:
        """
        Make a copy of a :class:`Regress.TestStructB`
        """

class TestStructC:
    gimeta: ClassVar[_GIMeta]
    another_int: int
    obj: GObject.Object

class TestStructD:
    gimeta: ClassVar[_GIMeta]
    array1: list[TestStructA]
    array2: list[TestObj]
    field: TestObj
    list: list[TestObj]
    garray: list[TestObj]

class TestStructE:
    gimeta: ClassVar[_GIMeta]
    some_type: type | GObject.Type
    some_union: list[TestStructE__some_union__union]

class TestStructE__some_union__union:
    gimeta: ClassVar[_GIMeta]
    v_int: int
    v_uint: int
    v_long: int
    v_ulong: int
    v_int64: int
    v_uint64: int
    v_float: float
    v_double: float
    v_pointer: int

class TestStructF:
    gimeta: ClassVar[_GIMeta]
    ref_count: int
    data1: int
    data2: int
    data3: int
    data4: int
    data5: int
    data6: int
    data7: int

class TestStructFixedArray:
    gimeta: ClassVar[_GIMeta]
    just_int: int
    array: list[int]
    def frob(self) -> None: ...

class TestSubObj(TestObj, TestInterface):
    gimeta: ClassVar[_GIMeta]
    boolean: bool
    def __init__(self, *, boolean: bool = ..., **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...
    def instance_method(self) -> int: ...
    def unset_bare(self) -> None: ...

class TestSubObjClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: TestObjClass

class TestWi8021x(GObject.Object):
    gimeta: ClassVar[_GIMeta]
    testbool: bool
    def __init__(self, *, testbool: bool = ..., **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...
    def get_testbool(self) -> bool: ...
    def set_testbool(self, v: bool) -> None: ...
    @staticmethod
    def static_method(x: int) -> int: ...

class TestWi8021xClass:
    gimeta: ClassVar[_GIMeta]
    parent_class: GObject.ObjectClass

ANNOTATION_CALCULATED_DEFINE: int
ANNOTATION_CALCULATED_LARGE: int
"""
Constant to define a calculated large value
"""
ANNOTATION_CALCULATED_LARGE_DIV: int
"""
Constant to define a calculated large value
"""
BAD_EXPR_CONSTANT: int
BOOL_CONSTANT: bool
DOUBLE_CONSTANT: float
FOO_DEFINE_SHOULD_BE_EXPOSED: str
FOO_FLAGS_SECOND_AND_THIRD: int
FOO_PIE_IS_TASTY: float
FOO_SUCCESS_INT: int
GI_SCANNER_ELSE: int
GI_SCANNER_IFDEF: int
GOOD_EXPR_CONSTANT: int
GUINT64_CONSTANT: int
GUINT64_CONSTANTA: TestTypeGUInt64
G_GINT64_CONSTANT: int
INT_CONSTANT: int
LONG_STRING_CONSTANT: str
MAXUINT64: int
MININT64: int
Mixed_Case_Constant: int
NEGATIVE_INT_CONSTANT: int
STRING_CONSTANT: str
UTF8_CONSTANT: str
def aliased_caller_alloc() -> AliasedTestBoxed: ...
def annotation_attribute_func(object: AnnotationObject, data: str) -> int: ...
def annotation_custom_destroy(callback: AnnotationCallback) -> None:
    """
    Test messing up the heuristic of closure/destroy-notification
    detection, and fixing it via annotations.
    """
def annotation_custom_destroy_cleanup() -> None:
    """
    Use in tests for bindings with managed memory, to clean up the callback
    passed to :func:`Regress.annotation_custom_destroy`.
    """
def annotation_get_source_file() -> str: ...
def annotation_init(argv: list[str]) -> list[str]: ...
def annotation_invalid_regress_annotation(foo: int) -> None: ...
def annotation_ptr_array(array: list[GObject.Value]) -> None: ...
def annotation_return_array() -> list[str]: ...
def annotation_return_filename() -> str: ...
def annotation_set_source_file(fname: str | bytes | os.PathLike[str] | os.PathLike[bytes]) -> None: ...
def annotation_space_after_comment_bug631690() -> None:
    """
    Explicitly test having a space after the ** here.
    """
def annotation_string_array_length(properties: list[str]) -> None: ...
def annotation_string_zero_terminated() -> list[str]: ...
def annotation_string_zero_terminated_out(out: list[str]) -> list[str]: ...
def annotation_test_parsing_bug630862() -> GObject.Object:
    """
    See https://bugzilla.gnome.org/show_bug.cgi?id=630862
    """
def annotation_transfer_floating(object: GObject.Object) -> GObject.Object: ...
def annotation_versioned() -> None: ...
def atest_error_quark() -> GLib.Quark: ...
def foo_async_ready_callback(cancellable: Gio.Cancellable | None = ..., callback: Gio.AsyncReadyCallback | None = ...) -> None: ...
def foo_destroy_notify_callback(callback: FooCallback) -> None: ...
def foo_enum_method(regress_foo_enum: FooEnumType | int) -> int: ...
def foo_enum_type_method(regress_foo_enum: FooEnumType | int) -> int: ...
def foo_enum_type_returnv(x: int) -> FooEnumType: ...
def foo_error_quark() -> GLib.Quark: ...
def foo_init() -> int: ...
def foo_init_argv(argv: list[str] | None = ...) -> int: ...
def foo_init_argv_address(argv: list[str]) -> tuple[int, list[str]]: ...
def foo_interface_static_method(x: int) -> None: ...
def foo_method_external_references(object: Utility.Object, e: Utility.EnumType | int, f: Utility.FlagType | int, s: Utility.Struct) -> None: ...
def foo_not_a_constructor_new() -> FooObject:
    """
    This should be scanned as a top-level function, and shouldn't cause
    a "Can't find matching type for constructor" warning.
    """
def foo_test_array() -> list[str]: ...
def foo_test_const_char_param(param: str) -> None: ...
def foo_test_const_char_retval() -> str: ...
def foo_test_const_struct_param(param: FooStruct) -> None: ...
def foo_test_const_struct_retval() -> FooStruct: ...
def foo_test_string_array(array: list[str]) -> None: ...
def foo_test_string_array_with_g(array: list[str]) -> None: ...
def foo_test_unsigned(unsigned_param: int) -> None: ...
def foo_test_unsigned_type(unsigned_param: int) -> None: ...
def func_obj_null_in(obj: TestObj | None = ...) -> None: ...
def func_obj_nullable_in(obj: TestObj | None = ...) -> None: ...
def get_variant() -> GLib.Variant: ...
def global_get_flags_out() -> TestFlags | int: ...
def has_parameter_named_attrs(foo: int, attributes: list[int]) -> None:
    """
    This test case mirrors GnomeKeyringPasswordSchema from
    libgnome-keyring.
    """
def introspectable_via_alias(data: PtrArrayAlias) -> None: ...
def set_abort_on_error(abort_on_error: bool) -> None: ...
def test_abc_error_quark() -> GLib.Quark: ...
def test_array_callback(callback: TestCallbackArray) -> int: ...
def test_array_fixed_boxed_none_out() -> list[TestBoxedC]: ...
def test_array_fixed_out_objects() -> list[TestObj]: ...
def test_array_fixed_size_int_in(ints: list[int]) -> int: ...
def test_array_fixed_size_int_out() -> list[int]: ...
def test_array_fixed_size_int_return() -> list[int]: ...
def test_array_gint16_in(ints: list[int]) -> int: ...
def test_array_gint32_in(ints: list[int]) -> int: ...
def test_array_gint64_in(ints: list[int]) -> int: ...
def test_array_gint8_in(ints: list[int]) -> int: ...
def test_array_gtype_in(types: list[type | GObject.Type]) -> str: ...
def test_array_inout_callback(callback: TestCallbackArrayInOut) -> int: ...
def test_array_int_full_out() -> list[int]: ...
def test_array_int_in(ints: list[int]) -> int: ...
def test_array_int_inout(ints: list[int]) -> list[int]: ...
def test_array_int_none_out() -> list[int]: ...
def test_array_int_null_in(arr: list[int] | None = ...) -> None: ...
def test_array_int_null_out() -> list[int]: ...
def test_array_int_out() -> list[int]: ...
def test_array_of_fundamental_objects_in(list: list[TestFundamentalObject]) -> bool: ...
def test_array_of_fundamental_objects_out() -> list[TestFundamentalObject]: ...
def test_array_of_non_utf8_strings() -> list[str] | None: ...
def test_array_static_in_int(x: list[int]) -> None: ...
def test_array_struct_in_full(arr: list[TestStructA]) -> None:
    """
    Test flat array input with transfer full.

    Similar to:
    - gsf_property_settings_free() with structs but they contain pointers
    - g_byte_array_new_take() with guint8s
    """
def test_array_struct_in_none(arr: list[TestStructA]) -> None:
    """
    Test flat array input with transfer none.

    Similar to g_main_context_check() or gtk_target_list_new().
    """
def test_array_struct_out() -> list[TestStructA]:
    """
    This is similar to gdk_keymap_get_entries_for_keyval().
    """
def test_array_struct_out_caller_alloc() -> list[TestStructA]:
    """
    Test flat caller-allocated array output.

    Similar to g_main_context_query().
    """
def test_array_struct_out_container() -> list[TestStructA]:
    """
    Test flat array output with transfer container.

    Similar to pango_layout_get_log_attrs().
    """
def test_array_struct_out_full_fixed() -> list[TestStructA]:
    """
    Test flat fixed-size array output with transfer full.
    """
def test_array_struct_out_none() -> list[TestStructA]:
    """
    Test flat array output with transfer none.

    Similar to:
    - mm_modem_peek_ports() with structs
    - gdk_query_visual_types() with enums
    - gdk_event_get_axes() with doubles
    """
def test_async_ready_callback(callback: Gio.AsyncReadyCallback | None = ...) -> None: ...
def test_boolean(in_: bool) -> bool: ...
def test_boolean_false(in_: bool) -> bool: ...
def test_boolean_true(in_: bool) -> bool: ...
def test_boxeds_not_a_method(boxed: TestBoxed) -> None: ...
def test_boxeds_not_a_static() -> None: ...
def test_cairo_context_full_in(context: cairo.Context[cairo.Surface]) -> None: ...
def test_cairo_context_full_return() -> cairo.Context[cairo.Surface]: ...
def test_cairo_context_none_in(context: cairo.Context[cairo.Surface]) -> None: ...
def test_cairo_context_none_return() -> cairo.Context[cairo.Surface]: ...
def test_cairo_font_face_full_return(cairo: cairo.Context[cairo.Surface]) -> cairo.FontFace: ...
def test_cairo_font_options_full_in(options: cairo.FontOptions) -> None: ...
def test_cairo_font_options_full_return() -> cairo.FontOptions: ...
def test_cairo_font_options_none_in(options: cairo.FontOptions) -> None: ...
def test_cairo_font_options_none_return() -> cairo.FontOptions: ...
def test_cairo_matrix_none_in(matrix: cairo.Matrix) -> None: ...
def test_cairo_matrix_none_return() -> cairo.Matrix: ...
def test_cairo_matrix_out_caller_allocates() -> cairo.Matrix: ...
def test_cairo_path_full_in_full_return(path: cairo.Path) -> cairo.Path: ...
def test_cairo_path_full_return() -> cairo.Path: ...
def test_cairo_path_none_in(path: cairo.Path) -> None: ...
def test_cairo_pattern_full_in(pattern: cairo.Pattern) -> None: ...
def test_cairo_pattern_full_return() -> cairo.Pattern: ...
def test_cairo_pattern_none_in(pattern: cairo.Pattern) -> None: ...
def test_cairo_pattern_none_return() -> cairo.Pattern: ...
def test_cairo_region_full_in(region: cairo.Region) -> None: ...
def test_cairo_scaled_font_full_return(cairo: cairo.Context[cairo.Surface]) -> cairo.ScaledFont: ...
def test_cairo_surface_full_in(surface: cairo.Surface) -> None: ...
def test_cairo_surface_full_out() -> cairo.Surface: ...
def test_cairo_surface_full_return() -> cairo.Surface: ...
def test_cairo_surface_none_in(surface: cairo.Surface) -> None: ...
def test_cairo_surface_none_return() -> cairo.Surface: ...
def test_callback(callback: TestCallback | None = ...) -> int: ...
def test_callback_async(callback: TestCallbackUserData) -> None: ...
def test_callback_destroy_notify(callback: TestCallbackUserData) -> int:
    """
    Notified - callback persists until a DestroyNotify delegate
    is invoked.
    """
def test_callback_destroy_notify_no_user_data(callback: TestCallbackUserData) -> int:
    """
    Adds a scope notified callback with no user data. This can invoke an error
    condition in bindings which needs to be tested.
    """
def test_callback_return_full(callback: TestCallbackReturnFull) -> None: ...
def test_callback_thaw_async() -> int: ...
def test_callback_thaw_notifications() -> int:
    """
    Invokes all callbacks installed by #test_callback_destroy_notify(),
    adding up their return values, and removes them, invoking the
    corresponding destroy notfications.
    """
def test_callback_user_data(callback: TestCallbackUserData) -> int:
    """
    Call - callback parameter persists for the duration of the method
    call and can be released on return.
    """
def test_closure(closure: GObject.Closure) -> int: ...
def test_closure_one_arg(closure: GObject.Closure, arg: int) -> int: ...
def test_closure_variant(closure: GObject.Closure, arg: GLib.Variant | None = ...) -> GLib.Variant: ...
def test_create_fundamental_hidden_class_instance() -> TestFundamentalObject: ...
def test_date_in_gvalue() -> GObject.Value: ...
def test_def_error_quark() -> GLib.Quark: ...
def test_discontinuous_1_with_private_values() -> TestDiscontinuousFlags: ...
def test_discontinuous_2_with_private_values() -> TestDiscontinuousFlags: ...
def test_double(in_: float) -> float: ...
def test_enum_param(e: TestEnum | int) -> str: ...
def test_error_quark() -> GLib.Quark: ...
def test_filename_return() -> list[str]: ...
def test_float(in_: float) -> float: ...
@overload
def test_function_async(io_priority: int, cancellable: Gio.Cancellable | None = ..., callback: None = ...) -> Awaitable[bool]: ...
@overload
def test_function_async(io_priority: int, cancellable: Gio.Cancellable | None = ..., callback: Gio.AsyncReadyCallback = ...) -> None: ...
def test_function_finish(res: Gio.AsyncResult) -> bool: ...
def test_function_sync(io_priority: int) -> bool: ...
def test_function_thaw_async() -> int: ...
def test_fundamental_argument_in(obj: TestFundamentalObject) -> bool: ...
def test_fundamental_argument_out(obj: TestFundamentalObject) -> TestFundamentalObject: ...
def test_garray_container_return() -> list[str]: ...
def test_garray_full_return() -> list[str]: ...
def test_gerror_callback(callback: TestCallbackGError) -> None: ...
def test_ghash_container_return() -> dict[str, str]: ...
def test_ghash_everything_return() -> dict[str, str]: ...
def test_ghash_gvalue_in(hash: dict[str, GObject.Value]) -> None: ...
def test_ghash_gvalue_return() -> dict[str, GObject.Value]: ...
def test_ghash_nested_everything_return() -> dict[str, dict[str, str]]:
    """
    Specify nested parameterized types directly with the (type ) annotation.
    """
def test_ghash_nested_everything_return2() -> dict[str, dict[str, str]]:
    """
    Another way of specifying nested parameterized types: using the
    element-type annotation.
    """
def test_ghash_nothing_in(in_: dict[str, str]) -> None: ...
def test_ghash_nothing_in2(in_: dict[str, str]) -> None: ...
def test_ghash_nothing_return() -> dict[str, str]: ...
def test_ghash_nothing_return2() -> dict[str, str]: ...
def test_ghash_null_in(in_: dict[str, str] | None = ...) -> None: ...
def test_ghash_null_out() -> dict[str, str]: ...
def test_ghash_null_return() -> dict[str, str] | None: ...
def test_glist_boxed_full_return(count: int) -> list[TestBoxedC]: ...
def test_glist_boxed_none_return(count: int) -> list[TestBoxedC]: ...
def test_glist_container_return() -> list[str]: ...
def test_glist_everything_return() -> list[str]: ...
def test_glist_gtype_container_in(in_: list[type | GObject.Type]) -> None: ...
def test_glist_nothing_in(in_: list[str]) -> None: ...
def test_glist_nothing_in2(in_: list[str]) -> None: ...
def test_glist_nothing_return() -> list[str]: ...
def test_glist_nothing_return2() -> list[str]: ...
def test_glist_null_in(in_: list[str] | None = ...) -> None: ...
def test_glist_null_out() -> list[str]: ...
def test_gslist_container_return() -> list[str]: ...
def test_gslist_everything_return() -> list[str]: ...
def test_gslist_nothing_in(in_: list[str]) -> None: ...
def test_gslist_nothing_in2(in_: list[str]) -> None: ...
def test_gslist_nothing_return() -> list[str]: ...
def test_gslist_nothing_return2() -> list[str]: ...
def test_gslist_null_in(in_: list[str] | None = ...) -> None: ...
def test_gslist_null_out() -> list[str]: ...
def test_gtype(in_: type | GObject.Type) -> type | GObject.Type: ...
def test_gvalue_out_boxed(init: int) -> GObject.Value: ...
def test_gvariant_as() -> GLib.Variant: ...
def test_gvariant_asv() -> GLib.Variant: ...
def test_gvariant_i() -> GLib.Variant: ...
def test_gvariant_s() -> GLib.Variant: ...
def test_gvariant_v() -> GLib.Variant: ...
def test_hash_table_callback(data: dict[str, int], callback: TestCallbackHashtable) -> None: ...
def test_int(in_: int) -> int: ...
def test_int16(in_: int) -> int: ...
def test_int32(in_: int) -> int: ...
def test_int64(in_: int) -> int: ...
def test_int8(in_: int) -> int: ...
def test_int_out_utf8(in_: str) -> int: ...
def test_int_value_arg(v: GObject.Value) -> int: ...
def test_long(in_: int) -> int: ...
def test_multi_callback(callback: TestCallback | None = ...) -> int: ...
def test_multi_double_args(in_: float) -> tuple[float, float]: ...
def test_multiline_doc_comments() -> None:
    """
    This is a function.

    It has multiple lines in the documentation.

    The sky is blue.

    You will give me your credit card number.
    """
def test_nested_parameter(a: int) -> None:
    """
    <informaltable>
      <tgroup cols="3">
        <thead>
          <row>
            <entry>Syntax</entry>
            <entry>Explanation</entry>
            <entry>Examples</entry>
          </row>
        </thead>
        <tbody>
          <row>
            <entry>rgb(``r``, ``g``, ``b``)</entry>
            <entry>An opaque color; ``r``, ``g``, ``b`` can be either integers between
                   0 and 255 or percentages</entry>
            <entry><literallayout>rgb(128, 10, 54)
    rgb(20%, 30%, 0%)</literallayout></entry>
          </row>
          <row>
            <entry>rgba(``r``, ``g``, ``b``, ``a``)</entry>
            <entry>A translucent color; ``r``, ``g``, ``b`` are as in the previous row,
                   ``a`` is a floating point number between 0 and 1</entry>
            <entry><literallayout>rgba(255, 255, 0, 0.5)</literallayout></entry>
          </row>
       </tbody>
     </tgroup>
    </informaltable>

    What we're testing here is that the scanner ignores the ``a`` nested inside XML.
    """
def test_noptr_callback(callback: TestNoPtrCallback | None = ...) -> None: ...
def test_null_gerror_callback(callback: TestCallbackGError) -> None: ...
def test_null_strv_in_gvalue() -> GObject.Value: ...
def test_offt(in_: int) -> int: ...
def test_owned_gerror_callback(callback: TestCallbackOwnedGError) -> None: ...
def test_return_allow_none() -> str | None: ...
def test_return_nullable() -> str | None: ...
def test_short(in_: int) -> int: ...
def test_simple_boxed_a_const_return() -> TestSimpleBoxedA: ...
def test_simple_callback(callback: TestSimpleCallback | None = ...) -> None: ...
def test_size(in_: int) -> int: ...
def test_ssize(in_: int) -> int: ...
def test_struct_a_parse(string: str) -> TestStructA: ...
def test_strv_in(arr: list[str]) -> bool: ...
def test_strv_in_gvalue() -> GObject.Value: ...
def test_strv_out() -> list[str]: ...
def test_strv_out_c() -> list[str]: ...
def test_strv_out_container() -> list[str]: ...
def test_strv_outarg() -> list[str]: ...
def test_timet(in_: int) -> int: ...
def test_torture_signature_0(x: int, foo: str, m: int) -> tuple[float, int, int]: ...
def test_torture_signature_1(x: int, foo: str, m: int) -> tuple[bool, float, int, int]:
    """
    This function throws an error if m is odd.
    """
def test_torture_signature_2(x: int, callback: TestCallbackUserData, foo: str, m: int) -> tuple[float, int, int]: ...
def test_uint(in_: int) -> int: ...
def test_uint16(in_: int) -> int: ...
def test_uint32(in_: int) -> int: ...
def test_uint64(in_: int) -> int: ...
def test_uint8(in_: int) -> int: ...
def test_ulong(in_: int) -> int: ...
def test_unconventional_error_quark() -> GLib.Quark: ...
def test_unichar(in_: str) -> str: ...
def test_unsigned_enum_param(e: TestEnumUnsigned | int) -> str: ...
def test_ushort(in_: int) -> int: ...
def test_utf8_const_in(in_: str) -> None: ...
def test_utf8_const_return() -> str: ...
def test_utf8_inout(inout: str) -> str: ...
def test_utf8_nonconst_return() -> str: ...
def test_utf8_null_in(in_: str | None = ...) -> None: ...
def test_utf8_null_out() -> str: ...
def test_utf8_out() -> str: ...
def test_utf8_out_nonconst_return() -> tuple[str, str]: ...
def test_utf8_out_out() -> tuple[str, str]: ...
def test_value_return(i: int) -> GObject.Value: ...
@deprecated("Deprecated since 1.33.3.")
def test_versioning() -> None: ...
