# Auto-generated by ginext-stubgen from Vte-3.91.gir.
# Do not edit by hand.
# mypy: disable-error-code="override,type-arg,misc,valid-type"
from __future__ import annotations

import os
from collections.abc import Iterator
from typing_extensions import deprecated
from contextlib import AbstractContextManager
from typing import Any, Awaitable, Callable, ClassVar, Concatenate, Generic, Final, Literal, NamedTuple, ParamSpec as _ParamSpec, Self, TypeVar, override, overload
from enum import IntEnum, IntFlag
from ginext import GLib
from ginext import GObject
from ginext import Gdk
from ginext import Gio
from ginext import Gtk
from ginext import Pango
import cairo
from ginext.overlay.registrar import OverlayRegistrar as _OverlayRegistrar
from ginext.private import GIMeta as _GIMeta

overlay: _OverlayRegistrar
__version__: tuple[int, ...]
def __getattr__(name: str) -> Any: ...

_SigO = TypeVar('_SigO')
_SigP = _ParamSpec('_SigP')
_SigR = TypeVar('_SigR')

class SignalConnection:
    handler_id: int
    signal_name: str
    source: Any
    callback: Callable[..., Any]
    after: bool
    once: bool
    owner: Any
    is_connected: bool
    def disconnect(self) -> None: ...
    def blocked(self) -> AbstractContextManager[SignalConnection]: ...

class Signal(Generic[_SigO, _SigP, _SigR]):
    def __call__(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...
    def connect(self, handler: Callable[Concatenate[_SigO, _SigP], _SigR], *, after: bool = ..., once: bool = ..., owner: Any = ...) -> SignalConnection: ...
    def connect_after(self, handler: Callable[Concatenate[_SigO, _SigP], _SigR]) -> SignalConnection: ...
    def emit(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...
    def disconnect(self, connection: SignalConnection) -> None: ...
class SignalMethod(Signal[_SigO, _SigP, _SigR]):
    def __call__(self, *args: _SigP.args, **kwargs: _SigP.kwargs) -> _SigR: ...

class DetailedSignal(Signal[_SigO, _SigP, _SigR]):
    def __call__(self, detail: str | GObject.Property) -> 'Signal[_SigO, _SigP, _SigR]': ...

class Align(IntEnum):
    START = 0
    CENTER = 1
    END = 2

class CursorBlinkMode(IntEnum):
    SYSTEM = 0
    ON = 1
    OFF = 2

class CursorShape(IntEnum):
    BLOCK = 0
    IBEAM = 1
    UNDERLINE = 2

class EraseBinding(IntEnum):
    AUTO = 0
    ASCII_BACKSPACE = 1
    ASCII_DELETE = 2
    DELETE_SEQUENCE = 3
    TTY = 4

class FeatureFlags(IntFlag):
    FLAG_BIDI = 1
    FLAG_ICU = 2
    FLAG_SYSTEMD = 4
    FLAG_SIXEL = 8
    FLAGS_MASK = -1

class Format(IntEnum):
    TEXT = 1
    HTML = 2

class ProgressHint(IntEnum):
    INACTIVE = 0
    ACTIVE = 1
    ERROR = 2
    INDETERMINATE = 3
    PAUSED = 4

class PropertyFlags(IntFlag):
    NONE = 0
    EPHEMERAL = 1

class PropertyId(IntEnum):
    CURRENT_DIRECTORY_URI = 0
    CURRENT_FILE_URI = 1
    XTERM_TITLE = 2
    CONTAINER_NAME = 3
    CONTAINER_RUNTIME = 4
    CONTAINER_UID = 5
    SHELL_PRECMD = 6
    SHELL_PREEXEC = 7
    SHELL_POSTEXEC = 8
    PROGRESS_HINT = 9
    PROGRESS_VALUE = 10
    ICON_COLOR = 11
    ICON_IMAGE = 12

class PropertyType(IntEnum):
    VALUELESS = 0
    BOOL = 1
    INT = 2
    UINT = 3
    DOUBLE = 4
    RGB = 5
    RGBA = 6
    STRING = 7
    DATA = 8
    UUID = 9
    URI = 10
    IMAGE = 11

class PtyError(IntEnum):
    PTY_HELPER_FAILED = 0
    PTY98_FAILED = 1

class PtyFlags(IntFlag):
    NO_LASTLOG = 1
    NO_UTMP = 2
    NO_WTMP = 4
    NO_HELPER = 8
    NO_FALLBACK = 16
    NO_SESSION = 32
    NO_CTTY = 64
    DEFAULT = 0

class RegexError(IntEnum):
    INCOMPATIBLE = 2147483646
    NOT_SUPPORTED = 2147483647

class TextBlinkMode(IntEnum):
    NEVER = 0
    FOCUSED = 1
    UNFOCUSED = 2
    ALWAYS = 3

class UuidFormat(IntFlag):
    SIMPLE = 1
    BRACED = 2
    URN = 4
    ANY = 7

class WriteFlags(IntEnum):
    DEFAULT = 0

SelectionFunc = Callable[[Terminal, int, int], bool]
TerminalSpawnAsyncCallback = Callable[[Terminal, GLib.Pid, GLib.Error | None], None]
@deprecated("Deprecated since 0.68.")
class CharAttributes:
    gimeta: ClassVar[_GIMeta]
    row: int
    column: int
    fore: Pango.Color
    back: Pango.Color
    underline: int
    strikethrough: int
    columns: int

class EventContext:
    """
    Provides context information for a context menu event.
    """
    gimeta: ClassVar[_GIMeta]
    def get_coordinates(self, x: float | None = ..., y: float | None = ...) -> bool: ...

class Pty(GObject.Object, Gio.Initable):
    gimeta: ClassVar[_GIMeta]
    fd: int
    flags: PtyFlags | int
    def __init__(self, *, fd: int = ..., flags: PtyFlags | int = ..., **kwargs: Any) -> None: ...
    @classmethod
    def new_foreign_sync(cls, fd: int, cancellable: Gio.Cancellable | None = ...) -> Self:
        """
        Creates a new :class:`Vte.Pty` for the PTY master ``fd``.

        No entry will be made in the lastlog, utmp or wtmp system files.

        Note that the newly created :class:`Vte.Pty` will take ownership of ``fd``
        and close it on finalize.
        """
    @classmethod
    def new_sync(cls, flags: PtyFlags | int, cancellable: Gio.Cancellable | None = ...) -> Self:
        """
        Allocates a new pseudo-terminal.

        You can later use fork() or the g_spawn_async() family of functions
        to start a process on the PTY.

        If using fork(), you MUST call :meth:`Vte.Pty.child_setup` in the child.

        If using g_spawn_async() and friends, you MUST either use
        :meth:`Vte.Pty.child_setup` directly as the child setup function, or call
        :meth:`Vte.Pty.child_setup` from your own child setup function supplied.

        When using :meth:`Vte.Terminal.spawn_sync` with a custom child setup
        function, :meth:`Vte.Pty.child_setup` will be called before the supplied
        function; you must not call it again.

        Also, you MUST pass the ``G_SPAWN_DO_NOT_REAP_CHILD`` flag.

        Note also that ``G_SPAWN_STDOUT_TO_DEV_NULL``, ``G_SPAWN_STDERR_TO_DEV_NULL``,
        and ``G_SPAWN_CHILD_INHERITS_STDIN`` are not supported, since stdin, stdout
        and stderr of the child process will always be connected to the PTY.

        Note that you should set the PTY's size using :meth:`Vte.Pty.set_size` before
        spawning the child process, so that the child process has the correct
        size from the start instead of starting with a default size and then
        shortly afterwards receiving a <literal>SIGWINCH</literal> signal. You
        should prefer using :meth:`Vte.Terminal.pty_new_sync` which does this
        automatically.
        """
    def child_setup(self) -> None: ...
    @deprecated("Deprecated since 0.42.")
    def close(self) -> None:
        """
        Since 0.42 this is a no-op.
        """
    def get_fd(self) -> int: ...
    def get_size(self) -> tuple[bool, int, int]:
        """
        Reads the pseudo terminal's window size.

        If getting the window size failed, ``error`` will be set to a :class:`GIOError.`
        """
    def set_size(self, rows: int, columns: int) -> bool:
        """
        Attempts to resize the pseudo terminal's window size.  If successful, the
        OS kernel will send <literal>SIGWINCH</literal> to the child process group.

        If setting the window size failed, ``error`` will be set to a :class:`GIOError.`
        """
    def set_utf8(self, utf8: bool) -> bool:
        """
        Tells the kernel whether the terminal is UTF-8 or not, in case it can make
        use of the info.  Linux 2.6.5 or so defines IUTF8 to make the line
        discipline do multibyte backspace correctly.
        """
    @overload
    def spawn_async(self, working_directory: str | None, argv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]], envv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]] | None, spawn_flags: GLib.SpawnFlags | int, child_setup: GLib.SpawnChildSetupFunc | None, timeout: int, cancellable: Gio.Cancellable | None = ..., callback: None = ...) -> Awaitable[tuple[bool, GLib.Pid]]:
        """
        Like :meth:`Vte.Pty.spawn_with_fds_async`, except that this function does not
        allow passing file descriptors to the child process. See :meth:`Vte.Pty.spawn_with_fds_async`
        for more information.
        """
    @overload
    def spawn_async(self, working_directory: str | None, argv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]], envv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]] | None, spawn_flags: GLib.SpawnFlags | int, child_setup: GLib.SpawnChildSetupFunc | None, timeout: int, cancellable: Gio.Cancellable | None = ..., callback: Gio.AsyncReadyCallback = ...) -> None:
        """
        Like :meth:`Vte.Pty.spawn_with_fds_async`, except that this function does not
        allow passing file descriptors to the child process. See :meth:`Vte.Pty.spawn_with_fds_async`
        for more information.
        """
    def spawn_finish(self, result: Gio.AsyncResult) -> tuple[bool, GLib.Pid]: ...
    @overload
    def spawn_with_fds_async(self, working_directory: str | None, argv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]], envv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]] | None, fds: list[int] | None, map_fds: list[int] | None, spawn_flags: GLib.SpawnFlags | int, child_setup: GLib.SpawnChildSetupFunc | None, timeout: int, cancellable: Gio.Cancellable | None = ..., callback: None = ...) -> Awaitable[tuple[bool, GLib.Pid]]:
        """
        Starts the specified command under the pseudo-terminal ``pty``.
        The ``argv`` and ``envv`` lists should be ``None``-terminated.
        The "TERM" environment variable is automatically set to a default value,
        but can be overridden from ``envv``.
        ``pty_flags`` controls logging the session to the specified system log files.

        Note also that ``G_SPAWN_STDOUT_TO_DEV_NULL``, ``G_SPAWN_STDERR_TO_DEV_NULL``,
        and ``G_SPAWN_CHILD_INHERITS_STDIN`` are not supported in ``spawn_flags``, since
        stdin, stdout and stderr of the child process will always be connected to
        the PTY. Also ``G_SPAWN_LEAVE_DESCRIPTORS_OPEN`` is not supported; and
        ``G_SPAWN_DO_NOT_REAP_CHILD`` will always be added to ``spawn_flags``.

        If ``fds`` is not ``None``, the child process will map the file descriptors from
        ``fds`` according to ``map_fds``; ``n_map_fds`` must be less or equal to ``n_fds``.
        This function will take ownership of the file descriptors in ``fds``;
        you must not use or close them after this call. All file descriptors in ``fds``
        must have the FD_CLOEXEC flag set on them; it will be unset in the child process
        before calling man:execve(2). Note also that no file descriptor may be mapped
        to stdin, stdout, or stderr (file descriptors 0, 1, or 2), since these will be
        assigned to the PTY. All open file descriptors apart from those mapped as above
        will be closed when execve() is called.

        Beginning with 0.60, and on linux only, and unless :data:`Vte.SPAWN_NO_SYSTEMD_SCOPE` is
        passed in ``spawn_flags``, the newly created child process will be moved to its own
        systemd user scope; and if :data:`Vte.SPAWN_REQUIRE_SYSTEMD_SCOPE` is passed, and creation
        of the systemd user scope fails, the whole spawn will fail.
        You can override the options used for the systemd user scope by
        providing a systemd override file for 'vte-spawn-.scope' unit. See man:systemd.unit(5)
        for further information.

        See vte_pty_new(), and :meth:`Vte.Terminal.watch_child` for more information.
        """
    @overload
    def spawn_with_fds_async(self, working_directory: str | None, argv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]], envv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]] | None, fds: list[int] | None, map_fds: list[int] | None, spawn_flags: GLib.SpawnFlags | int, child_setup: GLib.SpawnChildSetupFunc | None, timeout: int, cancellable: Gio.Cancellable | None = ..., callback: Gio.AsyncReadyCallback = ...) -> None:
        """
        Starts the specified command under the pseudo-terminal ``pty``.
        The ``argv`` and ``envv`` lists should be ``None``-terminated.
        The "TERM" environment variable is automatically set to a default value,
        but can be overridden from ``envv``.
        ``pty_flags`` controls logging the session to the specified system log files.

        Note also that ``G_SPAWN_STDOUT_TO_DEV_NULL``, ``G_SPAWN_STDERR_TO_DEV_NULL``,
        and ``G_SPAWN_CHILD_INHERITS_STDIN`` are not supported in ``spawn_flags``, since
        stdin, stdout and stderr of the child process will always be connected to
        the PTY. Also ``G_SPAWN_LEAVE_DESCRIPTORS_OPEN`` is not supported; and
        ``G_SPAWN_DO_NOT_REAP_CHILD`` will always be added to ``spawn_flags``.

        If ``fds`` is not ``None``, the child process will map the file descriptors from
        ``fds`` according to ``map_fds``; ``n_map_fds`` must be less or equal to ``n_fds``.
        This function will take ownership of the file descriptors in ``fds``;
        you must not use or close them after this call. All file descriptors in ``fds``
        must have the FD_CLOEXEC flag set on them; it will be unset in the child process
        before calling man:execve(2). Note also that no file descriptor may be mapped
        to stdin, stdout, or stderr (file descriptors 0, 1, or 2), since these will be
        assigned to the PTY. All open file descriptors apart from those mapped as above
        will be closed when execve() is called.

        Beginning with 0.60, and on linux only, and unless :data:`Vte.SPAWN_NO_SYSTEMD_SCOPE` is
        passed in ``spawn_flags``, the newly created child process will be moved to its own
        systemd user scope; and if :data:`Vte.SPAWN_REQUIRE_SYSTEMD_SCOPE` is passed, and creation
        of the systemd user scope fails, the whole spawn will fail.
        You can override the options used for the systemd user scope by
        providing a systemd override file for 'vte-spawn-.scope' unit. See man:systemd.unit(5)
        for further information.

        See vte_pty_new(), and :meth:`Vte.Terminal.watch_child` for more information.
        """

class PtyClass:
    gimeta: ClassVar[_GIMeta]

class Regex:
    gimeta: ClassVar[_GIMeta]
    @classmethod
    def new_for_match(cls, pattern: str, pattern_length: int, flags: int) -> Self:
        """
        Compiles ``pattern`` into a regex for use as a match regex
        with :meth:`Vte.Terminal.match_add_regex` or
        vte_terminal_event_check_regex_simple().

        See man:pcre2pattern(3) for information
        about the supported regex language, and man:pcre2api(3) for
        information about the supported ``flags``.

        The regex will be compiled using <literal>PCRE2_UTF</literal> and
        possibly other flags, in addition to the flags supplied in ``flags``.
        """
    @classmethod
    def new_for_match_full(cls, pattern: str, pattern_length: int, flags: int, extra_flags: int) -> tuple[Self, int]:
        """
        Compiles ``pattern`` into a regex for use as a match regex
        with :meth:`Vte.Terminal.match_add_regex` or
        vte_terminal_event_check_regex_simple().

        See man:pcre2pattern(3) for information
        about the supported regex language, and man:pcre2api(3) for
        information about the supported ``flags`` and ``extra_flags``.

        The regex will be compiled using <literal>PCRE2_UTF</literal> and
        possibly other flags, in addition to the flags supplied in ``flags``.

        If regex compilation fails, ``error`` will be set and ``error_offset`` point
        to error as an offset into ``pattern``.
        """
    @classmethod
    def new_for_search(cls, pattern: str, pattern_length: int, flags: int) -> Self:
        """
        Compiles ``pattern`` into a regex for use as a search regex
        with :meth:`Vte.Terminal.search_set_regex`.

        See man:pcre2pattern(3) for information
        about the supported regex language, and man:pcre2api(3) for
        information about the supported ``flags``.

        The regex will be compiled using <literal>PCRE2_UTF</literal> and
        possibly other flags, in addition to the flags supplied in ``flags``.
        """
    @classmethod
    def new_for_search_full(cls, pattern: str, pattern_length: int, flags: int, extra_flags: int) -> tuple[Self, int]:
        """
        Compiles ``pattern`` into a regex for use as a search regex
        with :meth:`Vte.Terminal.search_set_regex`.

        See man:pcre2pattern(3) for information
        about the supported regex language, and man:pcre2api(3) for
        information about the supported ``flags`` and ``extra_flags``.

        The regex will be compiled using <literal>PCRE2_UTF</literal> and
        possibly other flags, in addition to the flags supplied in ``flags``.

        If regex compilation fails, ``error`` will be set and ``error_offset`` point
        to error as an offset into ``pattern``.
        """
    def jit(self, flags: int) -> bool:
        """
        If the platform supports JITing, JIT compiles ``regex``.
        """
    def ref(self) -> Regex:
        """
        Increases the reference count of ``regex`` by one.
        """
    def substitute(self, subject: str, replacement: str, flags: int) -> str:
        """
        See man:pcre2api(3) and man:pcre2_substitute(3) for more information.
        """
    def unref(self) -> Regex:
        """
        Decreases the reference count of ``regex`` by one, and frees ``regex``
        if the refcount reaches zero.
        """

class Terminal(Gtk.Widget, Gtk.Accessible, Gtk.AccessibleText, Gtk.Buildable, Gtk.ConstraintTarget, Gtk.Scrollable):
    gimeta: ClassVar[_GIMeta]
    @deprecated("Deprecated since 0.60.")
    @property
    def allow_bold(self) -> bool: ...
    allow_hyperlink: bool
    audible_bell: bool
    backspace_binding: EraseBinding | int
    bold_is_bright: bool
    cell_height_scale: float
    cell_width_scale: float
    cjk_ambiguous_width: int
    context_menu: Gtk.Popover
    context_menu_model: Gio.MenuModel
    @deprecated("Deprecated since 0.78.")
    @property
    def current_directory_uri(self) -> str: ...
    @deprecated("Deprecated since 0.78.")
    @property
    def current_file_uri(self) -> str: ...
    cursor_blink_mode: CursorBlinkMode | int
    cursor_shape: CursorShape | int
    delete_binding: EraseBinding | int
    enable_a11y: bool
    enable_bidi: bool
    enable_fallback_scrolling: bool
    enable_legacy_osc777: bool
    enable_shaping: bool
    enable_sixel: bool
    @deprecated("Deprecated since 0.54.")
    @property
    def encoding(self) -> str: ...
    font_desc: Pango.FontDescription
    font_options: cairo.FontOptions
    font_scale: float
    hyperlink_hover_uri: str
    @deprecated("Deprecated since 0.54.")
    @property
    def icon_title(self) -> str: ...
    input_enabled: bool
    pointer_autohide: bool
    pty: Pty
    @deprecated("Deprecated since 0.58.")
    @property
    def rewrap_on_resize(self) -> bool: ...
    scroll_on_insert: bool
    scroll_on_keystroke: bool
    scroll_on_output: bool
    scroll_unit_is_pixels: bool
    scrollback_lines: int
    text_blink_mode: TextBlinkMode | int
    @deprecated("Deprecated since 0.78.")
    @property
    def window_title(self) -> str: ...
    word_char_exceptions: str
    xalign: Align | int
    xfill: bool
    yalign: Align | int
    yfill: bool
    def __init__(self, *, allow_bold: bool = ..., allow_hyperlink: bool = ..., audible_bell: bool = ..., backspace_binding: EraseBinding | int = ..., bold_is_bright: bool = ..., cell_height_scale: float = ..., cell_width_scale: float = ..., cjk_ambiguous_width: int = ..., context_menu: Gtk.Popover = ..., context_menu_model: Gio.MenuModel = ..., cursor_blink_mode: CursorBlinkMode | int = ..., cursor_shape: CursorShape | int = ..., delete_binding: EraseBinding | int = ..., enable_a11y: bool = ..., enable_bidi: bool = ..., enable_fallback_scrolling: bool = ..., enable_legacy_osc777: bool = ..., enable_shaping: bool = ..., enable_sixel: bool = ..., encoding: str = ..., font_desc: Pango.FontDescription = ..., font_options: cairo.FontOptions = ..., font_scale: float = ..., input_enabled: bool = ..., pointer_autohide: bool = ..., pty: Pty = ..., rewrap_on_resize: bool = ..., scroll_on_insert: bool = ..., scroll_on_keystroke: bool = ..., scroll_on_output: bool = ..., scroll_unit_is_pixels: bool = ..., scrollback_lines: int = ..., text_blink_mode: TextBlinkMode | int = ..., xalign: Align | int = ..., xfill: bool = ..., yalign: Align | int = ..., yfill: bool = ..., **kwargs: Any) -> None: ...
    @classmethod
    def new(cls, *args: Any, **kwargs: Any) -> Self: ...
    def check_hyperlink_at(self, x: float, y: float) -> str | None:
        """
        Returns a nonempty string: the target of the explicit hyperlink (printed using the OSC 8
        escape sequence) at the position (x, y), or ``None``.

        Proper use of the escape sequence should result in URI-encoded URIs with a proper scheme
        like "http://", "https://", "file://", "mailto:" etc. This is, however, not enforced by VTE.
        The caller must tolerate the returned string potentially not being a valid URI.
        """
    def check_match_at(self, x: float, y: float) -> tuple[str | None, int]:
        """
        Checks if the text in and around the position (x, y) matches any of the
        regular expressions previously set using vte_terminal_match_add().  If a
        match exists, the text string is returned and if ``tag`` is not ``None``, the number
        associated with the matched regular expression will be stored in ``tag``.

        If more than one regular expression has been set with
        vte_terminal_match_add(), then expressions are checked in the order in
        which they were added.
        """
    def check_regex_simple_at(self, x: float, y: float, regexes: list[Regex], match_flags: int) -> list[str] | None:
        """
        Like vte_terminal_check_regex_simple_at(), but returns an array of strings,
        containing the matching text (or ``None`` if no match) corresponding to each of the
        regexes in ``regexes``.

        You must free each string and the array; but note that this is *not* a ``None``-terminated
        string array, and so you must *not* use g_strfreev() on it.
        """
    def copy_clipboard_format(self, format: Format | int) -> None:
        """
        Places the selected text in the terminal in the :class:`GDK_SELECTION_CLIPBOARD`
        selection in the form specified by ``format``.

        For all formats, the selection data (see :class:`GtkSelectionData`) will include the
        text targets (see gtk_target_list_add_text_targets() and
        gtk_selection_data_targets_includes_text()). For :data:`Vte.Format.HTML`,
        the selection will also include the "text/html" target, which when requested,
        returns the HTML data in UTF-16 with a U+FEFF BYTE ORDER MARK character at
        the start.
        """
    def copy_primary(self) -> None:
        """
        Places the selected text in the terminal in the :class:`GDK_SELECTION_PRIMARY`
        selection.
        """
    def dup_termprop_string(self, prop: str) -> tuple[str | None, int]:
        """
        Returns the value of a :data:`Vte.PropertyType.STRING` termprop, or ``None`` if
          ``prop`` is unset, or ``prop`` is not a registered property.
        """
    def dup_termprop_string_by_id(self, prop: int) -> tuple[str | None, int]:
        """
        Like :meth:`Vte.Terminal.dup_termprop_string` except that it takes the termprop
        by ID. See that function for more information.
        """
    def dup_termprop_uuid(self, prop: str) -> Uuid | None:
        """
        Returns the value of a :data:`Vte.PropertyType.UUID` termprop as a :class:`Vte.Uuid`, or ``None`` if
          ``prop`` is unset, or ``prop`` is not a registered property.
        """
    def dup_termprop_uuid_by_id(self, prop: int) -> Uuid | None:
        """
        Like :meth:`Vte.Terminal.dup_termprop_uuid` except that it takes the termprop
        by ID. See that function for more information.
        """
    def feed(self, data: list[int] | None = ...) -> None:
        """
        Interprets ``data`` as if it were data received from a child process.
        """
    def feed_child(self, text: list[int] | None = ...) -> None:
        """
        Sends a block of UTF-8 text to the child as if it were entered by the user
        at the keyboard.
        """
    @deprecated("Deprecated since 0.60.")
    def feed_child_binary(self, data: list[int] | None = ...) -> None:
        """
        Sends a block of binary data to the child.
        """
    @deprecated("Deprecated since 0.60.")
    def get_allow_bold(self) -> bool:
        """
        Checks whether or not the terminal will attempt to draw bold text,
        by using a bold font variant.
        """
    def get_allow_hyperlink(self) -> bool:
        """
        Checks whether or not hyperlinks (OSC 8 escape sequence) are allowed.
        """
    def get_audible_bell(self) -> bool:
        """
        Checks whether or not the terminal will beep when the child outputs the
        "bl" sequence.
        """
    def get_bold_is_bright(self) -> bool:
        """
        Checks whether the SGR 1 attribute also switches to the bright counterpart
        of the first 8 palette colors, in addition to making them bold (legacy behavior)
        or if SGR 1 only enables bold and leaves the color intact.
        """
    def get_cell_height_scale(self) -> float: ...
    def get_cell_width_scale(self) -> float: ...
    def get_char_height(self) -> int: ...
    def get_char_width(self) -> int: ...
    def get_cjk_ambiguous_width(self) -> int:
        """
        Returns whether ambiguous-width characters are narrow or wide.
        (Note that when using a non-UTF-8 encoding set via :meth:`Vte.Terminal.set_encoding`,
        the width of ambiguous-width characters is fixed and determined by the encoding
        itself.)
        """
    def get_color_background_for_draw(self) -> Gdk.RGBA:
        """
        Returns the background colour, as used by ``terminal`` when
        drawing the background, which may be different from
        the color set by :meth:`Vte.Terminal.set_color_background`.

        Note: you must only call this function while handling the
        GtkWidget::draw signal.

        This function is rarely useful. One use for it is if you disable
        drawing the background (see :meth:`Vte.Terminal.set_clear_background`)
        and then need to draw the background yourself.
        """
    def get_column_count(self) -> int: ...
    def get_context_menu(self) -> Gtk.Widget | None: ...
    def get_context_menu_model(self) -> Gio.MenuModel | None: ...
    @deprecated("Deprecated since 0.78.")
    def get_current_directory_uri(self) -> str | None: ...
    @deprecated("Deprecated since 0.78.")
    def get_current_file_uri(self) -> str | None: ...
    def get_cursor_blink_mode(self) -> CursorBlinkMode:
        """
        Returns the currently set cursor blink mode.
        """
    def get_cursor_position(self) -> tuple[int, int]:
        """
        Reads the location of the insertion cursor and returns it.  The row
        coordinate is absolute.

        This method is unaware of BiDi. The returned column is logical column.
        """
    def get_cursor_shape(self) -> CursorShape:
        """
        Returns the currently set cursor shape.
        """
    def get_enable_a11y(self) -> bool:
        """
        Checks whether the terminal communicates with a11y backends
        """
    def get_enable_bidi(self) -> bool:
        """
        Checks whether the terminal performs bidirectional text rendering.
        """
    def get_enable_fallback_scrolling(self) -> bool: ...
    def get_enable_legacy_osc777(self) -> bool: ...
    def get_enable_shaping(self) -> bool:
        """
        Checks whether the terminal shapes Arabic text.
        """
    def get_enable_sixel(self) -> bool: ...
    @deprecated("Deprecated since 0.54.")
    def get_encoding(self) -> str | None:
        """
        Determines the name of the encoding in which the terminal expects data to be
        encoded, or ``None`` if UTF-8 is in use.
        """
    def get_font(self) -> Pango.FontDescription:
        """
        Queries the terminal for information about the fonts which will be
        used to draw text in the terminal.  The actual font takes the font scale
        into account, this is not reflected in the return value, the unscaled
        font is returned.
        """
    def get_font_options(self) -> cairo.FontOptions | None: ...
    def get_font_scale(self) -> float: ...
    def get_has_selection(self) -> bool:
        """
        Checks if the terminal currently contains selected text.  Note that this
        is different from determining if the terminal is the owner of any
        :class:`GtkClipboard` items.
        """
    @deprecated("Deprecated since 0.54.")
    def get_icon_title(self) -> str | None: ...
    def get_input_enabled(self) -> bool:
        """
        Returns whether the terminal allow user input.
        """
    def get_mouse_autohide(self) -> bool:
        """
        Determines the value of the terminal's mouse autohide setting.  When
        autohiding is enabled, the mouse cursor will be hidden when the user presses
        a key and shown when the user moves the mouse.  This setting can be changed
        using :meth:`Vte.Terminal.set_mouse_autohide`.
        """
    def get_pty(self) -> Pty | None:
        """
        Returns the :class:`Vte.Pty` of ``terminal``.
        """
    @deprecated("Deprecated since 0.58.")
    def get_rewrap_on_resize(self) -> bool:
        """
        Checks whether or not the terminal will rewrap its contents upon resize.
        """
    def get_row_count(self) -> int: ...
    def get_scroll_on_insert(self) -> bool: ...
    def get_scroll_on_keystroke(self) -> bool: ...
    def get_scroll_on_output(self) -> bool: ...
    def get_scroll_unit_is_pixels(self) -> bool: ...
    def get_scrollback_lines(self) -> int: ...
    def get_termprop_bool(self, prop: str) -> tuple[bool, bool]:
        """
        For a :data:`Vte.PropertyType.BOOL` termprop, sets ``value`` to ``prop``'s value,
          or to ``False`` if ``prop`` is unset, or ``prop`` is not a registered property.
        """
    def get_termprop_bool_by_id(self, prop: int) -> tuple[bool, bool]:
        """
        Like :meth:`Vte.Terminal.get_termprop_bool` except that it takes the termprop
        by ID. See that function for more information.
        """
    def get_termprop_data(self, prop: str) -> list[int] | None:
        """
        Returns the value of a :data:`Vte.PropertyType.DATA` termprop, or ``None`` if
          ``prop`` is unset, or ``prop`` is not a registered property.
        """
    def get_termprop_data_by_id(self, prop: int) -> list[int] | None:
        """
        Like :meth:`Vte.Terminal.get_termprop_data` except that it takes the termprop
        by ID. See that function for more information.
        """
    def get_termprop_double(self, prop: str) -> tuple[bool, float]:
        """
        For a :data:`Vte.PropertyType.DOUBLE` termprop, sets ``value`` to ``prop``'s value,
          which is finite; or to 0.0 if ``prop`` is unset, or ``prop`` is not a
          registered property.
        """
    def get_termprop_double_by_id(self, prop: int) -> tuple[bool, float]:
        """
        Like :meth:`Vte.Terminal.get_termprop_double` except that it takes the termprop
        by ID. See that function for more information.
        """
    def get_termprop_enum(self, prop: str, gtype: type | GObject.Type) -> tuple[bool, int]:
        """
        See vte_properties_get_property_enum() for more information.
        """
    def get_termprop_enum_by_id(self, prop: int, gtype: type | GObject.Type) -> tuple[bool, int]:
        """
        Like :meth:`Vte.Terminal.get_termprop_enum` except that it takes the property
        by ID. See that function for more information.
        """
    def get_termprop_flags(self, prop: str, gtype: type | GObject.Type, ignore_unknown_flags: bool) -> tuple[bool, int]:
        """
        See vte_properties_get_property_flags() for more information.
        """
    def get_termprop_flags_by_id(self, prop: int, gtype: type | GObject.Type, ignore_unknown_flags: bool) -> tuple[bool, int]:
        """
        Like :meth:`Vte.Terminal.get_termprop_flags` except that it takes the property
        by ID. See that function for more information.
        """
    def get_termprop_int(self, prop: str) -> tuple[bool, int]:
        """
        For a :data:`Vte.PropertyType.INT` termprop, sets ``value`` to ``prop``'s value,
        or to 0 if ``prop`` is unset, or if ``prop`` is not a registered property.

        If only a subset or range of values are acceptable for the given property,
        the caller must validate the returned value and treat any out-of-bounds
        value as if the termprop had no value; in particular it *must not* clamp
        the values to the expected range.
        """
    def get_termprop_int_by_id(self, prop: int) -> tuple[bool, int]:
        """
        Like :meth:`Vte.Terminal.get_termprop_int` except that it takes the termprop
        by ID. See that function for more information.
        """
    def get_termprop_rgba(self, prop: str) -> tuple[bool, Gdk.RGBA]:
        """
        Stores the value of a :data:`Vte.PropertyType.RGB` or :data:`Vte.PropertyType.RGBA` termprop in ``color`` and
        returns ``True`` if the termprop is set, or stores rgb(0,0,0) or rgba(0,0,0,1) in ``color``
        and returns ``False`` if the termprop is unset.
        """
    def get_termprop_rgba_by_id(self, prop: int) -> tuple[bool, Gdk.RGBA]:
        """
        Like :meth:`Vte.Terminal.get_termprop_rgba` except that it takes the termprop
        by ID. See that function for more information.
        """
    def get_termprop_string(self, prop: str) -> tuple[str | None, int]:
        """
        Returns the value of a :data:`Vte.PropertyType.STRING` termprop, or ``None`` if
          ``prop`` is unset, or ``prop`` is not a registered property.
        """
    def get_termprop_string_by_id(self, prop: int) -> tuple[str | None, int]:
        """
        Like :meth:`Vte.Terminal.get_termprop_string` except that it takes the termprop
        by ID. See that function for more information.
        """
    def get_termprop_uint(self, prop: str) -> tuple[bool, int]:
        """
        For a :data:`Vte.PropertyType.UINT` termprop, sets ``value`` to ``prop``'s value,
        or to 0 if ``prop`` is unset, or ``prop`` is not a registered property.

        If only a subset or range of values are acceptable for the given property,
        the caller must validate the returned value and treat any out-of-bounds
        value as if the termprop had no value; in particular it *must not* clamp
        the values to the expected range.
        """
    def get_termprop_uint_by_id(self, prop: int) -> tuple[bool, int]:
        """
        Like :meth:`Vte.Terminal.get_termprop_uint` except that it takes the termprop
        by ID. See that function for more information.
        """
    def get_termprop_value(self, prop: str) -> tuple[bool, GObject.Value]:
        """
        Returns ``True`` with the value of ``prop`` stored in ``value`` (if not ``None``) if,
          the termprop has a value, or ``False`` if ``prop`` is unset, or ``prop`` is not
          a registered property; in that case ``value`` will not be set.

        The value type returned depends on the termprop type:
        * A :data:`Vte.PropertyType.VALUELESS` termprop stores no value, and returns ``False``
          from this function.
        * A :data:`Vte.PropertyType.BOOL` termprop stores a ``G_TYPE_BOOLEAN`` value.
        * A :data:`Vte.PropertyType.INT` termprop stores a ``G_TYPE_INT64`` value.
        * A :data:`Vte.PropertyType.UINT` termprop stores a ``G_TYPE_UINT64`` value.
        * A :data:`Vte.PropertyType.DOUBLE` termprop stores a ``G_TYPE_DOUBLE`` value.
        * A :data:`Vte.PropertyType.RGB` termprop stores a boxed :class:`GdkRGBA` value with alpha 1.0 on gtk3,
           and nothing on gtk4.
        * A :data:`Vte.PropertyType.RGBA` termprop stores a boxed :class:`GdkRGBA` value on gtk3,
           and nothing on gtk4.
        * A :data:`Vte.PropertyType.STRING` termprop stores a ``G_TYPE_STRING`` value.
        * A :data:`Vte.PropertyType.DATA` termprop stores a boxed :class:`GBytes` value.
        * A :data:`Vte.PropertyType.UUID` termprop stores a boxed :class:`Vte.Uuid` value.
        * A :data:`Vte.PropertyType.URI` termprop stores a boxed :class:`GUri` value.
        * A :data:`Vte.PropertyType.IMAGE` termprop stores a boxed #cairo_surface_t value on gtk3,
            and a boxed :class:`GdkTexture` on gtk4
        """
    def get_termprop_value_by_id(self, prop: int) -> tuple[bool, GObject.Value]:
        """
        Like :meth:`Vte.Terminal.get_termprop_value` except that it takes the termprop
        by ID. See that function for more information.
        """
    @deprecated("Deprecated since 0.76.")
    def get_text(self, is_selected: SelectionFunc | None = ...) -> tuple[str | None, list[CharAttributes]]:
        """
        Extracts a view of the visible part of the terminal.

        This method is unaware of BiDi. The columns returned in ``attributes`` are
        logical columns.

        Note: since 0.68, passing a non-``None`` ``attributes`` parameter is deprecated. Starting with
        0.72, passing a non-``None`` ``attributes`` parameter will make this function itself return ``None``.
        Since 0.72, passing a non-``None`` ``is_selected`` parameter will make this function itself return ``None``.
        """
    def get_text_blink_mode(self) -> TextBlinkMode:
        """
        Checks whether or not the terminal will allow blinking text.
        """
    def get_text_format(self, format: Format | int) -> str | None:
        """
        Returns text from the visible part of the terminal in the specified format.

        This method is unaware of BiDi. The columns returned in ``attributes`` are
        logical columns.
        """
    @deprecated("Deprecated since 0.56.")
    def get_text_include_trailing_spaces(self, is_selected: SelectionFunc | None = ...) -> tuple[str, list[CharAttributes]]:
        """
        Extracts a view of the visible part of the terminal.

        This method is unaware of BiDi. The columns returned in ``attributes`` are
        logical columns.

        Note: since 0.68, passing a non-``None`` ``array`` parameter is deprecated. Starting with
        0.72, passing a non-``None`` ``array`` parameter will make this function itself return ``None``.
        Since 0.72, passing a non-``None`` ``is_selected`` parameter will make this function itself return ``None``.
        """
    @deprecated("Deprecated since 0.76.")
    def get_text_range(self, start_row: int, start_col: int, end_row: int, end_col: int, is_selected: SelectionFunc | None = ...) -> tuple[str | None, list[CharAttributes]]:
        """
        Extracts a view of the visible part of the terminal. The
        entire scrollback buffer is scanned, so it is possible to read the entire
        contents of the buffer using this function.

        This method is unaware of BiDi. The columns passed in ``start_col`` and ``end_row``,
        and returned in ``attributes`` are logical columns.

        Since 0.68, passing a non-``None`` ``array`` parameter is deprecated.
        Since 0.72, passing a non-``None`` ``array`` parameter will make this function
          itself return ``None``.
        Since 0.72, passing a non-``None`` ``is_selected`` function will make this function
          itself return ``None``.
        """
    def get_text_range_format(self, format: Format | int, start_row: int, start_col: int, end_row: int, end_col: int) -> tuple[str | None, int]:
        """
        Returns the specified range of text in the specified format.
        """
    def get_text_selected(self, format: Format | int) -> str | None:
        """
        Gets the currently selected text in the format specified by ``format``.
        Since 0.72, this function also supports :data:`Vte.Format.HTML` format.
        """
    def get_text_selected_full(self, format: Format | int) -> tuple[str | None, int]:
        """
        Gets the currently selected text in the format specified by ``format``.
        """
    @deprecated("Deprecated since 0.78.")
    def get_window_title(self) -> str | None: ...
    def get_word_char_exceptions(self) -> str | None:
        """
        Returns the set of characters which will be considered parts of a word
        when doing word-wise selection, in addition to the default which only
        considers alphanumeric characters part of a word.

        If ``None``, a built-in set is used.
        """
    def get_xalign(self) -> Align: ...
    def get_xfill(self) -> bool: ...
    def get_yalign(self) -> Align: ...
    def get_yfill(self) -> bool: ...
    def match_add_regex(self, regex: Regex, flags: int) -> int:
        """
        Adds the regular expression ``regex`` to the list of matching expressions.  When the
        user moves the mouse cursor over a section of displayed text which matches
        this expression, the text will be highlighted.

        Note that ``regex`` should have been created using the <literal>PCRE2_MULTILINE</literal>
        flag.
        """
    @deprecated("Deprecated since 0.46.")
    def match_check(self, column: int, row: int) -> tuple[str | None, int]:
        """
        Checks if the text in and around the specified position matches any of the
        regular expressions previously set using vte_terminal_match_add().  If a
        match exists, the text string is returned and if ``tag`` is not ``None``, the number
        associated with the matched regular expression will be stored in ``tag``.

        If more than one regular expression has been set with
        vte_terminal_match_add(), then expressions are checked in the order in
        which they were added.
        """
    def match_remove(self, tag: int) -> None:
        """
        Removes the regular expression which is associated with the given ``tag`` from
        the list of expressions which the terminal will highlight when the user
        moves the mouse cursor over matching text.
        """
    def match_remove_all(self) -> None:
        """
        Clears the list of regular expressions the terminal uses to highlight text
        when the user moves the mouse cursor.
        """
    @deprecated("Deprecated since 0.40.")
    def match_set_cursor(self, tag: int, cursor: Gdk.Cursor | None = ...) -> None:
        """
        Sets which cursor the terminal will use if the pointer is over the pattern
        specified by ``tag``.  The terminal keeps a reference to ``cursor``.
        """
    def match_set_cursor_name(self, tag: int, cursor_name: str) -> None:
        """
        Sets which cursor the terminal will use if the pointer is over the pattern
        specified by ``tag``.
        """
    def paste_primary(self) -> None:
        """
        Sends the contents of the :class:`GDK_SELECTION_PRIMARY` selection to the terminal's
        child. The terminal will call also paste the
        :class:`GDK_SELECTION_PRIMARY` selection when the user clicks with the the second
        mouse button.
        """
    def paste_text(self, text: str) -> None:
        """
        Sends ``text`` to the terminal's child as if retrived from the clipboard,
        this differs from :meth:`Vte.Terminal.feed_child` in that it may process
        ``text`` before passing it to the child (e.g. apply bracketed mode)
        """
    def pty_new_sync(self, flags: PtyFlags | int, cancellable: Gio.Cancellable | None = ...) -> Pty:
        """
        Creates a new :class:`Vte.Pty`, sets the emulation property
        from :class:`Vte.Terminal`:emulation, and sets the size using
        ``terminal``'s size.

        See vte_pty_new() for more information.
        """
    def ref_termprop_data_bytes(self, prop: str) -> bytes | None:
        """
        Returns the value of a :data:`Vte.PropertyType.DATA` termprop as a :class:`GBytes`, or ``None`` if
          ``prop`` is unset, or ``prop`` is not a registered property.
        """
    def ref_termprop_data_bytes_by_id(self, prop: int) -> bytes | None:
        """
        Like :meth:`Vte.Terminal.ref_termprop_data_bytes` except that it takes the termprop
        by ID. See that function for more information.
        """
    def ref_termprop_image_surface(self, prop: str) -> cairo.Surface | None:
        """
        Returns the value of a :data:`Vte.PropertyType.IMAGE` termprop as a #cairo_surface_t,
          or ``None`` if ``prop`` is unset, or ``prop`` is not a registered property.

        The surface will be a ``CAIRO_SURFACE_TYPE_IMAGE`` with format
        ``CAIRO_FORMAT_ARGB32`` or ``CAIRO_FORMAT_RGB24``.

        Note that the returned surface is owned by ``terminal`` and its contents
        must not be modified.
        """
    def ref_termprop_image_surface_by_id(self, prop: int) -> cairo.Surface | None:
        """
        Like :meth:`Vte.Terminal.ref_termprop_image_surface` except that it takes the
        termprop by ID. See that function for more information.
        """
    def ref_termprop_image_texture(self, prop: str) -> Gdk.Texture | None:
        """
        Returns the value of a :data:`Vte.PropertyType.IMAGE` termprop as a :class:`GdkTexture`, or ``None`` if
          ``prop`` is unset, or ``prop`` is not a registered property.
        """
    def ref_termprop_image_texture_by_id(self, prop: int) -> Gdk.Texture | None:
        """
        Like :meth:`Vte.Terminal.ref_termprop_image_texture` except that it takes the
        termprop by ID. See that function for more information.
        """
    def ref_termprop_uri(self, prop: str) -> GLib.Uri | None:
        """
        Returns the value of a :data:`Vte.PropertyType.URI` termprop as a :class:`GUri`, or ``None`` if
          ``prop`` is unset, or ``prop`` is not a registered property.
        """
    def ref_termprop_uri_by_id(self, prop: int) -> GLib.Uri | None:
        """
        Like :meth:`Vte.Terminal.ref_termprop_uri` except that it takes the termprop
        by ID. See that function for more information.
        """
    def ref_termprop_variant(self, prop: str) -> GLib.Variant | None:
        """
        Returns the value of ``prop`` as a :class:`GVariant`, or ``None`` if
          ``prop`` unset, or ``prop`` is not a registered property.

        The :class:`GVariantType` of the returned :class:`GVariant` depends on the termprop type:
        * A :data:`Vte.PropertyType.VALUELESS` termprop returns a ``G_VARIANT_TYPE_UNIT`` variant.
        * A :data:`Vte.PropertyType.BOOL` termprop returns a ``G_VARIANT_TYPE_BOOLEAN`` variant.
        * A :data:`Vte.PropertyType.INT` termprop returns a ``G_VARIANT_TYPE_INT64`` variant.
        * A :data:`Vte.PropertyType.UINT` termprop returns a ``G_VARIANT_TYPE_UINT64`` variant.
        * A :data:`Vte.PropertyType.DOUBLE` termprop returns a ``G_VARIANT_TYPE_DOUBLE`` variant.
        * A :data:`Vte.PropertyType.RGB` or :data:`Vte.PropertyType.RGBA` termprop returns a "(ddddv)"
          tuple containing the red, green, blue, and alpha (1.0 for :data:`Vte.PropertyType.RGB`)
          components of the color and a variant of unspecified contents
        * A :data:`Vte.PropertyType.STRING` termprop returns a ``G_VARIANT_TYPE_STRING`` variant.
        * A :data:`Vte.PropertyType.DATA` termprop returns a "ay" variant (which is *not* a bytestring!).
        * A :data:`Vte.PropertyType.UUID` termprop returns a ``G_VARIANT_TYPE_STRING`` variant
          containing a string representation of the UUID in simple form.
        * A :data:`Vte.PropertyType.URI` termprop returns a ``G_VARIANT_TYPE_STRING`` variant
          containing a string representation of the URI
        * A :data:`Vte.PropertyType.IMAGE` termprop returns ``None`` since an image has no
          variant representation.
        """
    def ref_termprop_variant_by_id(self, prop: int) -> GLib.Variant | None:
        """
        Like :meth:`Vte.Terminal.ref_termprop_variant` except that it takes the termprop
        by ID. See that function for more information.
        """
    def reset(self, clear_tabstops: bool, clear_history: bool) -> None:
        """
        Resets as much of the terminal's internal state as possible, discarding any
        unprocessed input data, resetting character attributes, cursor state,
        national character set state, status line, terminal modes (insert/delete),
        selection state, and encoding.
        """
    def reset_termprop(self, prop: str) -> None:
        """
        Resets the termprop ``prop`` to its default value.
        """
    def reset_termprop_by_id(self, prop: int) -> None:
        """
        Like :meth:`Vte.Terminal.reset_termprop` except that it takes the termprop
        by ID. See that function for more information.
        """
    def search_find_next(self) -> bool:
        """
        Searches the next string matching the search regex set with
        :meth:`Vte.Terminal.search_set_regex`.
        """
    def search_find_previous(self) -> bool:
        """
        Searches the previous string matching the search regex set with
        :meth:`Vte.Terminal.search_set_regex`.
        """
    def search_get_regex(self) -> Regex: ...
    def search_get_wrap_around(self) -> bool: ...
    def search_set_regex(self, regex: Regex | None, flags: int) -> None:
        """
        Sets the regex to search for. Unsets the search regex when passed ``None``.

        Note that ``regex`` should have been created using the
        <literal>PCRE2_MULTILINE</literal> flag.
        """
    def search_set_wrap_around(self, wrap_around: bool) -> None:
        """
        Sets whether search should wrap around to the beginning of the
        terminal content when reaching its end.
        """
    def select_all(self) -> None:
        """
        Selects all text within the terminal (not including the scrollback buffer).
        """
    @deprecated("Deprecated since 0.60.")
    def set_allow_bold(self, allow_bold: bool) -> None:
        """
        Controls whether or not the terminal will attempt to draw bold text,
        by using a bold font variant.
        """
    def set_allow_hyperlink(self, allow_hyperlink: bool) -> None:
        """
        Controls whether or not hyperlinks (OSC 8 escape sequence) are allowed.
        """
    def set_audible_bell(self, is_audible: bool) -> None:
        """
        Controls whether or not the terminal will beep when the child outputs the
        "bl" sequence.
        """
    def set_backspace_binding(self, binding: EraseBinding | int) -> None:
        """
        Modifies the terminal's backspace key binding, which controls what
        string or control sequence the terminal sends to its child when the user
        presses the backspace key.
        """
    def set_bold_is_bright(self, bold_is_bright: bool) -> None:
        """
        Sets whether the SGR 1 attribute also switches to the bright counterpart
        of the first 8 palette colors, in addition to making them bold (legacy behavior)
        or if SGR 1 only enables bold and leaves the color intact.
        """
    def set_cell_height_scale(self, scale: float) -> None:
        """
        Sets the terminal's cell height scale to ``scale``.

        This can be used to increase the line spacing. (The font's height is not affected.)
        Valid values go from 1.0 (default) to 2.0 ("double spacing").
        """
    def set_cell_width_scale(self, scale: float) -> None:
        """
        Sets the terminal's cell width scale to ``scale``.

        This can be used to increase the letter spacing. (The font's width is not affected.)
        Valid values go from 1.0 (default) to 2.0.
        """
    def set_cjk_ambiguous_width(self, width: int) -> None:
        """
        This setting controls whether ambiguous-width characters are narrow or wide.
        (Note that when using a non-UTF-8 encoding set via :meth:`Vte.Terminal.set_encoding`,
        the width of ambiguous-width characters is fixed and determined by the encoding
        itself.)
        """
    def set_clear_background(self, setting: bool) -> None:
        """
        Sets whether to paint the background with the background colour.
        The default is ``True``.

        This function is rarely useful. One use for it is to add a background
        image to the terminal.
        """
    def set_color_background(self, background: Gdk.RGBA) -> None:
        """
        Sets the background color for text which does not have a specific background
        color assigned.  Only has effect when no background image is set and when
        the terminal is not transparent.
        """
    def set_color_bold(self, bold: Gdk.RGBA | None = ...) -> None:
        """
        Sets the color used to draw bold text in the default foreground color.
        If ``bold`` is ``None`` then the default color is used.
        """
    def set_color_cursor(self, cursor_background: Gdk.RGBA | None = ...) -> None:
        """
        Sets the background color for text which is under the cursor.  If ``None``, text
        under the cursor will be drawn with foreground and background colors
        reversed.
        """
    def set_color_cursor_foreground(self, cursor_foreground: Gdk.RGBA | None = ...) -> None:
        """
        Sets the foreground color for text which is under the cursor.  If ``None``, text
        under the cursor will be drawn with foreground and background colors
        reversed.
        """
    def set_color_foreground(self, foreground: Gdk.RGBA) -> None:
        """
        Sets the foreground color used to draw normal text.
        """
    def set_color_highlight(self, highlight_background: Gdk.RGBA | None = ...) -> None:
        """
        Sets the background color for text which is highlighted.  If ``None``,
        it is unset.  If neither highlight background nor highlight foreground are set,
        highlighted text (which is usually highlighted because it is selected) will
        be drawn with foreground and background colors reversed.
        """
    def set_color_highlight_foreground(self, highlight_foreground: Gdk.RGBA | None = ...) -> None:
        """
        Sets the foreground color for text which is highlighted.  If ``None``,
        it is unset.  If neither highlight background nor highlight foreground are set,
        highlighted text (which is usually highlighted because it is selected) will
        be drawn with foreground and background colors reversed.
        """
    def set_colors(self, foreground: Gdk.RGBA | None = ..., background: Gdk.RGBA | None = ..., palette: list[Gdk.RGBA] | None = ...) -> None:
        """
        ``palette`` specifies the new values for the 256 palette colors: 8 standard colors,
        their 8 bright counterparts, 6x6x6 color cube, and 24 grayscale colors.
        Omitted entries will default to a hardcoded value.

        ``palette_size`` must be 0, 8, 16, 232 or 256.

        If ``foreground`` is ``None`` and ``palette_size`` is greater than 0, the new foreground
        color is taken from ``palette``[7].  If ``background`` is ``None`` and ``palette_size`` is
        greater than 0, the new background color is taken from ``palette``[0].
        """
    def set_context_menu(self, menu: Gtk.Widget | None = ...) -> None:
        """
        Sets ``menu`` as the context menu in ``terminal``.
        Use ``None`` to unset the current menu.

        Note that a menu model set with :meth:`Vte.Terminal.set_context_menu_model`
        takes precedence over a menu set using this function.
        """
    def set_context_menu_model(self, model: Gio.MenuModel | None = ...) -> None:
        """
        Sets ``model`` as the context menu model in ``terminal``.
        Use ``None`` to unset the current menu model.
        """
    def set_cursor_blink_mode(self, mode: CursorBlinkMode | int) -> None:
        """
        Sets whether or not the cursor will blink. Using :data:`Vte.CursorBlinkMode.SYSTEM`
        will use the :class:`GtkSettings::gtk`-cursor-blink setting.
        """
    def set_cursor_shape(self, shape: CursorShape | int) -> None:
        """
        Sets the shape of the cursor drawn.
        """
    def set_default_colors(self) -> None:
        """
        Reset the terminal palette to reasonable compiled-in default color.
        """
    def set_delete_binding(self, binding: EraseBinding | int) -> None:
        """
        Modifies the terminal's delete key binding, which controls what
        string or control sequence the terminal sends to its child when the user
        presses the delete key.
        """
    def set_enable_a11y(self, enable_a11y: bool) -> None:
        """
        Controls whether or not the terminal will communicate with a11y backends.
        """
    def set_enable_bidi(self, enable_bidi: bool) -> None:
        """
        Controls whether or not the terminal will perform bidirectional text rendering.
        """
    def set_enable_fallback_scrolling(self, enable: bool) -> None:
        """
        Controls whether the terminal uses scroll events to scroll the history
        if the event was not otherwise consumed by it.

        This function is rarely useful, except when the terminal is added to a
        :class:`GtkScrolledWindow`, to perform kinetic scrolling (while vte itself does
        not, yet, implement kinetic scrolling by itself).
        """
    def set_enable_legacy_osc777(self, enable: bool) -> None:
        """
        Sets whether legacy OSC 777 sequences are translated to
        their corresponding termprops.
        """
    def set_enable_shaping(self, enable_shaping: bool) -> None:
        """
        Controls whether or not the terminal will shape Arabic text.
        """
    def set_enable_sixel(self, enabled: bool) -> None:
        """
        Set whether to enable SIXEL images.
        """
    @deprecated("Deprecated since 0.54.")
    def set_encoding(self, codeset: str | None = ...) -> bool:
        """
        Changes the encoding the terminal will expect data from the child to
        be encoded with.  For certain terminal types, applications executing in the
        terminal can change the encoding. If ``codeset`` is ``None``, it uses "UTF-8".

        Note: Support for non-UTF-8 is deprecated and may get removed altogether.
        Instead of this function, you should use a wrapper like luit(1) when
        spawning the child process.
        """
    def set_font(self, font_desc: Pango.FontDescription | None = ...) -> None:
        """
        Sets the font used for rendering all text displayed by the terminal,
        overriding any fonts set using gtk_widget_modify_font().  The terminal
        will immediately attempt to load the desired font, retrieve its
        metrics, and attempt to resize itself to keep the same number of rows
        and columns.  The font scale is applied to the specified font.
        """
    def set_font_options(self, font_options: cairo.FontOptions | None = ...) -> None:
        """
        Sets the terminal's font options to ``options``.

        Note that on GTK4, the terminal by default uses font options
        with ``CAIRO_HINT_METRICS_ON`` set; to override that, use this
        function to set a #cairo_font_options_t that has
        ``CAIRO_HINT_METRICS_OFF`` set.
        """
    def set_font_scale(self, scale: float) -> None:
        """
        Sets the terminal's font scale to ``scale``.
        """
    def set_input_enabled(self, enabled: bool) -> None:
        """
        Enables or disables user input. When user input is disabled,
        the terminal's child will not receive any key press, or mouse button
        press or motion events sent to it.
        """
    def set_mouse_autohide(self, setting: bool) -> None:
        """
        Changes the value of the terminal's mouse autohide setting.  When autohiding
        is enabled, the mouse cursor will be hidden when the user presses a key and
        shown when the user moves the mouse.  This setting can be read using
        :meth:`Vte.Terminal.get_mouse_autohide`.
        """
    def set_pty(self, pty: Pty | None = ...) -> None:
        """
        Sets ``pty`` as the PTY to use in ``terminal``.
        Use ``None`` to unset the PTY.
        """
    @deprecated("Deprecated since 0.58.")
    def set_rewrap_on_resize(self, rewrap: bool) -> None:
        """
        Controls whether or not the terminal will rewrap its contents, including
        the scrollback history, whenever the terminal's width changes.
        """
    def set_scroll_on_insert(self, scroll: bool) -> None:
        """
        Controls whether or not the terminal will forcibly scroll to the bottom of
        the viewable history when text is inserted, e.g. by a paste.
        """
    def set_scroll_on_keystroke(self, scroll: bool) -> None:
        """
        Controls whether or not the terminal will forcibly scroll to the bottom of
        the viewable history when the user presses a key.  Modifier keys do not
        trigger this behavior.
        """
    def set_scroll_on_output(self, scroll: bool) -> None:
        """
        Controls whether or not the terminal will forcibly scroll to the bottom of
        the viewable history when the new data is received from the child.
        """
    def set_scroll_unit_is_pixels(self, enable: bool) -> None:
        """
        Controls whether the terminal's scroll unit is lines or pixels.

        This function is rarely useful, except when the terminal is added to a
        :class:`GtkScrolledWindow.`
        """
    def set_scrollback_lines(self, lines: int) -> None:
        """
        Sets the length of the scrollback buffer used by the terminal.  The size of
        the scrollback buffer will be set to the larger of this value and the number
        of visible rows the widget can display, so 0 can safely be used to disable
        scrollback.

        A negative value means "infinite scrollback".

        Using a large scrollback buffer (roughly 1M+ lines) may lead to performance
        degradation or exhaustion of system resources, and is therefore not recommended.

        Note that this setting only affects the normal screen buffer.
        No scrollback is allowed on the alternate screen buffer.
        """
    def set_size(self, columns: int, rows: int) -> None:
        """
        Attempts to change the terminal's size in terms of rows and columns.  If
        the attempt succeeds, the widget will resize itself to the proper size.
        """
    def set_suppress_legacy_signals(self) -> None:
        """
        Suppress emissions of signals and property notifications
        that are deprecated.
        """
    def set_text_blink_mode(self, text_blink_mode: TextBlinkMode | int) -> None:
        """
        Controls whether or not the terminal will allow blinking text.
        """
    def set_word_char_exceptions(self, exceptions: str) -> None:
        """
        With this function you can provide a set of characters which will
        be considered parts of a word when doing word-wise selection, in
        addition to the default which only considers alphanumeric characters
        part of a word.

        The characters in ``exceptions`` must be non-alphanumeric, each character
        must occur only once, and if ``exceptions`` contains the character
        U+002D HYPHEN-MINUS, it must be at the start of the string.

        Use ``None`` to reset the set of exception characters to the default.
        """
    def set_xalign(self, align: Align | int) -> None:
        """
        Sets the horizontal alignment of ``terminal`` within its allocation.

        Note: ``VTE_ALIGN_START_FILL`` is not supported, and will be treated
          like :data:`Vte.Align.START`.
        """
    def set_xfill(self, fill: bool) -> None:
        """
        Sets the horizontal fillment of ``terminal`` within its allocation.

        Note: ``VTE_FILL_START_FILL`` is not supported, and will be treated
          like ``VTE_FILL_START``.
        """
    def set_yalign(self, align: Align | int) -> None:
        """
        Sets the vertical alignment of ``terminal`` within its allocation.
        """
    def set_yfill(self, fill: bool) -> None:
        """
        Sets the vertical fillment of ``terminal`` within its allocation.
        Note that yfill is only supported with yalign set to
        :data:`Vte.Align.START`, and is ignored for all other yalign values.
        """
    def spawn_async(self, pty_flags: PtyFlags | int, working_directory: str | None, argv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]], envv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]] | None, spawn_flags: GLib.SpawnFlags | int, child_setup: GLib.SpawnChildSetupFunc | None, timeout: int, cancellable: Gio.Cancellable | None = ..., callback: TerminalSpawnAsyncCallback | None = ...) -> None:
        """
        A convenience function that wraps creating the :class:`Vte.Pty` and spawning
        the child process on it. Like :meth:`Vte.Terminal.spawn_with_fds_async`,
        except that this function does not allow passing file descriptors to
        the child process. See :meth:`Vte.Terminal.spawn_with_fds_async` for more
        information.
        """
    @deprecated("Deprecated since 0.48.")
    def spawn_sync(self, pty_flags: PtyFlags | int, working_directory: str | None, argv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]], envv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]] | None, spawn_flags: GLib.SpawnFlags | int, child_setup: GLib.SpawnChildSetupFunc | None = ..., cancellable: Gio.Cancellable | None = ...) -> tuple[bool, GLib.Pid]:
        """
        Starts the specified command under a newly-allocated controlling
        pseudo-terminal.  The ``argv`` and ``envv`` lists should be ``None``-terminated.
        The "TERM" environment variable is automatically set to a default value,
        but can be overridden from ``envv``.
        ``pty_flags`` controls logging the session to the specified system log files.

        Note that ``G_SPAWN_DO_NOT_REAP_CHILD`` will always be added to ``spawn_flags``.

        Note also that ``G_SPAWN_STDOUT_TO_DEV_NULL``, ``G_SPAWN_STDERR_TO_DEV_NULL``,
        and ``G_SPAWN_CHILD_INHERITS_STDIN`` are not supported in ``spawn_flags``, since
        stdin, stdout and stderr of the child process will always be connected to
        the PTY.

        Note that all open file descriptors will be closed in the child. If you want
        to keep some file descriptor open for use in the child process, you need to
        use a child setup function that unsets the FD_CLOEXEC flag on that file
        descriptor.

        See vte_pty_new(), g_spawn_async() and :meth:`Vte.Terminal.watch_child` for more information.

        Beginning with 0.52, sets PWD to ``working_directory`` in order to preserve symlink components.
        The caller should also make sure that symlinks were preserved while constructing the value of ``working_directory``,
        e.g. by using :meth:`Vte.Terminal.get_current_directory_uri`, g_get_current_dir() or get_current_dir_name().
        """
    def spawn_with_fds_async(self, pty_flags: PtyFlags | int, working_directory: str | None, argv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]], envv: list[str | bytes | os.PathLike[str] | os.PathLike[bytes]] | None, fds: list[int] | None, map_fds: list[int] | None, spawn_flags: GLib.SpawnFlags | int, child_setup: GLib.SpawnChildSetupFunc | None, timeout: int, cancellable: Gio.Cancellable | None = ..., callback: TerminalSpawnAsyncCallback | None = ...) -> None:
        """
        A convenience function that wraps creating the :class:`Vte.Pty` and spawning
        the child process on it. See :meth:`Vte.Pty.new_sync`, :meth:`Vte.Pty.spawn_with_fds_async`,
        and :meth:`Vte.Pty.spawn_finish` for more information.

        When the operation is finished successfully, ``callback`` will be called
        with the child :class:`GPid`, and a ``None`` :class:`GError.` The child PID will already be
        watched via :meth:`Vte.Terminal.watch_child`.

        When the operation fails, ``callback`` will be called with a -1 :class:`GPid`,
        and a non-``None`` :class:`GError` containing the error information.

        Note that ``G_SPAWN_STDOUT_TO_DEV_NULL``, ``G_SPAWN_STDERR_TO_DEV_NULL``,
        and ``G_SPAWN_CHILD_INHERITS_STDIN`` are not supported in ``spawn_flags``, since
        stdin, stdout and stderr of the child process will always be connected to
        the PTY.

        If ``fds`` is not ``None``, the child process will map the file descriptors from
        ``fds`` according to ``map_fds``; ``n_map_fds`` must be less or equal to ``n_fds``.
        This function will take ownership of the file descriptors in ``fds``;
        you must not use or close them after this call.

        Note that all  open file descriptors apart from those mapped as above
        will be closed in the child. (If you want to keep some other file descriptor
        open for use in the child process, you need to use a child setup function
        that unsets the FD_CLOEXEC flag on that file descriptor manually.)

        Beginning with 0.60, and on linux only, and unless :data:`Vte.SPAWN_NO_SYSTEMD_SCOPE` is
        passed in ``spawn_flags``, the newly created child process will be moved to its own
        systemd user scope; and if :data:`Vte.SPAWN_REQUIRE_SYSTEMD_SCOPE` is passed, and creation
        of the systemd user scope fails, the whole spawn will fail.
        You can override the options used for the systemd user scope by
        providing a systemd override file for 'vte-spawn-.scope' unit. See man:systemd.unit(5)
        for further information.

        Note that if ``terminal`` has been destroyed before the operation is called,
        ``callback`` will be called with a ``None`` ``terminal``; you must not do anything
        in the callback besides freeing any resources associated with ``user_data``,
        but taking care not to access the now-destroyed :class:`Vte.Terminal`. Note that
        in this case, if spawning was successful, the child process will be aborted
        automatically.

        Beginning with 0.52, sets PWD to ``working_directory`` in order to preserve symlink components.
        The caller should also make sure that symlinks were preserved while constructing the value of ``working_directory``,
        e.g. by using :meth:`Vte.Terminal.get_current_directory_uri`, g_get_current_dir() or get_current_dir_name().
        """
    def unselect_all(self) -> None:
        """
        Clears the current selection.
        """
    def watch_child(self, child_pid: GLib.Pid) -> None:
        """
        Watches ``child_pid``. When the process exists, the :class:`Vte.Terminal`::child-exited
        signal will be called with the child's exit status.

        Prior to calling this function, a :class:`Vte.Pty` must have been set in ``terminal``
        using :meth:`Vte.Terminal.set_pty`.
        When the child exits, the terminal's :class:`Vte.Pty` will be set to ``None``.

        Note: g_child_watch_add() or g_child_watch_add_full() must not have
        been called for ``child_pid``, nor a :class:`GSource` for it been created with
        g_child_watch_source_new().

        Note: when using the g_spawn_async() family of functions,
        the ``G_SPAWN_DO_NOT_REAP_CHILD`` flag MUST have been passed.
        """
    def write_contents_sync(self, stream: Gio.OutputStream, flags: WriteFlags | int, cancellable: Gio.Cancellable | None = ...) -> bool:
        """
        Write contents of the current contents of ``terminal`` (including any
        scrollback history) to ``stream`` according to ``flags``.

        If ``cancellable`` is not ``None``, then the operation can be cancelled by triggering
        the cancellable object from another thread. If the operation was cancelled,
        the error ``G_IO_ERROR_CANCELLED`` will be returned in ``error``.

        This is a synchronous operation and will make the widget (and input
        processing) during the write operation, which may take a long time
        depending on scrollback history and ``stream`` availability for writing.
        """
    def do_bell(self) -> None: ...
    def do_char_size_changed(self, char_width: int, char_height: int) -> None: ...
    def do_child_exited(self, status: int) -> None: ...
    def do_commit(self, text: str, size: int) -> None: ...
    def do_contents_changed(self) -> None: ...
    @deprecated("Deprecated since 0.50.")
    def do_copy_clipboard(self) -> None:
        """
        Places the selected text in the terminal in the :class:`GDK_SELECTION_CLIPBOARD`
        selection.
        """
    def do_cursor_moved(self) -> None: ...
    def do_decrease_font_size(self) -> None: ...
    def do_deiconify_window(self) -> None: ...
    def do_encoding_changed(self) -> None: ...
    def do_eof(self) -> None: ...
    def do_icon_title_changed(self) -> None: ...
    def do_iconify_window(self) -> None: ...
    def do_increase_font_size(self) -> None: ...
    def do_lower_window(self) -> None: ...
    def do_maximize_window(self) -> None: ...
    def do_move_window(self, x: int, y: int) -> None: ...
    def do_paste_clipboard(self) -> None:
        """
        Sends the contents of the :class:`GDK_SELECTION_CLIPBOARD` selection to the
        terminal's child. It's called on paste menu item, or when
        user presses Shift+Insert.
        """
    def do_raise_window(self) -> None: ...
    def do_refresh_window(self) -> None: ...
    def do_resize_window(self, width: int, height: int) -> None: ...
    def do_restore_window(self) -> None: ...
    def do_selection_changed(self) -> None: ...
    def do_setup_context_menu(self, context: EventContext) -> None: ...
    def do_termprop_changed(self, prop: str) -> None: ...
    def do_termprops_changed(self, props: int, n_props: int) -> bool: ...
    def do_window_title_changed(self) -> None: ...
    bell: Signal[Self, [], None]
    char_size_changed: Signal[Self, [int, int], None]
    child_exited: Signal[Self, [int], None]
    commit: Signal[Self, [str, int], None]
    contents_changed: Signal[Self, [], None]
    copy_clipboard: SignalMethod[Self, [], None]
    current_directory_uri_changed: Signal[Self, [], None]
    current_file_uri_changed: Signal[Self, [], None]
    cursor_moved: Signal[Self, [], None]
    decrease_font_size: Signal[Self, [], None]
    deiconify_window: Signal[Self, [], None]
    encoding_changed: Signal[Self, [], None]
    eof: Signal[Self, [], None]
    hyperlink_hover_uri_changed: Signal[Self, [str, Gdk.Rectangle], None]
    icon_title_changed: Signal[Self, [], None]
    iconify_window: Signal[Self, [], None]
    increase_font_size: Signal[Self, [], None]
    lower_window: Signal[Self, [], None]
    maximize_window: Signal[Self, [], None]
    move_window: Signal[Self, [int, int], None]
    paste_clipboard: SignalMethod[Self, [], None]
    raise_window: Signal[Self, [], None]
    refresh_window: Signal[Self, [], None]
    resize_window: Signal[Self, [int, int], None]
    restore_window: Signal[Self, [], None]
    selection_changed: Signal[Self, [], None]
    setup_context_menu: Signal[Self, [EventContext | None], None]
    termprop_changed: Signal[Self, [str], None]
    termprops_changed: Signal[Self, [list[int]], bool]
    window_title_changed: Signal[Self, [], None]
    def do_current_directory_uri_changed(self) -> None: ...
    def do_current_file_uri_changed(self) -> None: ...
    def do_hyperlink_hover_uri_changed(self, object: str, p0: Gdk.Rectangle) -> None: ...

class TerminalClass:
    """
    All of these fields should be considered read-only, except for derived classes.
    """
    gimeta: ClassVar[_GIMeta]
    parent_class: Gtk.WidgetClass
    eof: Any
    child_exited: Any
    encoding_changed: Any
    char_size_changed: Any
    window_title_changed: Any
    icon_title_changed: Any
    selection_changed: Any
    contents_changed: Any
    cursor_moved: Any
    commit: Any
    deiconify_window: Any
    iconify_window: Any
    raise_window: Any
    lower_window: Any
    refresh_window: Any
    restore_window: Any
    maximize_window: Any
    resize_window: Any
    move_window: Any
    increase_font_size: Any
    decrease_font_size: Any
    copy_clipboard: Any
    paste_clipboard: Any
    bell: Any
    setup_context_menu: Any
    termprops_changed: Any
    termprop_changed: Any
    _padding: list[int]
    priv: TerminalClassPrivate

class TerminalClassPrivate:
    gimeta: ClassVar[_GIMeta]

class Uuid:
    """
    An object representing an UUID.
    """
    gimeta: ClassVar[_GIMeta]
    @classmethod
    def new_from_string(cls, str: str, len: int, fmt: UuidFormat | int) -> Self:
        """
        Creates a new UUID from its string representation ``str``.
        """
    @classmethod
    def new_v4(cls) -> Self:
        """
        Creates a new random UUID.
        """
    def dup(self) -> Uuid:
        """
        Creates a copy of ``uuid``.
        """
    def equal(self, other: Uuid) -> bool:
        """
        Compares ``uuid`` and ``other`` for equality.
        """
    def free(self) -> None:
        """
        Frees ``uuid``.
        """
    def free_to_string(self, fmt: UuidFormat | int, len: int) -> str:
        """
        Frees ``uuid`` and returns its string representation, see
        :meth:`Vte.Uuid.to_string` for more information.
        """
    def new_v5(self, data: str, len: int) -> Uuid:
        """
        Creates a new UUID for ``ns`` and ``str``.
        """
    def to_string(self, fmt: UuidFormat | int) -> tuple[str, int]:
        """
        Returns the string representation of ``uuid``.
        """
    @staticmethod
    def validate_string(str: str, len: int, fmt: UuidFormat | int) -> bool:
        """
        Checks whether ``str`` is a valid string representation of an UUID.
        """

MAJOR_VERSION: int
"""
The major version number of the VTE library
(e.g. in version 3.1.4 this is 3).
"""
MICRO_VERSION: int
"""
The micro version number of the VTE library
(e.g. in version 3.1.4 this is 4).
"""
MINOR_VERSION: int
"""
The minor version number of the VTE library
(e.g. in version 3.1.4 this is 1).
"""
REGEX_FLAGS_DEFAULT: int
SPAWN_NO_PARENT_ENVV: int
"""
Use this as a spawn flag (together with flags from :class:`GSpawnFlags`) in
:meth:`Vte.Pty.spawn_async`.

Normally, the spawned process inherits the environment from the parent
process; when this flag is used, only the environment variables passed
to :meth:`Vte.Pty.spawn_async` etc. are passed to the child process.
"""
SPAWN_NO_SYSTEMD_SCOPE: int
"""
Use this as a spawn flag (together with flags from :class:`GSpawnFlags`) in
:meth:`Vte.Pty.spawn_async`.

Prevents :meth:`Vte.Pty.spawn_async` etc. from moving the newly created child
process to a systemd user scope.
"""
SPAWN_REQUIRE_SYSTEMD_SCOPE: int
"""
Use this as a spawn flag (together with flags from :class:`GSpawnFlags`) in
:meth:`Vte.Pty.spawn_async`.

Requires :meth:`Vte.Pty.spawn_async` etc. to move the newly created child
process to a systemd user scope; if that fails, the whole spawn fails.

This is supported on Linux only.
"""
TERMPROP_CONTAINER_NAME: str
"""
A :data:`Vte.PropertyType.STRING` termprop that stores the name of the
container.
"""
TERMPROP_CONTAINER_RUNTIME: str
"""
A :data:`Vte.PropertyType.STRING` termprop that stores the runtime of the
container.
"""
TERMPROP_CONTAINER_UID: str
"""
A :data:`Vte.PropertyType.UINT` termprop that stores the user ID of the
container.
"""
TERMPROP_CURRENT_DIRECTORY_URI: str
"""
A :data:`Vte.PropertyType.URI` termprop that stores the current directory
URI as set by OSC 7.
Use this with :meth:`Vte.Terminal.ref_termprop_uri` instead of using
:meth:`Vte.Terminal.get_current_directory_uri`.

Note that this termprop is not settable via the termprop OSC.
"""
TERMPROP_CURRENT_FILE_URI: str
"""
A :data:`Vte.PropertyType.URI` termprop that stores the current file URI
as set by OSC 6.
Use this with :meth:`Vte.Terminal.ref_termprop_uri` instead of using
:meth:`Vte.Terminal.get_current_file_uri`.

Note that this termprop is not settable via the termprop OSC.
"""
TERMPROP_ICON_COLOR: str
TERMPROP_ICON_IMAGE: str
"""
A :data:`Vte.PropertyType.IMAGE` termprop to specify an image for use
as a favicon.

Applications should prefer to use this termprop, if set, over
the :data:`Vte.TERMPROP_ICON_COLOR` color.

Note that in this vte version, this termprop is always unset.
"""
TERMPROP_NAME_PREFIX: str
"""
The string prefix that any termprop's name must start with to be installed
by :func:`Vte.install_termprop`.
"""
TERMPROP_PROGRESS_HINT: str
"""
A :data:`Vte.PropertyType.INT` termprop that stores a hint how to interpret
the :data:`Vte.TERMPROP_PROGRESS_VALUE` termprop value. If set, this
termprop's value will be from the :class:`Vte.ProgressHint` enumeration.
An unset termprop should be treated as if it had value
:data:`Vte.ProgressHint.ACTIVE` if the :data:`Vte.TERMPROP_PROGRESS_VALUE`
termprop has a value

Note that this termprop never will have the value
:data:`Vte.ProgressHint.INACTIVE`.

The value of this termprop should be ignored unless the
:data:`Vte.TERMPROP_PROGRESS_VALUE` termprop has a value.

Note that before version 0.82, this termprop could not be set by
the termprop OSC, but instead only by OSC 9 ; 4 (ConEmu progress).
"""
TERMPROP_PROGRESS_VALUE: str
"""
A :data:`Vte.PropertyType.UINT` termprop that stores the progress of the running
command as a value between 0 and 100.

Note that before version 0.82, this termprop could not be set by
the termprop OSC, but instead only by OSC 9 ; 4 (ConEmu progress).
"""
TERMPROP_SHELL_POSTEXEC: str
"""
An ephemeral :data:`Vte.PropertyType.UINT` termprop that signals that the shell
has executed the commands entered at the prompt and these commands
have returned. The termprop value is the exit code.
"""
TERMPROP_SHELL_PRECMD: str
"""
A :data:`Vte.PropertyType.VALUELESS` termprop that signals that the shell
is going to prompt.
"""
TERMPROP_SHELL_PREEXEC: str
"""
A :data:`Vte.PropertyType.VALUELESS` termprop that signals that the shell
is preparing to execute the command entered at the prompt.
"""
TERMPROP_XTERM_TITLE: str
"""
A :data:`Vte.PropertyType.STRING` termprop that stores the xterm window title
as set by OSC 0 and OSC 2.
Use this with :meth:`Vte.Terminal.get_termprop_string` instead of using
:meth:`Vte.Terminal.get_window_title`.

Note that this termprop is not settable via the termprop OSC.
"""
TEST_FLAGS_ALL: int
TEST_FLAGS_NONE: int
@deprecated("Deprecated since 0.60.")
def get_encoding_supported(encoding: str) -> bool:
    """
    Queries whether the legacy encoding ``encoding`` is supported.

    If ICU support is not available, this function always returns ``False``.

    Note that UTF-8 is always supported; you can select it by
    passing ``None`` to :meth:`Vte.Terminal.set_encoding`.
    """
@deprecated("Deprecated since 0.60.")
def get_encodings(include_aliases: bool) -> list[str]:
    """
    Gets the list of supported legacy encodings.

    If ICU support is not available, this returns an empty vector.
    Note that UTF-8 is always supported; you can select it by
    passing ``None`` to :meth:`Vte.Terminal.set_encoding`.
    """
def get_feature_flags() -> FeatureFlags:
    """
    Gets features VTE was compiled with.
    """
def get_features() -> str:
    """
    Gets a list of features vte was compiled with.
    """
def get_major_version() -> int:
    """
    Returns the major version of the VTE library at runtime.
    Contrast this with :data:`Vte.MAJOR_VERSION` which represents
    the version of the VTE library that the code was compiled
    with.
    """
def get_micro_version() -> int:
    """
    Returns the micro version of the VTE library at runtime.
    Contrast this with :data:`Vte.MICRO_VERSION` which represents
    the version of the VTE library that the code was compiled
    with.
    """
def get_minor_version() -> int:
    """
    Returns the minor version of the VTE library at runtime.
    Contrast this with :data:`Vte.MINOR_VERSION` which represents
    the version of the VTE library that the code was compiled
    with.
    """
def get_termprops() -> list[str] | None:
    """
    Gets the names of the installed termprops in an unspecified order.
    """
def get_user_shell() -> str:
    """
    Gets the user's shell, or ``None``. In the latter case, the
    system default (usually "/bin/sh") should be used.
    """
def install_termprop(name: str, type: PropertyType | int, flags: PropertyFlags | int) -> int:
    """
    Installs a new terminal property that can be set by the application.

    ``name`` must follow the rules for termprop names as laid out above; it
    must have at least 4 components, the first two of which must be "vte",
    and "ext". Use the :data:`Vte.TERMPROP_NAME_PREFIX` macro which defines this
    name prefix.

    You should use an identifier for your terminal as the first component
    after the prefix, as a namespace marker.

    It is a programming error to call this function with a ``name`` that does
    not meet these requirements.

    It is a programming error to call this function after any :class:`Vte.Terminal`
    instances have been created.

    It is a programming error to call this function if the named termprop
    is already installed with a different type or flags.
    """
def install_termprop_alias(name: str, target_name: str) -> int:
    """
    Installs a new terminal property ``name`` as an alias for the terminal
    property ``target_name``.
    """
def pty_error_quark() -> GLib.Quark:
    """
    Error domain for VTE PTY errors. Errors in this domain will be from the :class:`Vte.PtyError`
    enumeration. See :class:`GError` for more information on error domains.
    """
def query_termprop(name: str) -> tuple[bool, str, int, PropertyType | int, PropertyFlags | int]:
    """
    Gets the property type of the termprop. For properties installed by
    :func:`Vte.install_termprop`, the name starts with "vte.ext.".

    For an alias termprop (see :func:`Vte.install_termprop_alias`), ``resolved_name``
    will be name of the alias' target termprop; otherwise it will be ``name``.
    """
def query_termprop_by_id(prop: int) -> tuple[bool, str, PropertyType | int, PropertyFlags | int]:
    """
    Like :func:`Vte.query_termprop` except that it takes the termprop by ID.
    See that function for more information.

    For an alias termprop (see :func:`Vte.install_termprop_alias`), ``resolved_name``
    will be name of the alias' target termprop; otherwise it will be ``name``.
    """
def regex_error_quark() -> GLib.Quark: ...
def uuid_validate_string(str: str, len: int, fmt: UuidFormat | int) -> bool:
    """
    Checks whether ``str`` is a valid string representation of an UUID.
    """
