# Copyright 2026 Johan Dahlin
#
# SPDX-License-Identifier: LGPL-2.1-or-later
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, see <http://www.gnu.org/licenses/>.

# Ratchet: residual explicit Any not yet removed (adopting --disallow-any-explicit
# incrementally). Remove this line once the file is Any-clean.
# mypy: disable-error-code="explicit-any"

"""Type stubs for ginext.private (C extension re-exports)."""

from __future__ import annotations

import types
from collections.abc import Callable
from typing import Any, Self
from ginext.abi import ABIProfile
from ginext.namespace import Namespace
from ginext.private import _gobject
from ginext.private._gobject import CallableInfo, SignalInfo, VFuncInfo
from ginext.signal.descriptor import SignalDescriptor

class GIMeta:
    """C extension metaclass for GObject wrapper classes."""

    gtype: int
    type_name: str
    version: str
    size: int
    namespace: Any
    method_owner_name: str
    method_infos: dict[str, tuple[CallableInfo, bool]]
    signal_infos: dict[str, SignalInfo | SignalDescriptor]
    signal_method_backings: dict[str, Callable[..., object]]
    vfunc_infos: dict[str, VFuncInfo]
    extensions: dict[str, dict[str, object]]
    pspecs: dict[str, object]
    qualified_name: str
    gi_info: Any  # None for Python-defined subclasses; GIR ObjectInfo/InterfaceInfo for built classes
    typelib_methods: dict[str, Callable[..., object]]
    anonymous_unions: list[object]
    descriptor: object
    functions: object
    hidden_fields: set[str]
    info: object
    profile: ABIProfile

    @classmethod
    def from_type_name(cls, type_name: str, info: object = ...) -> GIMeta: ...
    @classmethod
    def info_by_gtype(cls, gtype: int) -> Any: ...
    @classmethod
    def register_subclass(
        cls, py_cls: type, annotations: dict[str, Any], type_name: str
    ) -> GIMeta: ...
    def get_property(self, obj: object, name: str) -> object: ...
    def param_spec(self, name: str) -> object: ...
    def set_property(self, obj: object, name: str, value: object) -> None: ...
    def list_property_names(self) -> list[str]: ...
    def add_emission_hook(self, detailed_signal: str, callback: object) -> int: ...
    def remove_emission_hook(self, detailed_signal: str, hook_id: int) -> None: ...
    def register_property_type_info(self, name: str, info: object) -> None: ...
    def register_signal(
        self,
        signal_name: str,
        return_gtype: int,
        arg_gtypes: tuple[int, ...],
        *extra_args: object,
    ) -> int: ...
    def install_native_vfunc_attrs(self, cls: type, info: object) -> None: ...

class GObject:
    @classmethod
    def construct_with_properties(cls, properties: dict[str, object]) -> int: ...
    @classmethod
    def new_bound_from_c(cls, ptr: object | int, owns_ref: bool = ...) -> Self: ...
    @classmethod
    def new_preallocated_from_c(
        cls, ptr: object | int, handlers: object = ...
    ) -> Self: ...
    def bind_from_c(self, ptr: object | int, owns_ref: bool = ...) -> None: ...
    def is_bound(self) -> bool: ...
    def owns_ref(self) -> bool: ...
    def pointer_value(self) -> int: ...
    def release_ref(self) -> None: ...
    def preserve_wrapper_state(self) -> None: ...
    def ref_sink(self) -> None: ...
    def make_floating(self) -> None: ...
    def ref_count(self) -> int: ...
    def is_floating(self) -> bool: ...
    def freeze_notify(self) -> None: ...
    def thaw_notify(self) -> None: ...
    def run_dispose(self) -> None: ...
    def disconnect_handler_id(self, handler_id: int) -> None: ...
    def handler_id_is_connected(self, handler_id: int) -> bool: ...
    def stop_emission_by_name(self, detailed_signal: str) -> None: ...
    def get_property_by_name(self, name: str) -> object: ...
    def set_property_by_name(self, name: str, value: object) -> None: ...
    @classmethod
    def from_c(cls, ptr: object | int) -> object: ...
    def prime_construction_state(
        self, ptr: object | int, handlers: object = ...
    ) -> None: ...
    def connect_constructor_handler(
        self, signal_name: str, callback: object, signal_arg_limit: int
    ) -> int: ...
    def signal_is_action(self, signal_name: str) -> bool: ...
    def signal_connect(
        self,
        signal_name: str,
        callback: object,
        after: bool = ...,
        once: bool = ...,
        owner: object = ...,
        signal_info: object = ...,
        signal_arg_limit: int = ...,
    ) -> int: ...
    def signal_emit(
        self,
        signal_name: str,
        signal_info: object = ...,
        emit_args: tuple[object, ...] | None = ...,
    ) -> object: ...
    def signal_emit_with_gtypes(
        self,
        signal_name: str,
        arg_gtypes: tuple[int, ...],
        emit_args: tuple[object, ...],
    ) -> object: ...

class GBoxed: ...

class DeclaredProperty:
    name: str
    owner: type
    pspec: object

    @classmethod
    def from_spec(
        cls,
        spec: object,
        owner: type,
        prop_id: int,
        pspec: object,
        coerce_gtype_int: bool = ...,
    ) -> DeclaredProperty: ...

class MethodDescriptor:
    gimeta: types.SimpleNamespace
    __name__: str
    __qualname__: str

    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

# Low-level C functions — typed as Any for internals that aren't
# part of the public API.
def build_callable_descriptor(*args: Any, **kwargs: Any) -> MethodDescriptor: ...
def invoke(
    namespace: str | Namespace | types.ModuleType,
    name: str = ...,
    *args: Any,
    **kwargs: Any,
) -> Any: ...
def class_struct_wrapper(*args: Any) -> Any: ...
def installed_versions() -> dict[str, list[str]]: ...
def invoke_callable_descriptor(*args: Any) -> Any: ...
def invoke_stats() -> dict[str, Any]: ...
def namespace_dir(namespace: str, version: str | None) -> list[str]: ...
def namespace_find(
    namespace: str, version: str | None, name: str
) -> tuple[str, Any]: ...
def preload_shared_library(path: str) -> None: ...
def register_gobject_callbacks(**hooks: Any) -> None: ...
def synthetic_callable(qualified_name: str) -> Any: ...
def instantiatable_unref(ptr: int) -> None: ...
def register_static(gtype_base: int, type_name: str, members: dict[str, int] | None = ...) -> int: ...
def fundamental_from_pointer(cls: type, ptr: int, gtype: int) -> _gobject.Fundamental: ...
Fundamental = _gobject.Fundamental
def record_field_get(obj: Any, field_info: Any, *args: Any) -> Any: ...
def record_field_set(obj: Any, field_info: Any, *args: Any) -> None: ...
def record_install_field_descriptors(cls: Any, info: Any) -> None: ...
def record_field_names(info: Any) -> tuple[str, ...]: ...
def record_ensure_size(obj: Any, size: int) -> None: ...
def record_memory_get(obj: Any, *args: Any) -> Any: ...
def record_memory_set(obj: Any, *args: Any) -> None: ...
def record_copy(obj: Any, *args: Any) -> Any: ...
def record_pointer_equal(a: Any, b: Any) -> bool: ...
def record_pointer_value(obj: object) -> int: ...
def record_new(cls: Any, *args: Any) -> Any: ...
def register_boxed_class(*args: Any) -> None: ...
def require_namespace(namespace: str, version: str | None) -> str: ...
def reset_invoke_stats() -> None: ...
def gvalue_get_type() -> int: ...
def gvalue_get_gtype(value: Any) -> int: ...
def gvalue_init_value(value: Any, gtype: int) -> None: ...
def gvalue_unset_value(value: Any) -> None: ...
def gvalue_reset_value(value: Any) -> None: ...
def gvalue_array_get_nth_type(array: Any, n: int) -> int: ...
def gvalue_get_value(value: Any) -> Any: ...
def gvalue_set_value(value: Any, v: Any) -> None: ...
def gvalue_set_to_py_fallback(callback: Callable[[int, int], Any] | None) -> None: ...
def gvalue_get_to_py_fallback() -> Callable[[int, int], Any] | None: ...
def gvalue_set_from_py_converter(
    callback: Callable[[Any, int, int], Any] | None,
) -> None: ...
def gvalue_get_from_py_converter() -> Callable[[Any, int, int], Any] | None: ...
def gvalue_set_data_int(value_ptr: int, index: int, value: int) -> None: ...
def gvalue_set_data_uint64(value_ptr: int, index: int, value: int) -> None: ...
def register_converter(
    to_py: Callable[[int, int], Any] | None,
    from_py: Callable[[Any, int, int], Any] | None,
) -> None: ...
def get_converters() -> tuple[
    Callable[[int, int], Any] | None, Callable[[Any, int, int], Any] | None
]: ...
def gvalue_new_for_gtype(gtype: int) -> Any: ...
def gvalue_wrap_pointer(value_ptr: int) -> Any: ...
def gstrv_get_type() -> int: ...
def gerror_get_type() -> int: ...
def ensure_cairo_gobject_types() -> None: ...
def glib_event_source_new(*args: Any) -> Any: ...
def type_has_value_table(gtype: int) -> bool: ...
def param_spec_info(pspec: Any) -> Any: ...
def param_spec_default_value(pspec: Any) -> Any: ...
def param_spec_numeric_info(pspec: Any) -> Any: ...
def callable_has_self(info: Any) -> bool: ...
def callable_has_user_data_slot(info: Any) -> bool: ...
def callable_get_arg_names(info: Any) -> list[str]: ...
def callable_async_info(info: Any) -> tuple[str, int] | None: ...
def callable_name(info: Any) -> str: ...
def object_info(info: Any) -> dict[str, Any]: ...
def record_info(info: Any) -> dict[str, Any]: ...
def girepository_struct_info_anonymous_union_offset(info: Any, *args: Any) -> int: ...
def girepository_constant_info_get_value(info: Any) -> Any: ...
