# Ratchet: residual explicit Any not yet removed (adopting --disallow-any-explicit
# incrementally). Remove this line once the file is Any-clean.
# mypy: disable-error-code="explicit-any"

"""Type stubs for ginext.private._gobject (C extension).

Method signatures are canonical in C (``__text_signature__``/``__doc__`` in
``src/ginext/private/GIRepository/*.c``) and readable via inspect.signature().
This file declares only attribute types, ``__match_args__``, and the methods
that the rest of ginext's source code calls — to keep mypy happy without
duplicating every method. As more callers are typed, entries here grow; as the
C gains __text_signature__ annotations that stubgen can read at runtime, they
can be removed.
"""

from typing import Any

def gobject_add_weak_notify(obj: object, callback: object, args: tuple[object, ...]) -> object: ...

class BaseInfo:
    __match_args__ = ("name", "namespace")
    name: str
    namespace: str
    def get_name(self) -> str: ...
    def get_namespace(self) -> str: ...

class RegisteredTypeInfo(BaseInfo):
    __match_args__ = ("name", "gtype")
    gtype: int
    def get_g_type(self) -> int: ...
    def get_type_name(self) -> str: ...

class CallableInfo(BaseInfo):
    __match_args__ = ("name", "arg_names")
    arg_names: list[str]
    has_user_data_slot: bool
    def is_method(self) -> bool: ...
    def is_async(self) -> bool: ...
    def get_n_args(self) -> int: ...
    def may_return_null(self) -> bool: ...
    def skip_return(self) -> bool: ...
    def get_return_type(self) -> TypeInfo: ...
    def get_arg(self, n: int) -> ArgInfo: ...
    def find_method(self, name: str) -> FunctionInfo | None: ...

class FunctionInfo(CallableInfo):
    def invoke(self, *args: Any) -> Any: ...

class SignalInfo(CallableInfo): ...
class VFuncInfo(CallableInfo): ...
class CallbackInfo(CallableInfo): ...

class ObjectInfo(RegisteredTypeInfo):
    def get_n_methods(self) -> int: ...
    def get_n_signals(self) -> int: ...
    def get_n_vfuncs(self) -> int: ...
    def get_n_properties(self) -> int: ...
    def get_n_interfaces(self) -> int: ...
    def get_fundamental(self) -> bool: ...
    def find_method(self, name: str) -> FunctionInfo | None: ...
    def anonymous_union_offset(self, field_name: str, align: int) -> int: ...
    def object_info(self) -> dict[str, Any]: ...

class InterfaceInfo(RegisteredTypeInfo):
    def get_n_methods(self) -> int: ...
    def get_n_properties(self) -> int: ...
    def get_n_signals(self) -> int: ...
    def get_n_vfuncs(self) -> int: ...
    def find_method(self, name: str) -> FunctionInfo | None: ...
    def object_info(self) -> dict[str, Any]: ...

class StructInfo(RegisteredTypeInfo):
    def get_n_methods(self) -> int: ...
    def get_size(self) -> int: ...
    def find_method(self, name: str) -> FunctionInfo | None: ...
    def anonymous_union_offset(self, field_name: str, align: int) -> int: ...
    def record_info(self) -> dict[str, Any]: ...

class UnionInfo(RegisteredTypeInfo):
    def get_n_methods(self) -> int: ...
    def get_size(self) -> int: ...
    def find_method(self, name: str) -> FunctionInfo | None: ...
    def anonymous_union_offset(self, field_name: str, align: int) -> int: ...
    def record_info(self) -> dict[str, Any]: ...

class EnumInfo(RegisteredTypeInfo):
    __match_args__ = ("name", "members")
    members: list[tuple[str, int]]
    def get_n_values(self) -> int: ...

class FlagsInfo(EnumInfo): ...

class ConstantInfo(BaseInfo):
    __match_args__ = ("name", "value")
    value: object
    def get_value(self) -> Any: ...

class ArgInfo(BaseInfo):
    def get_direction(self) -> int: ...
    def may_be_null(self) -> bool: ...
    def is_optional(self) -> bool: ...
    def get_closure_index(self) -> int: ...
    def get_destroy_index(self) -> int: ...

class FieldInfo(BaseInfo): ...
class PropertyInfo(BaseInfo): ...

class TypeInfo(BaseInfo):
    def get_tag(self) -> int: ...
    def is_pointer(self) -> bool: ...
    def get_interface(self) -> BaseInfo | None: ...
    def get_array_length_index(self) -> int: ...

class ValueInfo(BaseInfo):
    def get_value(self) -> int: ...

class UnresolvedInfo(BaseInfo): ...

class Fundamental:
    __instance_ptr__: int
    __gtype__: int
