from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _parse_spec(spec: str) -> tuple[str, str]:
    if ":" not in spec:
        raise SystemExit(f"bad namespace spec {spec!r}: want NAME:VERSION")
    name, version = spec.split(":", 1)
    return name, version


def _write_init_pyi(namespaces: list[str], out_dir: Path) -> None:
    lines = [
        "# Auto-generated by packages/typelib/generate_stubs.py. Do not edit.",
        "# Re-exports the native test-typelib stubs installed with ginext.",
        "from typing import Any",
        "",
    ]
    lines.extend(
        f"from . import {namespace} as {namespace}" for namespace in sorted(namespaces)
    )
    lines += [
        "",
        "def __getattr__(name: str) -> Any: ...",
        "",
    ]
    (out_dir / "__init__.pyi").write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("out_dir", type=Path)
    parser.add_argument("specs", nargs="+")
    args = parser.parse_args(argv)

    repo_root = Path(__file__).resolve().parents[2]
    stubgen_src = repo_root / "packages" / "ginext-stubgen" / "src"
    if str(stubgen_src) not in sys.path:
        sys.path.insert(0, str(stubgen_src))

    from ginext_stubgen import find_gir, generate

    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []

    for spec in args.specs:
        name, version = _parse_spec(spec)
        gir = find_gir(name, version)
        if gir is None:
            raise SystemExit(f"missing GIR for {name}-{version}")
        namespace, text = generate(gir, mode="native")
        (out_dir / f"{namespace}.pyi").write_text(text, encoding="utf-8")
        written.append(namespace)

    _write_init_pyi(written, out_dir)
    (out_dir / "py.typed").write_text("", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
